kivy/python-for-android

recipes/android/src/android/_android.pyx

Allows android package to be imported in a service.

fix android package for services

---

recipes/audiostream/recipe.sh
recipes/pyparsing/recipe.sh

pyparsing is pure python, and AUDIOSTREAM_ROOT
is not used anywhere. The audiostream module builds both
in arm and x86 without setting the envvar.

removed reference to ARM from audiostream and pyparsing recipes

---

recipes/eventlet/patches/fix-setuptools.patch
recipes/eventlet/recipe.sh

Uses distutils to install, as setuptools is not available by default (yet).
Can be cleaned up after https://github.com/kivy/python-for-android/tree/recipe-pynacl gets merged

Recipe for eventlet lib

---

distribute.sh

When pip is needed, it's provided by the mandatory virtual environment.
Therefore, there is no need to require an external one.

Don't search for the pip command

---

src/build.py

Currently the --ignore-path option only applies for public data.
Since installing "release" apk version on /data requires using private data, the ignore filter is also needed here.

Apply ignore_path filter to private data

---

distribute.sh

Prevents env vars set in one recipe build function from affecting other recipe build functions.

save and restore environment when running recipe functions

---

distribute.sh

This fixes the invocation of mktemp so it works on OS X also.

fix mktemp usage for OS X

---

distribute.sh

This simple addition checks that the calculated NDK path is correct. It wasn't for me, and resulted in bizarre errors down the track when it's simple enough to check at this point.

check the calculated NDK platform path for validity

---

distribute.sh

Reverts kivy/python-for-android#344
This was not tested on Linux, which is now broken.

Revert "fix mktemp usage for OS X"

---

recipes/android/src/android/_android.pyx

when using WIndow.softinput_mode='pan' with kivy. I noticed that changing the orientation of the screen (on android) (e.g. from portrait to landscape), caused the display to misbehave: eventhough the system keyboard had not be requested, the whole screen seem to be offset as if it had been.
The problem was that get_keyboard_height from the android module had a static notion of height.  My patch causes it to reevaluate the height (this is especially important in case of dispaly orientation change).
With my app, I now get the expected behaviour.

make get_keyboard_height more dynamic

---

recipes/android/src/android/_android.pyx

Make `get_keyboard_height` faster by using a listener to respond to layout changes, and update keyboard height accordingly, rather than polling it every time the function is called.

use listener to respond to keyboard height changes

---

recipes/midistream/recipe.sh

MIDI streaming is not oficially suported on Android, but works and much of fun.
See: https://github.com/b3b/midistream

Recipe for MIDI streaming

---

recipes/enum34/recipe.sh
recipes/six/recipe.sh
recipes/zeroconf/patches/no_ctypes_fix.patch
recipes/zeroconf/recipe.sh

A recipe for building zeroconf and six (additional zeroconf dependency).

Recipes for zeroconf and six

---

distribute.sh

Fix issue #337.
Clean `PYTHONPATH` for virtualenv so that pure Python modules will not be affected by environment created by recipes.

Fix issue #337

---

recipes/freetype/recipe.sh
recipes/harfbuzz/recipe.sh

reciepe for freetype and harfbuzz libraries allows freetype python file to be imported.

reciepes for freetype and harfbuzz

---

recipes/kivy/recipe.sh

Not for merging without discussion!
This would fix https://github.com/kivy/python-for-android/issues/234
I'm not sure if this is the right fix, but I'm doing a pr in the hope that someone who knows what's going on will see it. As far as I can tell, it *does* resolve the linked issue.
Without this pr, something doesn't work - the build_ext lines don't place object files where the biglink script can see them. I think the issue is that they recognise the pyx source files haven't changed and therefore don't rebuild the object files, whereas with this fix cython is always called and the files are always rebuilt.
As discussed with tito, maybe there is a better solution, but I'm not even completely sure what's going on and I couldn't track it down better than this.

Fixed kivy recipe to work on repeated runs with P4A_kivy_DIR

---

src/templates/AndroidManifest.tmpl.xml

Fixes a crash which occurs when using auto-rotation. I don't use jinja2, but this doesn't seem valid anyway (mixing template syntax with Python syntax). It did result in those conditions evaluating False when they previously evaluated True, and then crashed during rotation on my Note 4.

fix rotation bug with AndroidManifest.xml generation

---

src/src/org/renpy/android/SDLSurfaceView.java

Make sure `keyboard_height` is triggered while being dismissed.

---

recipes/leveldb/recipe.sh
recipes/plyvel/recipe.sh

LevelDB is Google's key-value storage library. Plyvel is a Python interface to LevelDB.

add leveldb and plyvel recipes

---

recipes/libsodium/recipe.sh

This recipe was tested with the following app:
```python
__version__ = "1.0.0"
import kivy
import libnacl
import time
import sys
from libnacl import public
kivy.require('1.9.0')
from kivy.app import App
from kivy.uix.label import Label
from kivy.logger import Logger
class MyApp(App):
def build(self):
msg = b'You\'ve got two empty halves of coconut and you\'re bangin\' \'em together.'
bob = libnacl.public.SecretKey()
alice = libnacl.public.SecretKey()
bob_box = libnacl.public.Box(bob.sk, alice.pk)
alice_box = libnacl.public.Box(alice.sk, bob.pk)
bob_ctxt = bob_box.encrypt(msg)
bclear = alice_box.decrypt(bob_ctxt)
alice_ctxt = alice_box.encrypt(msg)
aclear = alice_box.decrypt(alice_ctxt)
return Label(text=aclear)
if __name__ == '__main__':
MyApp().run()
```
If `libsodium` compiles and is …

add libsodium recipe

---

setup.py

"colorama<0.3" have no LIGHTBLUE_EX. Fixes.

[FIX] AttributeError: 'AnsiCodes' object has no attribute 'LIGHTBLUE_EX'

---

src/build.py

This should fix a python3 error where this value is compared with an int in the AndroidManifest.xml template - currently it's a str vs int comparison which only works in python2.

Converted --minsdk option input to int

---

pythonforandroid/toolchain.py

It is correct that we need libtool, but the executable is called libtoolize. Therefore sh.which(executable) won't work in this case. I renamed the variable "tool" to "executable", so other developers won't get confused and also add package names here.

[revamp] Correcting check for libtool

---

pythonforandroid/toolchain.py

Found the missing setting to make command outputs non-blocking. In my point of view this is the expected behaviour.

[revamp] Adding expected non-blocking output

---

pythonforandroid/toolchain.py

ANDROID_API = 14 is obsolete according to the Android SDK Manager.
Thats why I would suggest to update the DEFAULT_ANDROID_API at least to the next supported version.

[revamp] toolchain: Update DEFAULT_ANDROID_API to 15

---

distribute.sh
recipes/python/patches/android-21.patch
recipes/python/recipe.sh

This patch enables python to be build for android-21 and fixes the problems for using gcc >=4.8, too

Enabling android-21 builds

---

pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/python2/patches/fix-ftime-removal.patch

The `sys/timeb.h` header was removed in Android 21, because this header and the
`ftime` function were removed from the POSIX 2008 specification.
(Info reference: https://rbcommons.com/s/OpenH264/r/683/diff/1/ )
Closes #261, and replaces #410. The only difference is that in #410 the `#undef` is surrounded by an `#ifdef ANDROID`, which I didn't think was necessary (because this is only ever going to be patched for Android, because... `python-for-android`), but I can add it if desired.

[revamp] Undefine HAVE_FTIME for Android API > 19

---

pythonforandroid/toolchain.py

While working on the Qt5 recipe, I wanted to download the latest code from git. I know there is the possibility to download a tar or zip archive, but Qt5 uses submodules for their branch.
These won't be packaged by GitHub, so I started to add git support.
While coding I found out that a function, which should extract data from an archive isn't used anymore. But I can be wrong: https://github.com/kivy/python-for-android/compare/kivy:revamp...thopiekar:toolchain_git_support?expand=1#diff-9386f079c34547ba8b06a93309463a72L1365

[revamp] Adding direct git support to toolchain.py

---

README.rst

It's not an issue of python-for-android. NumPy can't be built using ndr8c - gcc segfaults during processing of this command:
```
./distribute.sh -m "sqlite3 numpy kivy"
```
Fails with this log:
```
ccache: build/src.linux-x86_64-2.7/numpy/core/src/multiarray/lowlevel_strided_loops.c
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: In function '_cast_ubyte_to_ulonglong':
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:886: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: In function '_cast_ubyte_to_ulonglong':
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:886: internal compiler error: …
```

Update NDK download link as NumPy can't be built using NDK r8c

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2python3/build/build.py

A more complete setup might try to factor out the commonalities between the three bootstraps (`pygame`, `sdl2` and `sdl2python3`), but for now this at least allows permissions to be specified for SDL2 bootstraps.

Add --permission to SDL2 bootstraps

---

src/build.py

build.py would fail here on versions such as 0.1.1-r4. This fixed it for me - I also checked the resulting string in AndroidManifest, it seems proper.

Fixed version number logic for non-int versions

---

pythonforandroid/toolchain.py

suppressing colorization makes the output easier to process by other scripts.

suppress colorization if stdout is not a tty

---

pythonforandroid/toolchain.py

This patch sends log messages to stderr.  See e.g. the url below for why that's preferable:
http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout
basically stdout is for primary data, and stderr for ancillary data (erros, notifications, ...), and this separation plays well with combining processes using pipes.  It improves on my previous patch in that log info when calling p4a from buildozer will no longer be thrown away.
I also modified colorization, whether on stdout or stderr, to happen only when the corresponding stream is a tty.

send notifications to stderr. use colorization on stdout or stderr only if a tty.

---

pythonforandroid/toolchain.py

The updated toolchain.py fails if the output of shprint contains unicode characters.
This can happen if you use something like:
shprint(sh.cp, '-v', entry,  self.ctx.get_libs_dir(arch.arch))
and results in:
File "/usr/lib64/python2.7/site-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 2312, in build_recipes
recipe.postbuild_arch(arch)
File "/usr/lib64/python2.7/site-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/recipes/qt5base/__init__.py", line 118, in postbuild_arch
shprint(sh.cp, '-v', entry,  self.ctx.get_libs_dir(arch.arch))
File "/usr/lib64/python2.7/site-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 187, in shprint
shorten_string(msg, msg_width), width=msg_width))
UnicodeEncodeError: 'ascii' codec can't …

Fixing unicode error

---

.gitignore
pythonforandroid/toolchain.py

` type=bool` is not the way to do boolean options with `argparser`.  I added  `add_boolean_option` and used it to automatically define both `--foo` and `--no-foo` options.

Fix boolean options

---

pythonforandroid/toolchain.py

Latest toolchain.py has typo error:
File "/usr/lib64/python2.7/site-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 1822, in download
filename = shprint(sh.basename, url).stdout[:-1].decode('utf-8')
File "/usr/lib64/python2.7/site-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 207, in shprint
Style.RESET_ALL, ' ', width=(columns - 1)))
NameError: global name 'Style' is not defined
This patch fixes this error

Fixing missing Colo

---

pythonforandroid/recipes/audiostream/__init__.py
pythonforandroid/recipes/audiostream/recipe.sh

I've included code to allow either sdl or sdl2 dependency.
However the library itself only links against SDL1 at the moment - the library needs to be changed to know when it is being linked against SDL2 (library names to link are slightly different)

Added audiostream recipe

---

pythonforandroid/toolchain.py

Shows the path to the `ndk_platform` when it is not found, and shows a final error if `prepare_build_environment` is not `ok`.

add new error message and improve existing

---

pythonforandroid/bootstraps/sdl2/build/jni/src/Android.mk
pythonforandroid/recipes/sdl2/__init__.py
pythonforandroid/toolchain.py

Makes things compile when you have openssl in your requirements, making the python2 directory `python2-openssl` instead of `python2`.

fix hard coded python2 path in sdl2 Android.mk

---

pythonforandroid/toolchain.py

Makes the OpenSSL recipe work (otherwise, it was renaming OpenSSL-x.y.z/ACKNOWLEDGEMENTS to openssl instead of the directory).

fix root directory for tgz extraction

---

pythonforandroid/patching.py
pythonforandroid/recipes/kivysdl2python3/__init__.py
pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/pycrypto/__init__.py
pythonforandroid/recipes/pygame/__init__.py
pythonforandroid/recipes/pyjnius/__init__.py
pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/sdl2/__init__.py
pythonforandroid/recipes/sdl2_image/__init__.py
pythonforandroid/recipes/sdl2_mixer/__init__.py
pythonforandroid/recipes/sdl2python3/__init__.py
pythonforandroid/recipes/vispy/__init__.py
pythonforandroid/toolchain.py

Simplifies patching for recipes by removing boilerplate.

easier patching for recipes

---

pythonforandroid/toolchain.py

Current code for removing redundant dependency graphs has a bug in it where graph[i] was compared against itself and then removed (as it appears equal to itself).  This caused #515.  In this PR I've rearranged the loop in the function for removing redundant graphs to prevent this issue

Fix for #515 - dependency graph issue

---

pythonforandroid/toolchain.py

Adds the hostpython's site-packages to PYTHONPATH when `call_hostpython_via_targetpython` is False - prevents issues with wrong ELF class when loading certain modules, e.g. _ctypes, which happens to me for every setuptools-based package.
Also allows a recipe to add extra command line arguments to calls to setup.py - needed for my cdecimal recipe to tell it to build in 32-bit mode.

pythonpath and setup.py build fixes

---

pythonforandroid/recipe.py
pythonforandroid/recipes/fontconfig/__init__.py
pythonforandroid/recipes/pygame_bootstrap_components/__init__.py
pythonforandroid/recipes/sdl/__init__.py
pythonforandroid/recipes/sdl2/__init__.py
pythonforandroid/recipes/sdl2_image/__init__.py
pythonforandroid/recipes/sdl2_mixer/__init__.py
pythonforandroid/recipes/sdl2_ttf/__init__.py
pythonforandroid/recipes/sdl2python3/__init__.py
pythonforandroid/toolchain.py

Basic NDKRecipe implementation which can build static libraries.

add NDKRecipe, rename old to BootstrapNDKRecipe

---

pythonforandroid/build.py
pythonforandroid/recipe.py

Prevents errors when rebuilding a dist and the packages already exist, and errors when building a dist with pure-Python modules which depend on recipe modules.

fix pymodules install

---

pythonforandroid/build.py
pythonforandroid/logger.py

Improve installed package detection:
Always use `site_packages_name` if possible, and replace `.` with `/` to handle namespaced packages (i.e. `zope.interface`).
Fix decode error on py2:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)`
Allow console width to be set via `COLUMNS` env var:
Avoids `invalid ioctl` errors and allows custom console width when running in a non-standard terminal (like PyCharm debugger).

Various fixes

---

pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/toolchain.py

Adds two additional locations to find recipes.
First, a local recipes folder is checked. This defaults to `./p4a-recipes`, and can be set via the command line option `--local-recipes`/`--local_recipes`.
Next, a user-local folder is checked in the user-local storage (i.e. ~/.local/share/python-for-android/recipes).
Finally, the standard p4a recipes will be checked.
Note that while this works on py2, it will need to be tested on 3.3/3.4 AND 3.5. 3.5 will use the newer `spec_from_file_location` and `module_from_spec` methods in `importlib.util`, while 3.3/3.4 will use the older (deprecated?) `SourceFileLoader`. py2 just uses the simple `imp.load_source`.

add custom recipe support [needs py3 testing]

---

pythonforandroid/archs.py

ccache is already used for building hostpython (if `/usr/lib/ccache` is added to the `PATH`), but not for any cross compiles.
This adds ccache to the `CC` and `CXX` env vars for standard and Cython builds, and sets `NDK_CCACHE` to the ccache binary for NDK builds. ccache usage is enabled by default, for convenience, but will respect the `USE_CCACHE` var (if set to `0`, ccache will not be used).
My distribution
- recipes: `hostpython2, jpeg, libffi, openssl, png, sdl2_image, sdl2_mixer, sdl2_ttf, python2, cdecimal, cnotify, eesentinel, enum34, evdev, ipaddress, pil, pyasn1, pycrypto, pytz, pyusb, sdl2, setuptools, six, zope_event, zope_interface, babel, gryphus, idna, pycparser, pyjnius, pyopenssl, sqlalchemy, twisted, zope_component, cffi, kivy, cryptography, aeris2`, which includes some …

use ccache for cross compilation

---

pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/android/_android.pyx
pythonforandroid/recipes/android/src/android/_android_billing_jni.c
pythonforandroid/recipes/android/src/android/_android_jni.c
pythonforandroid/recipes/android/src/android/activity.py
pythonforandroid/recipes/android/src/android/broadcast.py
pythonforandroid/recipes/android/src/android/runnable.py
pythonforandroid/recipes/android/src/setup.py

This allows the android package and recipe to be used with the SDL2 bootstrap. Some functionality is not available under SDL2, or is not needed as an alternative implementation is already in place.

update android package for sdl2 bootstrap

---

pythonforandroid/recipe.py

Otherwise if the dir has already been copied, the new copy will be nested.

remove build dir before copying for IncludedFilesBehaviour

---

pythonforandroid/recipe.py

For armeabi-v7a, p4a will look for a function named `prebuild_armeabi-v7a`, which is an invalid name. This PR will make it look for `prebuild_armeabi_v7a` instead.

fix prebuild for armeabi-v7a, make missing recipe error more informative

---

pythonforandroid/graph.py
pythonforandroid/recipe.py

Currently you can add pure-Python packages to the requirements on the command line, but if added to the depends in a recipe they will only work if there is a recipe for that package. This allows you to specify pure-Python packages which you need installed without creating recipes for them.

add python_depends to recipe

---

pythonforandroid/logger.py
pythonforandroid/util.py

Unicode errors happen randomly due to UTF8 output from cp (the quotes). This prevents those errors.

fix logger unicode errors on py2

---

pythonforandroid/build.py

This avoids pip trying to overwrite packages which were installed via recipes (and sometimes throwing an error due to the package already existing in the destination, depending on pip version). This does mean you must specify every dependency package.

ignore deps when installing via pip

---

pythonforandroid/toolchain.py

Prevents errors when running `p4a apk ...` including dist arguments, but no dist needs to be built.

always parse dist args

---

pythonforandroid/bootstraps/pygame/__init__.py

When i'm building a distribution with:
p4a create -v --dist_name test --bootstrap pygame --requirements=kivy==1.9.1 --android_api=19 --force-build
I can't get to the end because it breaks to the python distribute part:
```
[INFO]:    Copying python distribution
[INFO]:    running python.host -OO -m compileall /home/tito/.local/share/python-for-android/build/python-installs/test
[INFO]:    STDOUT:
Compiling /home/tito/.local/share/python-for-android/build/python-installs/test/lib/python2.7/json/tests/test_unicode.py ...
SyntaxError: ("(unicode error) \\N escapes not supported (can't load unicodedata module)", ('/home/tito/.local/share/python-for-android/build/python-installs/test/lib/python2.7/json/tests/test_unicode.py', 8, None, "u = u'\\N{GREEK SMALL LETTER ALPHA}\\N{GREEK CAPITAL …
```

Fix -m compileall

---

pythonforandroid/archs.py
pythonforandroid/build.py
pythonforandroid/patching.py

Automatically detect Crystax NDK and add libcrystax and its path to link flags. Stores the NDK being used ('google' or 'crystax') in Context for recipe usage.

support crystax ndk

---

pythonforandroid/recipes/android/src/android/_android.pyx

Use the print lines to debug. It seems that mActivity.getWindow()... changes rctx.top to a non-zero number, which causes the app to permanently shift upwards . To replicate this error, make an app that calls the keyboard. The hotfix I added was to set rctx.top to zero.

Fix keyboard height issue

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

Same behavior as the old toolchain, it allows to add other jar and other intent when building an application

sdl2/bootstrap: add --add-jar and --intent-filters support

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

This bring back the functionnality of onNewIntent/onActivityResult callback from Java activity to Python.
Since you cannot override dynamically the activity with pyjnius, the only way is to declare thoses function directly in the Activity, and provide a support from Python.
The android.activity module within the bind() function already provide this, but the java part could be used without android module at all.

sdl2/bootstrap: add support for onActivityResult and onNewIntent

---

pythonforandroid/archs.py
pythonforandroid/recipe.py

Allows a recipe to specify that CFLAGS should not be present in CC. Some packages will complain about this behavior (and they're technically right).

add option to not include cflags in cc

---

pythonforandroid/build.py
pythonforandroid/recipe.py

Allows versions and URLs for recipes to be specified via the environment variables `VERSION_recipename` and `URL_recipename`. Should be trivial to add requirements-style support (i.e. `recipename==1.2.3` in requirements).

add basic env-based overrides for recipe version and url

---

pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/cffi/disable-pkg-config.patch
pythonforandroid/recipes/cryptography/__init__.py
pythonforandroid/recipes/cryptography/fix-cffi-path.patch
pythonforandroid/recipes/cryptography/link-static.patch
pythonforandroid/recipes/idna/__init__.py
pythonforandroid/recipes/ipaddress/__init__.py
pythonforandroid/recipes/libffi/Application.mk
pythonforandroid/recipes/libffi/__init__.py
pythonforandroid/recipes/libffi/disable-mips-check.patch
pythonforandroid/recipes/libffi/remove-version-info.patch
pythonforandroid/recipes/openssl/__init__.py
pythonforandroid/recipes/openssl/disable-sover.patch
pythonforandroid/recipes/pycparser/__init__.py
pythonforandroid/recipes/pyopenssl/__init__.py
pythonforandroid/recipes/python2/Setup.local-ssl
pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/python2/patches/disable-openpty.patch
pythonforandroid/recipes/python2/patches/enable-ssl.patch

Compiles python2 with openssl support, and includes related recipes: cffi, cryptography, idna, ipaddress, libffi, pycparser

add openssl support

---

pythonforandroid/recipe.py

Fixes pathing in some places, adds some utility methods/properties, adds support for rebuilding when installing compiled components to hostpython, and fixes use of `find` to call cython (`find` will always have a return code of 0 if `find` itself worked - whether the `-exec` part worked or not is irrelevant, using `xargs` instead fixes this).

recipe and build improvements

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/jni/src/start.c
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonUtil.java
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/concurrency/PythonEvent.java
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/concurrency/PythonLock.java
pythonforandroid/bootstraps/sdl2/build/src/org/renpy/android/PythonService.java
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

Also adds a couple features (sdk selection, incomplete billing support, Java locks) and moves native lib loading to `org.kivy.android.PythonUtil`.

Enable services with SDL2 bootstrap

---

pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/toolchain.py
pythonforandroid/tools/liblink
pythonforandroid/tools/liblink.sh

Adds copy libs support back to revamp, similar to old toolchain. This copies libraries and shared objects to the APK rather than using biglink to add them to libpymodules.so, which is required for some use cases where C extension modules have naming conflicts.

add copy libs option

---

pythonforandroid/util.py

also fixes #573 but simpler solution

alternative version string to download from sourceforge;

---

pythonforandroid/recipe.py

Prevents issues with `-lSDL2` et al (at least with copy libs, I don't think it makes a difference for biglink).

fix library include path

---

pythonforandroid/archs.py
pythonforandroid/bootstrap.py
pythonforandroid/bootstraps/sdl2/__init__.py
pythonforandroid/bootstraps/sdl2/build/jni/src/Android.mk
pythonforandroid/build.py
pythonforandroid/recipes/cdecimal/__init__.py
pythonforandroid/recipes/cryptography/__init__.py
pythonforandroid/recipes/libffi/__init__.py
pythonforandroid/recipes/openssl/__init__.py
pythonforandroid/recipes/sdl2_image/__init__.py
pythonforandroid/recipes/sdl2_image/disable-assembler.patch
pythonforandroid/recipes/sdl2_image/extra-cflags.patch

Didn't work 100% for me, but it's a start. I had a weird issue with missing symbol `valloc` for libmysql.so, might just be a problem for that recipe though.
Also had to get rid of egg folders - for some reason bionic won't accept so paths longer than 128 characters in my arm64 builds, even though it never had an issue with the armeabi-v7a builds using the same paths.

add aarch64/arm64-v8a arch

---

pythonforandroid/toolchain.py

The latest master wasn't supporting == in requirements. This make it work with recent merge from @kived.
VERSION_kivy=master
or
--requirements=kivy==master

Parse and export in environ requirements version

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/org/libsdl/app/SDLActivity.java

As explained on #465, the previous approach (pure GL, or using window background) doesn't fully work.
This approach have a tiny delay until PythonActivity.onCreate is called.
It first display an ImageView fitted on the screen.
Once SDL is loaded (and that SDL put its own layout), we put again our ImageView.
The tricky part is when to remove.
On the previous python-for-android+kivy, kivy was explicitely saying that he's ready to receive event. And that's where we knew the loading screen could be removed.
Here, there is no absolute way to do it, as SDL itself on the java part doesn't provide any callback... except pollInputDevices()
This method is called each X seconds, to check if any joystick has been plugged or not.
The PR add a keepActive() method that is overrided in PythonActivity to …

SDL2: implement support for loadingscreen

---

pythonforandroid/bootstraps/sdl2/build/ant.properties
pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/custom_rules.tmpl.xml
pythonforandroid/toolchain.py

Allows for additional source directories which need to be compiled with the bootstrap sources. This is useful when the additional sources reference classes in the bootstrap source, or when you want to create a custom Activity class (by subclassing PythonActivity and setting the custom Activity as the entrypoint).

sdl2 bootstrap: implement --add-source argument

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/sdl2/build/templates/Service.tmpl.java

Adds back the ability to run services in the foreground when using the new segregated service pattern. `--service` arguments can now include options, in the format `servicename:path/to/service.py:option1:option2:option3:...`. The only option which does anything is `foreground`, any other option will be silently ignored.

add foreground option to segregated services

---

pythonforandroid/recipes/cryptography/__init__.py

It cause an error when using python3.

Remove print from cryptography recipe.

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonService.java

Stop the service process to free its memory when the Python interpreter has exited.

stop service on interpreter exit

---

pythonforandroid/recipes/ndghttpsclient

requests with ssl needs ngd.httpsclient. Unfortunately it when it is installed in the build environment with pip it grabs it's dependencies from pip which messes up the resulting APK. Thus this recipe is needed.

Add ndg.httpsclient recipe

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/sdl2/build/templates/Service.tmpl.java

Allows services to be started sticky (`sticky` option with `--service`, i.e. `--service=name:file.py:sticky`).
Adds option to restart services when they exit by calling `<ServiceObject>.setAutoRestartService(true)`. When the Python interpreter exits, it will be restarted automatically. This is done programmatically, rather than via a build option, so that a service can actually shut down if necessary (by setting auto-restart to false).
Fixes issue with the foreground option which caused it to be applied to all services, regardless of whether the option was actually specified.

add sticky services, auto-restart services, fix foreground option

---

pythonforandroid/build.py

I couldn't think of a neater way than just adding a direct check when the api is read.
Should fix https://github.com/kivy/python-for-android/issues/627

Added error when api and arch conflict

---

pythonforandroid/logger.py

Or else the simple example given in the quickstart guide would fail with the log
```
$ python-for-android create --dist_name=testproject --bootstrap=pygame \
--requirements=sdl,python2
... lots of correct output ...
[INFO]:    -> running make -j5
working: Objects/descrobject.c:359:5: warning: missing initializer for field ‘set’ of ‘PyGetSetDef {aka struct PyGetSetDef}’ [-Wmissing-field-initializers]                                                                                                        Traceback (most recent call last):
File "/home/me/.virtualenvs/sandbox/bin/python-for-android", line 9, in <module>
load_entry_point('python-for-android', 'console_scripts', 'python-for-android')()
File "/home/me/test/python-for-android/pythonforandroid/toolchain.py", line 708, in main …
```

Make unistr available in logger

---

distribute.sh

This is apparently the right fix for new pip versions, as applied in the new toolchain.

Removed --download-cache pip argument

---

pythonforandroid/recipes/boost/__init__.py
pythonforandroid/recipes/boost/user-config.jam
pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libtorrent/user-config-openssl.patch

Build libtorrent with --encryption=openssl

OpenSSL for LibTorrent optional dependency

---

pythonforandroid/recipes/cryptography/__init__.py
pythonforandroid/recipes/cryptography/link-static.patch

Needed for compatibility with new OpenSSL version.

update cryptography to 1.2.3

---

README.md

The output did not look good in rendered Markdown. An extra space was added before :  which one should not do in English spelling.

Fixed : alignment in instructions

---

pythonforandroid/bootstraps/pygame/__init__.py

Previously the bootstrap copied local.properties from the bootstrap dir, but this hardcoded a (potentially incorrect) SDK dir, per https://github.com/kivy/python-for-android/issues/684
This PR implements the same fix already used in the SDL2 bootstrap.
Fixes #684.

Fixed pygame bootstrap local.properties creation

---

setup.py

The EX color variants weren't added until 0.3.3. I found out because
Fedora 23 packages colorama 0.3.2, which satisfies the requirement, but
causes the error: `AttributeError: 'AnsiCodes' object has no attribute
'LIGHTBLUE_EX'`...

Bump colorama requirement to 0.3.3

---

pythonforandroid/archs.py
pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/toolchain.py

Adds a `--storage-dir` option to specify the path to where p4a should store its files.
Also checks if the default storage dir includes a space, and if so changes it to `~/.python-for-android`. Fixes #622

add --storage-dir option

---

pythonforandroid/recipes/boost/__init__.py

Recipe does not choke on arch v7a anymore.

boost recipe handle arch armeabi-v7a

---

pythonforandroid/recipes/pyleveldb/__init__.py

Without this the source files of snappy are not replaced but only removed.

Enable snappy recipe for py-leveldb

---

pythonforandroid/recipes/libtorrent/__init__.py

Verified patches to work.
Contains bugfix for Boost 1.60 python bindings.

update libtorrent to 1.0.9

---

pythonforandroid/recipes/ffmpeg/__init__.py
pythonforandroid/recipes/ffmpeg/settings.patch

Source: http://writingminds.github.io/ffmpeg-android/

added ffmpeg recipe

---

pythonforandroid/recipes/libtribler/__init__.py

Privacy with BitTorrent and resilient to shut down http://www.tribler.org
Recipe uses the latest development version from git.
Supersedes PR #405

add libtribler recipe

---

pythonforandroid/archs.py
pythonforandroid/build.py

Fix python_recipe.from_crystax

---

pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/sdl2/build/build.py

These cause the build to fail if main.py doesn't exist. I don't think there's any reason not to crash, as the app won't work without a main.py under any situation except the occasional debugging test that's easy to work around.
Resolves https://github.com/kivy/python-for-android/issues/656

Added main.py existence check in both bootstraps

---

pythonforandroid/toolchain.py

```
(venv) ryan@ryan-mk3:~/g/tmp$ p4a create --dist-name venvtest --requirements=kivy,alembic --debug --arch=armeabi-v7a
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (8, 14, 19, 21, 22, 23)
[INFO]:    Requested API target 21 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Crystax NDK 10.3.1
[INFO]:    Found virtualenv at /usr/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking …
```

throw error early if running in venv

---

pythonforandroid/recipes/libpq/__init__.py
pythonforandroid/recipes/psycopg2/__init__.py
pythonforandroid/recipes/storm/__init__.py

Port psycopg2 (such as it's dependency 'libpq') and storm recipes from the old toolchain to the revamp.

Port storm and psycopg2 recipes from the old toolchain to the revamp.

---

pythonforandroid/build.py

If the toolchain version isn't found, p4a currently crashes because it's
not defined rather than when this is checked for (and a more helpful
error returned).

Added toolchain_version initialisation

---

pythonforandroid/bootstraps/webview/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/templates/WebViewLoader.tmpl.java
pythonforandroid/toolchain.py
testapps/testapp_flask/main.py
testapps/testapp_flask/templates/index.html

Hi there,
here are some improvements to the webview bootstrap:
- load an url in the webview from python code
- as in #741 described, a second start of the app crashes. At the moment I kill the whole application to make sure the python thread stops. I don't know if this is the best approach but at least it is working.
- I implemented a handler for the back button to scroll through the browser history and finally close the app. Perhaps this should be made configurable to choose one of the options.
I am also currently trying to somehow get the back button event via a callback to the python program to handle it there. Do you have a suggestion how to do that? How do you do that in SDL2?

Webview improvements

---

pythonforandroid/toolchain.py

I'm not sure if this is a good idea, but can't hurt to ask and it would help with the regular problem of users not understanding error messages when modules aren't present (e.g. when buildozer hasn't installed them).
The code just checks if appropriate versions of each dependency are present, and prints clear errors if not. Currently if these are missing the user just gets an ImportError traceback.

Added python modules check

---

pythonforandroid/recipes/cymunk/__init__.py
pythonforandroid/recipes/kivent_core/__init__.py
pythonforandroid/recipes/kivent_cymunk/__init__.py
pythonforandroid/recipes/kivent_particles/__init__.py
pythonforandroid/recipes/kivent_polygen/__init__.py

Adds kivent_core, kivent_cymunk, kivent_particles, and kivent_polygen. Everything builds, but crashes on run - same bug as kivy/kivent#92.

add kivent recipes

---

pythonforandroid/bootstraps/pygame/build/jni/application/Android.mk
pythonforandroid/recipes/sdl/__init__.py

The jni code wasn't checking the correct python2 build dir, so it
couldn't find Python.h when python2 was built with optional
dependencies.

Fixed python2 with pygame bootstrap

---

pythonforandroid/bootstraps/pygame/build/build.py

If there's no `main.py/main.pyo` in the command, the script will exit. However, for launcher you _can't_ put any of that into the command and therefore with the current state will exit. This will let you go and launcher is built.

Enable launcher for pygame

---

doc/source/conf.py
doc/source/index.rst
doc/source/old_toolchain/faq.rst
doc/source/quickstart.rst
doc/source/related.rst
doc/source/troubleshooting.rst

~31 errors purged to 2:
```
p4a\doc\source\commands.rst:17: WARNING: autodoc: failed to import class u'ToolchainCL' from module u'toolchain'; the module executes module level statement and it might call sys.exit().
p4a\doc\source\recipes.rst:488: WARNING: autodoc: failed to import class u'Recipe' from module u'toolchain'; the module executes module level statement and it might call sys.exit().
```
Most of the errors came with `ext/sphinx_rtd_theme` because it used non-existing `math` extension. Then some broken links, underlines, missing `_static` etc.
I took out `ext/*` part of the docs out because it's just an example from sphinx and shouldn't be available in the final documentation. It isn't included in pdf or in the website, but if you build a local docs, then it'll be there.

Fix build errors in docs

---

doc/source/index.rst
doc/source/launcher.rst

ref https://github.com/kivy/kivy/issues/2706

Add docs for launcher

---

pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libtorrent/disable-so-version.patch
pythonforandroid/recipes/libtorrent/setup-lib-name.patch
pythonforandroid/recipes/libtorrent/use-soname-python.patch

rename native libtorrent.so to libtorrent_rasterbar.so
link python libtorrent.so to libtorrent_rasterbar.so

Workaround recursive link libtorrent.so

---

pythonforandroid/recipes/coverage/__init__.py
pythonforandroid/recipes/coverage/fallback-utf8.patch

The included patch is why I made this recipe. It is a fallback to utf-8 encoding because the locale module is not working on Android at the moment.

Coverage recipe

---

pythonforandroid/recipes/cryptography/__init__.py
pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libtorrent/user-config-openssl.patch
pythonforandroid/recipes/m2crypto/__init__.py
pythonforandroid/recipes/openssl/__init__.py
pythonforandroid/recipes/openssl/rename-shared-lib.patch
pythonforandroid/recipes/python2/Setup.local-ssl
pythonforandroid/recipes/python2/__init__.py

On Android versions lower than 6.0 the openssl library of the system is being loaded instead of the one provided with the app.
Adding the version to the name of the shared library file avoids the problem of the linker at runtime giving the wrong version of the library and provides a clear indication of what version you are using (good ensuring you use the latest version for security).

introduce versioning for openssl

---

pythonforandroid/recipes/netifaces/__init__.py

Returns netifaces to working state for python 2 (still a hardcoded path)

rewrite netifaces recipe

---

pythonforandroid/bootstraps/service_only/__init__.py
pythonforandroid/bootstraps/service_only/build/jni/src/start.c
pythonforandroid/bootstraps/service_only/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/service_only/build/templates/Service.tmpl.java
setup.py

* Add option to have a different icon for the python service.
* Bugfix bootstrap Gradle build script
* Binder interface
Because it will be shown in the notification bar in black and white you likely want to use a different icon than the colored app one, since Android forces that one to black and white otherwise (ugly).

Improve service_only bootstrap

---

pythonforandroid/bdistapk.py

First call to `setup.py apk` fails since the build dir would not have been previously created:
```
error: [Errno 2] No such file or directory: 'build/bdist.android-armeabi'
```

Check if bdist_dir exists before removing

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

Used to get a blank loading screen without this.

fix issue with loading_screen

---

pythonforandroid/recipes/libzmq/__init__.py

The latest android NDK (r12b) doesn't ship gcc 4.8 any more for cross compilation but switched to 4.9, and thus building the `libzmq` recipe fails: it cannot locate `libgnustd_shared.so`.
_(On a sidenote: I am facing a similar bug to #234 in `_clock.so`, but that shouldn't be related to my changes to the recipe.)_

libzmq recipe: do not hardcode g++ version

---

pythonforandroid/bootstrap.py
pythonforandroid/build.py
pythonforandroid/toolchain.py
test_builds/tests/test_apk.py

Not for merging yet.
This makes development that modifies the java source easier, by symlinking instead of copying during the build process, so that you can modify the source and deploy without any dist rebuild.

Added symlink_java_src dev option

---

pythonforandroid/bdistapk.py

Allows writing of a list of permissions, because the dictionary isn't capable of holding multiple values to a single key other way to me. (multiple `permission` will be rewritten).
```
'permissions': ['ACCESS_COARSE_LOCATION', 'ACCESS_FINE_LOCATION',
'BLUETOOTH', 'BODY_SENSORS', 'CAMERA', 'INTERNET',
'NFC', 'READ_EXTERNAL_STORAGE', 'RECORD_AUDIO',
'USE_FINGERPRINT', 'VIBRATE', 'WAKE_LOCK',
'WRITE_EXTERNAL_STORAGE']
```

Allow list of permissions for bdist

---

pythonforandroid/bootstraps/sdl2/build/jni/src/start.c
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/sdl2/build/templates/Service.tmpl.java

Fixes SDL2 services by setting the correct path to the app, which was broken following the recent move to the app subdir.
This is more hardcoded than I'd like, I'll try to check out if we can use the PythonActivity method instead (maybe it should be a class method) to avoid the same breaking problems in the future.

Fixed app path for SDL2 services

---

setup.py

**Note**: this does _not_ allow one to use the full Python for Android toolchain. It simply removes the requirement for the sh module on Windows so that it is pip installable.
This addresses #819. I am not sure if a warning about the limited abilities is required, but this does allow one to pip install or use setup.py install. When I run p4a (for the curious), I get:
```
C:\Users\ethanhs>p4a
ERROR: The sh Python module could not be found, please install version 1.10 or higher
python-for-android is exiting due to the errors above.
```
Something that I could modify for this PR is to change [`check_python_dependencies`](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/toolchain.py#L12) to not error on Windows, and instead add a message to wait for binary …

Allow installation on Windows

---

pythonforandroid/bdistapk.py

This allows `--launcher` switch to work with the setup.py thing for creating apps.

Fix bdistapk for launcher

---

pythonforandroid/recipes/zope_interface/__init__.py

zope_interface was not installing "common" hierarchy because it
couldn't find setuptools and was using distutils instead.
This commit fix this by using hostpython own build dir, and also
removed unused imports (shprint and join).

fixed recipe zope_interface

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

Easy way to set the presplash background color of Loading Screen.
--presplash-color=#AARRGGBB, --presplash-color=#RRGGBB or --presplash-color=red
Default color: #FFFFFFFF (white)
More information:
https://developer.android.com/reference/android/graphics/Color.html
Parse the color string, and return the corresponding color-int. If the string cannot be parsed, throws an IllegalArgumentException exception. Supported formats are: #RRGGBB #AARRGGBB or one of the following names: 'red', 'blue', 'green', 'black', 'white', 'gray', 'cyan', 'magenta', 'yellow', 'lightgray', 'darkgray', 'grey', 'lightgrey', 'darkgrey', 'aqua', 'fuchsia', 'lime', 'maroon', 'navy', 'olive', 'purple', 'silver', 'teal'.

Easy way to set the presplash background color

---

pythonforandroid/bootstraps/sdl2/build/build.py

Optional argument to set the loading screen background color
--presplash-color=#AARRGGBB, --presplash-color=#RRGGBB or --presplash-color=red
Default color: #FFFFFFFF (white)

Added argument to set the loading screen background color

---

pythonforandroid/recipe.py

This is the error message which appears without the change:
```
[INFO]:    # Downloading recipes
[INFO]:    Downloading qt5
[DEBUG]:   -> running mkdir -p /home/thopiekar/.local/share/python-for-android/packages/qt5
[INFO]:    -> directory context /home/thopiekar/.local/share/python-for-android/packages/qt5
[DEBUG]:   -> running basename http://download.qt.io/official_releases/qt/5.7/5.7.0/single/qt-everywhere-opensource-src-5.7.0.tar.gz
[DEBUG]:        qt-everywhere-opensource-src-5.7.0.tar.gz
[WARNING]: Should check headers here! Skipping for now.
Downloading qt5 from http://download.qt.io/official_releases/qt/5.7/5.7.0/single/qt-everywhere-opensource-src-5.7.0.tar.gz
[DEBUG]:   -> running rm -f .mark-qt-everywhere-opensource-src-5.7.0.tar.gz
[INFO]:    Downloading qt5 from …
```

Completing md5sum comparison and download

---

pythonforandroid/recipes/boost/__init__.py

The ``ndk-dir`` argument of the ``make-standalone-toolchain.sh`` script is no longer supported and appears unnecessary because the script is located within the ndk-dir.

Make boost recipe compatible with Google NDK 13.0

---

pythonforandroid/recipes/android/src/android/_android.pyx

Remove SDL2 presplash function in `android` package.
ref #928

Add remove_presplash

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

Makes the SDL2 bootstrap compile all .py to .pyo files automatically, like the pygame bootstrap. This reduces APK size and speeds up execution. It only affects python2 builds for now.
I also added a `--no-compile-pyo` option to disable this behaviour.

Compile pyo with sdl2

---

pythonforandroid/recipe.py

Made the sdl2 bootstrap strip unneeded symbols with python3

---

pythonforandroid/bootstraps/sdl2/build/src/org/libsdl/app/SDLActivity.java

Added `System.exit(0); ` in  _SDLActivite.java_ _onDestroy()_ class to fix this issue kivy/kivy#4264, but I still think that is not right way and need to find more 'Android' method.

Complete closure of the application with SDL2.

---

pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

According to https://developer.android.com/guide/topics/manifest/activity-element.html#config -> orientation:
If your application targets API level 13 or higher (as declared by the minSdkVersion and targetSdkVersion attributes), then you should also declare the "screenSize" configuration, because it also changes when a device switches between portrait and landscape orientations.
If ``screenSize`` not given app freezes on orientation change.

Add ``screenSize`` to android:configChanges in AndroidManifest.xml if API >= 13

---

pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/webview/build/build.py

Usage results:
* single value
['param']
* two or more values
['param1', 'param2']
* two or more `--permission` args with at least one value each
[['param1', 'param2'], ['param3', 'param4']]
which is later flattened.
Closes #673

Switch --permission to accept >=1 parameters

---

pythonforandroid/recipes/protobuf_cpp/__init__.py

Protobuf with c++ implementation is much faster than native-python (10-60 times). Here is a recipe for building protobuf c++ extension. So **instead** of adding `protobuf` requirement, add `protobuf_cpp` one.
To ensure that you are using cpp implementation you can add folowing before importing protobuf:
```
import os
os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'cpp'
```
It will raise exception if cpp implementation is not available.

Add recipe for google protobuf cpp implementation

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/org/libsdl/app/SDLActivity.java

Right now the loading screen does not show up until loading is actually pretty much complete because all the loading tasks block the UI thread. As a result, you will see a dark grey gradient background instead of the loading screen. For apps with more data to unpack, this can appear for longer and give the impression the app has hung. This is a fix for Issue #983.

Move the unpackFiles step into an AsyncTask

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonUtil.java
pythonforandroid/recipe.py
pythonforandroid/recipes/python3crystax/__init__.py

~~Not for merging yet.~~
This PR removes some final references to python3.5 to make everything generic, so that python3.6 can be used by adding `python3crystax=3.6` in the requirements (the default remains 3.5 for now).
This won't actually do anything yet as CrystaX doesn't come with a prebuilt Python 3.6, but I've got this working as well. I'll add support for downloading a prebuilt one that I've generated, or for building a new one locally, shortly.

Added support for Python 3.6

---

pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/service_only/build/build.py
pythonforandroid/bootstraps/webview/build/build.py

Fix packaging failure when user has large UID by using GNU format over USTAR format

---

pythonforandroid/recipes/protobuf_cpp/__init__.py

Android application crashes without STL shared library, so we need copy STL library for protobuff cpp.

Fixed protobuf cpp

---

pythonforandroid/build.py
pythonforandroid/recipes/dateutil/__init__.py
pythonforandroid/recipes/icu/__init__.py
pythonforandroid/toolchain.py

New dateutil recipe and updated icu recipe.
Small addition to build process:
- build status threw an exception if no bootstrap was
available e.g. after clean_bootstrap_builds
- remove duplicates in list of python packages to install

Recipe updates and small fixes to build process

---

pythonforandroid/build.py

avdmanager replaces the older android tool. This replaces the previous PR at https://github.com/kivy/python-for-android/pull/1051 which checked for the availability of the executables in the wrong order.

Call avdmanager instead of android in the SDK

---

pythonforandroid/toolchain.py

Fixes https://github.com/kivy/python-for-android/issues/1058

Added command handling if p4a is run with no arguments

---

pythonforandroid/recipes/kivy/__init__.py

Currently the Kivy examples are included automatically under python3, due to a difference in where setuptools installs them. They add about 9MB to the APK size, and are definitely undesirable.

Delete the kivy-examples dir from the dist under python3

---

pythonforandroid/recipes/ethash/__init__.py
pythonforandroid/recipes/libsecp256k1/__init__.py
pythonforandroid/recipes/pycryptodome/__init__.py
pythonforandroid/recipes/pyethereum/__init__.py
pythonforandroid/recipes/pysha3/__init__.py
pythonforandroid/recipes/scrypt/__init__.py
pythonforandroid/recipes/scrypt/remove_librt.patch
pythonforandroid/recipes/secp256k1/__init__.py
pythonforandroid/recipes/secp256k1/cross_compile.patch
pythonforandroid/recipes/secp256k1/drop_setup_requires.patch
pythonforandroid/recipes/secp256k1/find_lib.patch
pythonforandroid/recipes/secp256k1/pkg-config.patch

* ethash
* libsecp256k1
* pycryptodome
* pyethereum
* pysha3
* scrypt
* secp256k1
See https://github.com/ethereum

Ethereum related recipes

---

pythonforandroid/bootstrap.py
pythonforandroid/graph.py

This PR rewrites most of the recipe graph calculation, because the old version was extremely hacky and I couldn't actually work out how to fix it. The new version is much simpler but seems to give either the same or better results.
Fixes https://github.com/kivy/python-for-android/issues/826 and https://github.com/kivy/python-for-android/issues/1056 (and probably others).
~~Not for merging quite yet.~~ Seems to work.

Rewrite recipe graph

---

pythonforandroid/recipes/kivy/__init__.py

Instead of removing it manually we should use the [`KIVY_SPLIT_EXAMPLES` flag](https://github.com/kivy/kivy/blob/master/setup.py#L1022) set for it and prevent failing the build maybe if `rmtree` would be able to do the task.
ref #1062

Use Kivy setup.py flag instead of rmtree

---

pythonforandroid/recipes/websocket-client/__init__.py
pythonforandroid/recipes/websocket-client/websocket.patch

you may need to copy patched library into your source tree

Recipe for websocket-client

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

resolves #1061. 
Not sure if this is the best implementation, but seems to work based on my limited testing.

implement wakelock for sdl2

---

pythonforandroid/logger.py

This prevents a regular error in the python2 build where the output is in byte format but is not valid utf-8, so the logger crashes in python3 because the output is assumed to be a str.

Made logger convert output to utf-8 including errors

---

pythonforandroid/graph.py
pythonforandroid/toolchain.py

Python dependencies were being ignored by the graph builder, which broke the flask recipe (and possibly others).

Made graph recognise python_depends

---

pythonforandroid/bootstraps/pygame/build/src/org/renpy/android/SDLSurfaceView.java
pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/service_only/build/templates/Service.tmpl.java
pythonforandroid/bootstraps/webview/build/src/org/kivy/android/PythonActivity.java
pythonforandroid/recipes/python2/patches/custom-loader.patch

new env var ANDROID_UNPACK to target a folder `/data/data/<app>/files` and for sdl2 that + `/app` to get libpymodules.so

Fix python2 for webview

---

pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonUtil.java

This PR rebases and restructures https://github.com/kivy/python-for-android/pull/903.
I've tested this only in the emulator, but I was able to reproduce the original issue, and this rebased PR seems to fix everything.
Fixes #866.

Fixed ssl, sqlite and crystax library loads on Android versions before ~4.4

---

pythonforandroid/bootstraps/sdl2/build/build.py

This is kind of messy, but there doesn't seem to be a very neat way to do it.
The point of doing this is that the compileall can fail for some files if it tries to load .so files (which hostpython doesn't have available). In particular, this occurs for files which try to access unicode characters with `'\N{...}'`. For instance, several files in sympy do this, and currently crash when sympy is imported on the device. This PR would make the compilation work in such cases.
For now, I think discussion would be better than straight merging, but having the change documented could help someone.

Try system python when performing compileall

---

pythonforandroid/bootstraps/sdl2/build/jni/src/start.c

Fixes https://github.com/kivy/python-for-android/issues/980.

Made start.c search ANDROID_UNPACK for crystax

---

pythonforandroid/recipes/twisted/__init__.py

Had to update Twisted to the latest version as addTimeout to a deferred is not available in V16.0.
Could we develop a more aggressive recipe upgrades policy so we don't fall behind Linux so much?
Thanks, Enoch.

This current Twisted version actually runs!

---

pythonforandroid/recipes/numpy/__init__.py

The pypi python server return : error 403 : SSL is required. So build failed with an empty archive that can t be extracted.

The pypi python return http 403 error on http

---

doc/source/quickstart.rst

Not sure about the markdown formatting, but it seems like  NDK's past r10e are all 64-bit only. Trying to use them on a 32-bit linux gives a "c compiler cannot produce executables" error

Add note about NDK version on 32-bit OS

---

pythonforandroid/recipe.py

It looks like it was dropped long time ago.

Remove unused `extract_source()` method

---

pythonforandroid/recipes/libiconv/__init__.py
pythonforandroid/recipes/libiconv/libiconv-1.15-no-gets.patch
pythonforandroid/recipes/libzbar/__init__.py
pythonforandroid/recipes/libzbar/werror.patch
pythonforandroid/recipes/zbar/__init__.py
pythonforandroid/recipes/zbar/zbar-0.10-python-crash.patch

- zbar Python extension
- zbar library
- iconv library

Adds zbar (and dependencies) support, refs #854

---

pythonforandroid/recipes/openssl/__init__.py

The '-j5' option causes the openssl build to fail with NDK 16, at least for me. I'm not sure if this means the build order is technically still improperly specified, but since it works it's probably a fine fix for now.

Removed '-j5' from openssl make

---

pythonforandroid/build.py

This seems to be necessary for building the webview bootstrap with the latest NDK, although I'm not sure why. Still looking into it.

Add the ndk platform libs dir during biglink

---

pythonforandroid/recipes/audiostream/__init__.py

I managed to get audiostream compiled and working using sdl2 on android.
I had to change the setup.py for audiostream, but I need help making my edits be system-independent, and how to make it able to use sdl OR sdl2....
My modified setup.py is over at: https://github.com/snuq/audiostream/blob/master/setup.py
Mostly i changed instances of 'SDL' into 'SDL2', and included '/home/kivy/.buildozer/android/platform/android-ndk-r9c/sources/android/support/include'

Update __init__.py to support SDL2

---

pythonforandroid/bootstraps/sdl2/build/templates/build.tmpl.gradle

This seems to fix the error message about needing `-source 7`.

Made sdl2 build.gradle work with Java 7

---

setup.py

fixes missing `assets` and `drawable` folder, `gladlew` executable.

setup.py: fix installation

---

pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/pygame/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

This allows users to add their own activities to the manifest file. This can be used to start Java activities using pyjnius, e.g.:
```python
PythonActivity = autoclass('org.kivy.android.PythonActivity')
SimpleScannerActivity = autoclass("org.electrum.qr.SimpleScannerActivity")
Intent = autoclass('android.content.Intent')
intent = Intent(PythonActivity.mActivity, SimpleScannerActivity)
activity.bind(on_activity_result=on_qr_result)
PythonActivity.mActivity.startActivityForResult(intent, 0)
```
This will be used in Electrum to scan QR codes using an embedded copy of zxing for Android.

Allow adding activities to the manifest

---

pythonforandroid/recipes/numpy/__init__.py

Fix for #1141 , tested in 2.7 only, not sure if will work with py3 crystax, however it's copied from recipe built for crystax, so there is chance.

fix for #1141 - added ldflags to numpy

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/build.tmpl.gradle

Jars from `android.add_jar` were copied to a directory but never referenced in the gradle build script.
Closes: #1208

Include jar files in build.gradle

---

pythonforandroid/recipes/setuptools/__init__.py

Adds python3crystax support to setuptools recipe.
Also removed unused imports.
Before the fix, running `buildozer android debug` was resulting the following:
```
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting.
```
Test program:
```
from kivy.app import App
from kivy.uix.label import Label
import pkg_resources
class MyApp(App):
def build(self):
version = pkg_resources.get_distribution("setuptools").version
return Label(text="version: " + version)
if __name__ == '__main__':
MyApp().run()
```
Side note, this is a simple fix to merge, but it actually …

Setuptools for Python3 (Crystax)

---

pythonforandroid/recipes/gevent/__init__.py
pythonforandroid/recipes/gevent/gevent.patch

Makes sure the arm cross linker is being used for LDSHARED.
Fixes configure script complaining about CFLAGS and LDFLAGS and
simplified `gevent.patch` (less is more), since flags are now
sanitized during `get_recipe_env()` call.
Also depends on #1249 (symlink system Python to hostpython3crystax).

Gevent Crystax/Python3 support

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

As in title, this allows setting the [activity launch mode](https://developer.android.com/guide/topics/manifest/activity-element.html#lmode) in the AndroidManifest from buildozer.spec.
It is cumbersome to manually (or via custom scripts) modify the manifest at `[app project]/.buildozer/android/platform/python-for-android/dist/[app]/templates/AndroidManifest.tmpl.xml`.
related: https://github.com/kivy/buildozer/pull/650

allow setting launchMode for the main activity in the manifest

---

.travis.yml
Dockerfile
README.rst

This is a first step to python-for-android continuous integration.
It currently only verifies that p4a creates an APK by cross compiling
a limited set of recipes.
How it works; On git push Travis "executes" `.travis.yml` instructions:
1. the `before_install` section runs `docker build` to prepare the environment
2. the `script` section is the actual test, building the APK with `docker run`
3. based the exit status Travis build will be green or red
For example editing `pythonforandroid/recipes/hostpython2/__init__.py` and
introducing an error e.g. replace `-j5` with `--wrong-flag` would make it fail.
Things to improve:
- improve `.travis.yml` readability
- test more recipes
- bring Python3 and Crystax support
- speed up build/run by caching downloads
- and much more

Continuous integration with Travis and Docker, fixes #625

---

pythonforandroid/bootstraps/sdl2/build/build.py

This addresses issue  #1257 reported for version 0.6.0. when building for sdl2 bootstrap.

Added 2 tests to ensure directories exist.

---

pythonforandroid/archs.py
pythonforandroid/build.py
pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/numpy/patches/ar.patch

different architectures have different include location, this PR allows to specify different include directory per architecture, so python x86 can be built.
numpy now uses the AR binary corresponding to architecture.

compile numpy for x86

---

pythonforandroid/recipe.py

First tries to return local recipe path or defaults to core one.

get_recipe_dir() also handle local recipes, fixes #1185

---

.travis.yml

Has the following requirements:
sdl2,pyjnius,kivy,python2
refs #1263

Build `testapp_python2` using `setup_testapp_python2.py`

---

.travis.yml
pythonforandroid/recipes/babel/__init__.py
pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/dateutil/__init__.py
pythonforandroid/recipes/idna/__init__.py
pythonforandroid/recipes/ipaddress/__init__.py
pythonforandroid/recipes/jpeg/__init__.py
pythonforandroid/recipes/libmysqlclient/__init__.py
pythonforandroid/recipes/mysqldb/__init__.py
pythonforandroid/recipes/pil/__init__.py
pythonforandroid/recipes/png/__init__.py
pythonforandroid/recipes/pycparser/__init__.py
pythonforandroid/recipes/pymunk/__init__.py
pythonforandroid/recipes/pytz/__init__.py
tox.ini

Makes sure lint checks are ran before `docker build` so we fail fast.
Currently `flake8` errors are ignored except for `E101` and `W191`.
This will demonstrate the fail fast case.
Next commit will fix these two errors in the code base.

Introduces linting (tox/flake8)

---

pythonforandroid/recipes/enum34/__init__.py
pythonforandroid/recipes/ipaddress/__init__.py
pythonforandroid/recipes/pyasn1/__init__.py
pythonforandroid/recipes/pyopenssl/__init__.py
pythonforandroid/recipes/zope_interface/__init__.py

Fix Twisted and Cryptography to not conflict with python3crystax
Note: Cryptography still does not successfully build, but at least it no longer complains about a conflict. https://paste.ubuntu.com/p/nMxXnP7tzH/

Fix twisted and cryptography build for python 3

---

pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/decorator/__init__.py
pythonforandroid/recipes/idna/__init__.py
pythonforandroid/recipes/pycryptodome/__init__.py
pythonforandroid/recipes/pysha3/__init__.py
pythonforandroid/recipes/pyyaml/__init__.py
pythonforandroid/recipes/requests/__init__.py
pythonforandroid/recipes/scrypt/__init__.py
pythonforandroid/recipes/scrypt/remove_librt.patch
pythonforandroid/recipes/secp256k1/__init__.py

Adds CrystaX/Python3 support to 9 recipes:
- cffi: fixes build in both Python2 and Python3
- decorator: updates version and adds python3crystax support
- idna: updates version
- pycryptodome: fixes version string & adds python3crystax support
- python3crystax: adds python3crystax support
- pyyaml: updates version & drops host python via target python
- requests: adds python3crystax support
- scrypt: fixes version & adds python3crystax support
- secp256k1: adds python3crystax support
These recipes were tested with CrystaX/Python3 in
https://github.com/AndreMiras/EtherollApp
See last `buildozer android debug` build success:
https://travis-ci.org/AndreMiras/EtherollApp/jobs/386381704

Recipes updates with CrystaX/Python3 support

---

pythonforandroid/recipes/python2/patches/ctypes-find-library-updated.patch

Fixes `find_library()` `OSError`/`FileNotFoundError` exception when app
deployed external SD storage.
Apps deployed on external SD storage have different root prefix.
External SD storage apps root dir prefix is like:
```
/mnt/expand/<sd-card-id>/user/0/<package.domain>.<package.name>/files/app
```
While internal storage apps root dir prefix is:
```
/data/data/<package.domain>.<package.name>/files/app
```
Hence the `[0:4]` trick doesn't work.

fixes find_library when deployed external storage

---

.travis.yml

I haven't added the tests for Python3 Crystax since `numpy` recipe first needs to be ported/fixed for it.
Edit: build green in my fork https://travis-ci.org/AndreMiras/python-for-android/jobs/396144141

Adds numpy/python2 to continuous integration, refs #1263

---

pythonforandroid/recipe.py
pythonforandroid/recipes/cryptography/__init__.py
pythonforandroid/recipes/m2crypto/__init__.py
pythonforandroid/recipes/pyleveldb/__init__.py

Fixes the right include and link paths for python2's recipes when variable "call_hostpython_via_targetpython" set to False. This will fix issues #668 and #669 with the new python2's (Python 2.7.11) but should work with the old python2's recipe. Thanks to @brussee who pointed this in PR #778.
PD: Buuuuf, The last PR #792 was wrong... I cloned from the wrong branch...sorry, those days I'm a little tired cause of my job and I make silly mistakes...

Fixes the include and link paths for python2

---

pythonforandroid/recipes/kivy/__init__.py

Kivy 1.10.1 was released recently. This minor change makes sure p4a picks up the latest stable kivy version by default.
Fixes #1328 and may also fix #1219 and https://github.com/kivy/buildozer/issues/697

Defaults to latest kivy==1.10.1 release, fixes #1328

---

pythonforandroid/bootstraps/sdl2/build/build.py

ignores .DS_Store files while comparing build-tools versions

Fix for Mac OS version bug

---

pythonforandroid/recipes/android/src/android/__init__.py

It would be better to add explicit imports, but fixing the tests is fine for now. The android module is mostly legacy stuff that would be better restructured entirely if it were actively developed.

Added code style exception for android module * import

---

pythonforandroid/recipes/Pillow/__init__.py
pythonforandroid/recipes/Pillow/patches/fix-docstring.patch
pythonforandroid/recipes/Pillow/patches/fix-setup.patch
pythonforandroid/recipes/setuptools/__init__.py

This patch adds a new recipe for Pillow. There already is a recipe for PIL, but PIL does not support python3.
This new recipe should work with `python3crystax` as well as with `python2`. However, with `python2`, there are the following issues:
- The existing recipe for `setuptools` provides an older version of `setuptools`, which is too old for Pillow. This can be circumvented by specifying `setuptools==40.0.0` when building an APK. I am not sure if it is possible to specify a minimum version for dependencies inside recipes.
- There seems to be an issue with the `jpeg` recipe which requires `libcutils`. I resolved it locally by removing `libcutils` from  `pythonforandroid/recipes/jpeg/build-static.patch`.
With `python3crystax`, there should be no issues.
This PR addresses #1114 and #1326.

Add Pillow Recipe

---

pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/numpy/patches/ar.patch
pythonforandroid/recipes/numpy/patches/fix-numpy.patch
pythonforandroid/recipes/numpy/patches/lib.patch
pythonforandroid/recipes/numpy/patches/prevent_libs_check.patch
pythonforandroid/recipes/numpy/patches/python2-fixes.patch

This PR extends the existing numpy recipe to also support
python3crystax. Additionally, the existing recipe code is cleaned up a
bit and numpy is upgraded to version 1.15.1.
The existing patches were ported to the new numpy version.
To get numpy 1.15.1 working with python 2.7, an additional patch
was necessary.
This PR should resolve #882.

Extend numpy recipe to support python3

---

pythonforandroid/recipes/hostpython2/__init__.py
pythonforandroid/recipes/hostpython2/fix-segfault-pygchead.patch

This is a fixes for #1297 - on some platform, Python < 2.7.15 crashes due to a bug highlighted only with recent compilers.
This one liner came from https://github.com/python/cpython/commit/e348c8d154cf6342c79d627ebfe89dfe9de23817#diff-fb41bdaf12f733cf6ab8a82677d03adc that contains a extensive explaination about it. It could be done on Python 2 for ARM, but the bug isn't triggered at the moment.
I compiled a fresh app with this patch, it doesn't segfault during the compilation of hostpython2, and the app on Android runs.
(I talked about moving to Python 2.7.15, but it would take more time that just accepting this patch, as we would need to update hostpython2 and python2 recipes, and all cross compilation patches. Plus more testing as ssl module changed somewhere, unsure if we don't need …

Fix segfault on hostpython2 when compiling for x86_64

---

pythonforandroid/recipes/libogg/__init__.py
pythonforandroid/recipes/libvorbis/__init__.py
pythonforandroid/recipes/openal/__init__.py
pythonforandroid/recipes/pyogg/__init__.py
pythonforandroid/recipes/pyogg/patches/fix-find-lib.patch
pythonforandroid/recipes/pyopenal/__init__.py
pythonforandroid/recipes/pyopenal/patches/fix-find-lib.patch

This PR adds recipes for PyOpenAL, OpenAL Soft, PyOgg, libvorbis, and libogg.
Note: A working numpy recipe is needed. So for testing with python3, you also need to pull in #1343.

Add recipes for OpenAL support

---

pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/cffi/disable-pkg-config.patch

This patch fixes the cffi build failing because "ffi.h" cannot be found
in the expected path on some host systems (e.g. gentoo).
This resolves #1148.

Fix cffi build failing on some hosts

---

doc/source/services.rst

It makes it easier to understand by using the initial example with
`myservice` as service name.

Fixes example service name example consistency

---

pythonforandroid/archs.py

As proposed in #1360 this change fixes `env["LDSHARED"]` not being set which can confuse distutils / `python setup.py build_ext` to use the incorrect host compiler, and it adds the `-I` folder to the python3 crystax sources when using python 3 crystax. This should allow a lot of recipes to be cleaned up later which currently have the same repeated hacks to work around this. (Uncleaned recipes should just duplicate include paths which should do no harm, so this shouldn't require any recipes to be changed to be safely merged)
**Testing state**:
- tested with python3crystax *without kivy* (but with `Pillow` recipe)
- **not tested** with python 2
- **not tested** with other recipes

Fix LDSHARED and missing CFLAGS include path for python3crystax sources

---

.github/ISSUE_TEMPLATE.md

The same way we did on buildozer project (https://github.com/kivy/buildozer/pull/688).
See what it looks like on my fork:
https://github.com/AndreMiras/python-for-android/issues/new

Adds issue template with basic required info

---

pythonforandroid/bootstraps/pygame/build/src/org/renpy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/org/kivy/android/PythonActivity.java

In https://github.com/kivy/python-for-android/pull/609 `PYTHON_NAME` was
being used while potentially null (in the case of basic service folder
method), leading to segfault on `setenv()` call.

Sets default service pythonName, fixes #1049

---

doc/source/services.rst
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonService.java

1) Fixes services auto-restart introduced in #643:
`onTaskRemoved()` stops the service gracefully using `stopSelf()` when
it gets killed. That way `onDestroy()` gets triggered and service will
restart under different process if auto-restart is enabled.
2) Documents process behavior and auto-restart usage:
Emphasis that services are running in a dedicated processes, different
from the app process, which is not the Android default behavior.
Adds a code snippet.

Fixes and clarifies services auto-restart

---

Dockerfile
pythonforandroid/recipes/python3crystax/__init__.py

Stay up to date with latest Ubuntu LTS.

Update Docker base image Ubuntu Bionic 18.04

---

pythonforandroid/recipes/groestlcoin_hash/__init__.py

Adds a recipe for groestlcoin_hash, a hash algorithm used by the Groestlcoin cryptocurrency.
This PR depends on #1217 because as with any electrum fork, the app using this recipe uses this patched p4a to allow using ssl with python3crystax, so this recipe wasn't tested on p4a master.
The overriden `get_recipe_env` could maybe be removed and the change it does be backported to the `CythonRecipe.get_recipe_env` method, at the same place `-lpython{}m' is added, so other recipes could benefit from it. I don't know if it could potentially lead to issues with others though, so that's an open question for me.

Groestlcoin hash

---

pythonforandroid/recipes/preppy/__init__.py
pythonforandroid/recipes/pyrxp/__init__.py
pythonforandroid/recipes/reportlab/__init__.py

Follow up for https://github.com/kivy/python-for-android/pull/1182
Squashed commit and also removed `pil` from the requirements list of the initial PR.
Edit:
Not tested, but well relatively safe change. In the worst case we have compilation error on Python3, but no regressions on Python2.

Adds Python3 support to reportlab, pyrxp and preppy

---

.travis.yml
tests/test_graph.py
tox.ini

Unit tests should be also ran in Continous Integration for both Python2
and Python3.
Also fixes `invalid_combinations` list as `python3` recipe was removed
in a19e884.

Enables unit tests in tox

---

pythonforandroid/recipes/reportlab/__init__.py
tests/recipes/test_reportlab.py
tox.ini

- fixes `TypeError` on host Python3
- adds recipe unit test
- makes it possible to override `pytest` args via `tox`

ReportLabRecipe fixes and unit tests, fixes #1380

---

pythonforandroid/bdistapk.py
pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/pygame/build/buildlib/argparse.py
pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/service_only/build/build.py
pythonforandroid/bootstraps/webview/build/build.py
pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/recipes/Pillow/__init__.py
pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/android/broadcast.py
pythonforandroid/recipes/hostpython2/__init__.py
pythonforandroid/recipes/ifaddrs/__init__.py
pythonforandroid/recipes/libglob/__init__.py
pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libvorbis/__init__.py
pythonforandroid/recipes/opencv/__init__.py
pythonforandroid/recipes/protobuf_cpp/__init__.py
pythonforandroid/recipes/vlc/__init__.py
pythonforandroid/toolchain.py
tox.ini

- E114 indentation is not a multiple of four (comment)
- E127 continuation line over-indented for visual indent
- E128 continuation line under-indented for visual indent
- E129 visually indented line with same indent as next logical line

Linter fixes E114, E127, E128, E129

---

pythonforandroid/recipes/jpeg/__init__.py

This way download can work when non HTTP ports are blocked.

jpeg: use https: URL instead of git:

---

pythonforandroid/recipes/twisted/__init__.py
pythonforandroid/recipes/twisted/incremental.patch

incremental is only used to get version, and it causes trouble during
installation as hostpython can't retrieve a https URL because it's
compiled without SSL support.
Also disabled install_in_hostpython which is not needed here.

twisted: added a patch to disable incremental during setup [pyconfr18]

---

pythonforandroid/recipes/cryptography/__init__.py

an include has been mistakenly removed in
cbe9e8e019196c65d563c85052df8722847f0217 resulting in compilation error
(a header can't be found). This patch fixes this.

cryptography: add missing include flag [pyconfr18]

---

pythonforandroid/toolchain.py

Although there are many changes here, they are all cosmetic and should not affect any behavior. I know it's not painful to make large and sweeping changes unnecessarily, but I think these are important for readability + pep8 compliance.
The types of changes and rationale are outlines below:
- Replace '''doc''' with """doc""" -> Pep8 specifies double quotes for doc strings
- Enforced 80 col line with -> Pep 8
- Removed unused import (imp) -> Redundant
- Removed assignment to unused variables -> Redundant
- Made argument passing indentation consistent
- Removed brackets around simple strings -> Redundant
- Made _read_configuration a static method as it does not use self -> good pratice? Or not?
- Replace using "args" parameter with "_args" -> Convention to indicate non-usage

Doc and cosmetics

---

.travis.yml
ci/rebuild_updated_recipes.py
pythonforandroid/recipes/babel/__init__.py
pythonforandroid/recipes/cffi/__init__.py
setup.py
tox.ini

This is a first iteration addressing recipes conditional build.
In this version all modified recipes are build in batch with no
dependency resolution whatsoever.
Also recipes are only built against `python3crystax` target and
`sdl2` bootstrap.
The list of broken recipes is not fully known, but this script will help
finding out. If a recipe is known to be broken, it should be added in
the `BROKEN_RECIPES` set to be skipped until it gets fixed.

Conditional recipe build fixes #1382

---

setup.py

Module `enum34` should only be installed on Python < 3.4
Fixes host Python3 regression from ecd0bf6, the error was:
```
AttributeError: module 'enum' has no attribute 'IntFlag'
```

Fixes Python3.6 and enum34

---

ci/constants.py
ci/rebuild_updated_recipes.py

Populated the list of broken recipes and moved to a dedicated
`constants.py` file.
Broken recipes are mostly divided in 3 categories:
1) recipes not yet migrated from python2 to python3crystax
2) recipes that don't have environment var well setup
3) recipes that are not broken but require a system package

List of broken recipes for python3crystax, refs #1402

---

setup.py

This is currently making buildozer fail because it tries to parse the line with a regex.

Put install_reqs on line so that buildozer's rubbish parsing will work

---

pythonforandroid/recipes/pyjnius/genericndkbuild_jnienv_getter.patch
pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

Broken due to edits in https://github.com/kivy/pyjnius/pull/356

Fix pyjnius setup.py patches

---

setup.py

Relies on PEP 508 to set conditional requirements in one statement.
Fixes buildozer p4a requirements install.

Installs requirements in a single statement

---

doc/source/services.rst

Adds explanation and sample code on how to extract the service argument from within the service.

doc: add instructions on accessing service argument

---

pythonforandroid/recipes/pyjnius/__init__.py

Fixes patch failing with:
```
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
```
refs #1414, #1416, #1417

Pins pyjnius==1.1.2

---

pythonforandroid/recipes/pyjnius/__init__.py

Just like we pinned `pyjnius==1.1.2` on `stable` branch in https://github.com/kivy/python-for-android/pull/1426 we're now pinning `pyjnius==1.1.3` on `master`.

Pins pyjnius==1.1.3, fixes #1416

---

pythonforandroid/bootstraps/pygame/build/blacklist.txt
pythonforandroid/bootstraps/sdl2/build/blacklist.txt
pythonforandroid/bootstraps/service_only/build/blacklist.txt
pythonforandroid/bootstraps/webview/build/blacklist.txt

mmap was blacklisted, but it is actually useful, e.g. to communicate
between a frontend and a service.
This patch remove it from blacklists.

removed mmap from blacklist

---

.dockerignore
Dockerfile

Subsequent p4a command will run as unprivileged user.
This makes the setup more realistic/closer to an actual setup.
Also added .dockerignore so container and host generated files don't conflict.

Creates non root user in Dockerfile

---

pythonforandroid/recipes/lxml/__init__.py

This pull request removes the python 2-specific hacks from the `lxml`-recipe that break Python 3 support. **I expect that this possibly will break the Python 2 lxml recipe build.** However, to fix that, the recipe shouldn't get any Python 2 specific flags hardcoded. Instead, either the core should be fixed if possible, or if that really isn't doable, then at least the Python 2 changes should be added as conditionals.
I therefore suggest that someone with Python 2 interest (I don't have any legacy Python 2 code) checks the state of this, and that these Python 2-specific hardcoded things get removed as in this pull request.
**What was tested:** I applied this patch and successfully tested both lxml install, `python-docx` install (which uses lxml), and generating DOCX documents from scratch …

Remove python 2-specific hardcoded hacks from lxml recipe

---

ci/rebuild_updated_recipes.py

The `rebuild_updated_recipes.py` was updated and some limitations fixed,
but the docstring was left behind, see b6ca832 and d563fcf.

Updates docstring to current state

---

pythonforandroid/recipe.py

Closing parentheses were in the wrong place...

C++ recipe didn't set all instances of `ctx.ndk_dir` in format string

---

pythonforandroid/build.py
pythonforandroid/toolchain.py

I only tried to build a distribution, not an apk from it, but it seems to work fine. The pure python libs i added to --requirements were installed fine in the python-install of the created distribution, just like when i ran p4a from outside of a virtualenv.

allow installing/using p4a in a virtualenv

---

ci/constants.py
pythonforandroid/recipes/protobuf_cpp/__init__.py

Protobuf has been updated to 3.5.1, it's not the last version (3.6.1)
because last version cause trouble during compilation and needs more
work.
This patch also fixes the issue with hardcoded local path for protoc which
could not work. Protobuf needs a version of "protoc" (its compiler, used
to produce .py file from .proto files) compiled for the host platform.
Official binaries for protoc are available, the recipe will download the
one suitable for host and use it.
If the platform is not supported, building may still work if the right "protoc"
is available in search path.

[protobuf_cpp] Updated to Protobuf 3.5.1 + fixed protoc issue

---

pythonforandroid/build.py

This is #1453 after successfully rebasing.

Show actual values in info messages

---

.travis.yml
Dockerfile
ci/constants.py
pythonforandroid/recipe.py
pythonforandroid/recipes/libffi/__init__.py
tox.ini

- adds system dependencies to the Docker container
- updates Cython version
- fixes Dockerfile spaces consistency (removed tabs)
- PEP8 E129 fix

Various CI improvements

---

pythonforandroid/recipes/libsodium/__init__.py
pythonforandroid/recipes/libsodium/size_max_fix.patch

This patch update libsodium to last available version, and remove the
"--enable-minimal" flag which was restricting features and causing
runtime troubles in other recipes.

[libsodium] Updated to last version (1.0.16)

---

.travis.yml
Dockerfile

I omitted this from the original PR because the Travis build failed at pyjnius for some reason. Trying again here to debug it.

Added python3 testapp build to Travis matrix

---

ci/constants.py

With #1435 we're falling back automatically to python2 if the recipe is
incompatible. This is better than maintaining a skip list, because the
recipe will still be compiled under python2 on conflicting dependency
graph for python3crystax.

Cleans broken python3crystax recipe list

---

pythonforandroid/recipes/ruamel.yaml/__init__.py
pythonforandroid/recipes/ruamel.yaml/disable-pip-req.patch

Details at:  https://pypi.python.org/pypi/ruamel.yaml
Bug necessitating patch: 
https://bitbucket.org/ruamel/yaml/issues/114/

Support ruamel.yaml, improved yaml lib.

---

ci/constants.py
pythonforandroid/recipes/doubleratchet/__init__.py
pythonforandroid/recipes/doubleratchet/requires_fix.patch
pythonforandroid/recipes/omemo/__init__.py
pythonforandroid/recipes/omemo/remove_dependencies.patch
pythonforandroid/recipes/omemo/wireformat.patch
pythonforandroid/recipes/pynacl/__init__.py
pythonforandroid/recipes/x3dh/__init__.py
pythonforandroid/recipes/x3dh/requires_fix.patch
pythonforandroid/recipes/xeddsa/__init__.py
pythonforandroid/recipes/xeddsa/remove_dependencies.patch

OMEMO is an end to end encryption algorithm used in XMPP. This recipe
add the module implementing it + its dependencies.
The following dependencies have been added:
- DoubleRatchet
- PyNaCl,
- X3DH
- XEdDSA
This has been tested working with python 2.

[omemo] Added recipes needed to build omemo module

---

ci/constants.py

Also it doesn't make sense to build it against other target python versions e.g. `python3crystax`. Therefore it should be skipped from conditional builds.

python3 is a core recipe built via .travis.yml

---

doc/source/docker.rst
doc/source/index.rst
pythonforandroid/toolchain.py

This way (including the `gradlew` fix) I built a runnable app on Windows 8.1 (in the old Docker for Windows with VirtualBox backend).

Add instructions for using Docker image for building APKs

---

pythonforandroid/build.py
pythonforandroid/distribution.py
pythonforandroid/toolchain.py

My python3 change fixed a bug where dists could be overwritten if a previous dist with the same name but different recipes was present. This wasn't the original intention of the code. However, it looks like the old buggy behaviour was more desirable in practice, so this PR allows dist overwriting by default but adds an option to configure it.

Allow dist overwrite by default

---

.travis.yml
Dockerfile

Prioritize SDK and NDK downloads before everything because once downloaded we don't care about redownloading unless the version is changed and layer cache works this way more efficiently. Redirect Licenses to `/dev/null`, move more important layers up. Move `&&` operators to the front - Docker sometimes, (personally I've encountered it only with `apt` and old `coreutils`), is very critical of the amount of spaces *after* the operator but does not care what's in front of it that much.

Remove crystax docker and optimize Dockerfile

---

pythonforandroid/archs.py
pythonforandroid/build.py

- Fix Toolchain Prefix For x86_64
- Add x86_64 To ```Context.archs```
x86_64 building worked just fine, it just wasn't enabled.

Allow x86_64 To Build

---

pythonforandroid/toolchain.py

I ran into this by accident while making the other pull requests. `--ndk-api` defaults to `0` in the parser, but code in other places (e.g. `distribution.py`) expects it to be `None` if not set. This breaks locating the proper final distribution in some cases when it's not specified, therefore I suggest this should be fixed.

Fix broken --ndk-api default value

---

pythonforandroid/recipes/libxslt/__init__.py

Some recent change to how the build dir is named has broken the libxslt recipe (and with it, lxml2). This pull request makes it build again!

Fix libxslt not getting proper libxml2 path, fixes #1479

---

pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/android/_android.pyx

If not switched to unicode, anything with formating such as `+` will trigger an error for py3 when accessing `JAVA_NAMESPACE` and likes:
b'1' + u'2'
u'1' + b'1'
and py2 just doesn't care.

Fix android module JAVA_NAMESPACE and JNI_NAMESPACE with unicode

---

testapps/testlauncherreboot_setup/sdl2.py

Still some quirks caused by the launcher itself, but the build alone is fine. Feel free to test.

Add setup.py build for kivy-launcher reboot

---

pythonforandroid/recipes/reportlab/__init__.py

This fixes the reportlab GPL issue by removing problematic component. (By default, reportlab has a GPL'ed font that is included into the `.apk` which is quite bad for licensing reasons.)
I tested that:
- the DarkGarden font is gone from the `.apk` (by manually unzipping it and opening the `private.mp3` tarball)
- that the build with `python3crystax` still works
- that a `python3crystax` app can still successfully export PDF with text
So as far as I'm concerned, this should be ready for merging

Fix reportlab GPL issue by removing problematic component

---

pythonforandroid/recipes/audiostream/__init__.py

This PR adds python3 support to audiostream recipe.
Before merging we need to merge kivy/audiostream#24 .

Fixes audiostream recipe on Python3

---

pythonforandroid/bootstrap.py
pythonforandroid/toolchain.py

Minor fixes to basic common bootstrap handling code as suggested by @AndreMiras here: #1496 (see the code review comments)
Please note I added `normpath` *without* replacing the two code lines after it as suggested in the code review, since that one does something different (not a path normalization, but ensures it is a relative path) and I'm pretty sure it needs to stay in.
**Tested, ready for merge**

Minor fixes to basic common bootstrap handling code

---

pythonforandroid/bootstraps/sdl2/build/build.py
pythonforandroid/bootstraps/service_only/build/build.py

The SDL2 & services_only bootstraps don't support building without `--private`, but the package assembling `build.py` will give an obscure backtrace if the option is omitted. This pull request adds in a proper error.

Make SDL2 & services_only bootstrap properly error with missing --private

---

pythonforandroid/archs.py
pythonforandroid/recipes/python3/__init__.py

This makes it no longer hardcoded to build on ARM.

Allow Python 3 To Be Built On Non-ARM Architectures

---

doc/source/buildoptions.rst
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/recipes/python3/__init__.py
testapps/setup_testapp_python3.py

Should be mentioned that the current test app for python3 has been modified by adding libffi to the requirements because the ui for the app has some button to test the ctypes module.
Note: This is the pull request #1463 cleaned up, with documentation and with the commits squashed into one single commit

Add ctypes support for python3's recipe

---

pythonforandroid/bootstraps/sdl2/build/gradle/wrapper/gradle-wrapper.properties
pythonforandroid/bootstraps/sdl2/build/templates/build.tmpl.gradle
pythonforandroid/toolchain.py

To solve the ci errors when trying to download the corresponding build tools which seems to not exist anymore...
Resolves: #1506

Update gradle version

---

pythonforandroid/recipes/android/__init__.py

python-for-android fails to build when running under a python 3 interpreter with the android recipe. There is no decode method in python3 strings.

No need to decode into unicode when running in python 3

---

pythonforandroid/recipes/libnacl/__init__.py

From their [`setup.py`](https://github.com/saltstack/libnacl) I don't see anything including `libsodium`, however the package is a `ctypes` wrapper (from their description), therefore I don't think it's usable without actually including `libsodium` as a dependency.

Fix libnacl recipe missing libsodium

---

.travis.yml
Dockerfile.py2
Dockerfile.py3
pythonforandroid/recipes/android/__init__.py

Fix the issue properly with `unicode_literals` and optional `encode()` in case `bytes` will come from outside as a value in variable. All `'strings'` in that particular file are now by default `unicode` no matter if py2 or py3.
Includes also py3 Dockerfile for testing purposes, though I haven't included it in the matrix yet because the built time will get longer.

Fix bytes/unicode issues in android recipe

---

pythonforandroid/bootstraps/sdl2/build/templates/build.tmpl.gradle

Add google repository for lint-gradle
https://stackoverflow.com/questions/46972122/could-not-find-com-android-tools-lintlint-gradle-android-studio-3

Add google repository at allprojects

---

ci/constants.py
ci/rebuild_updated_recipes.py
pythonforandroid/recipes/jedi/__init__.py

`python3crystax` support was removed from the CI in #1471.
Conditional builds now relies on `python3` with fallback to `python2`.
Adds `python3` support to `jedi` recipe to demonstrate.

Uses target python3 on conditional buids, fixes #1485

---

pythonforandroid/recipes/websocket-client/__init__.py

- fixes hardcoded version in `url` string
- fixes link to original repo in `url` string
- ditches `kivy` dependency

Updates websocket-client recipe, fixes #1253

---

pythonforandroid/recipes/jpeg/Application.mk

Otherwise it throws with an error message about cjpeg depending on undefined dependency cutils when using newer ndk (r15)

Fix jpeg build for newer NDKs

---

pythonforandroid/archs.py
pythonforandroid/bdistapk.py
pythonforandroid/build.py
pythonforandroid/distribution.py
pythonforandroid/graph.py
pythonforandroid/recipe.py
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/toolchain.py
pythonforandroid/util.py
tests/test_graph.py

This both makes the code neater and will make it easier to test things.

Replaced many `exit(1)`s with exception raising

---

pythonforandroid/bootstraps/common/build/build.py

Would fix https://github.com/kivy/python-for-android/issues/1193

Added --no-optimize-python option to remove -OO in sdl2 bootstrap

---

pythonforandroid/toolchain.py

In current master, the ```force-build``` argument is defined, but never used. Small patch to fix it, and clean up a bit of PEP8.
I have also added the config option to Buildozer here: [https://github.com/kivy/buildozer/pull/464](https://github.com/kivy/buildozer/pull/464)

android_new: fix force_build option

---

pythonforandroid/bootstraps/pygame/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

The current manifests don't specify some values in configChanges, e.g. the ones relevant for the side-by-side feature of new Android versions. If these values are missing, the SDLActivity will be restarted - however, SDL2 as a result will simply quit even when the application is in foreground/active without restarting properly, so the application crashes/instant-quits at any of these events.
In this spirit, the pygame bootstrap also seemed to have a lot more of these values added already, avoiding such config-triggered crashes. But for some reason these weren't in the other bootstraps. I unified the values for all bootstraps, and added the missing ones of newer API levels like `density`.
**Note:** to fully get side by side working, we also need #1528 - but with these combined, it works …

Unify configChanges manifest entry and add missing values

---

pythonforandroid/bootstraps/common/build/build.py

This currently causes a crash if the minsdk and ndkapi don't match (in which case the missing argparse argument is accessed).

Re-added argument that was lost during build.py merge

---

doc/source/quickstart.rst
pythonforandroid/bdistapk.py
pythonforandroid/toolchain.py
testapps/setup_testapp_flask.py
testapps/setup_testapp_python2.py
testapps/setup_testapp_python2_sqlite_openssl.py
testapps/setup_testapp_python3.py
testapps/setup_testapp_python3crystax.py

Use API 27 as default for travis & examples, including `armeabi-v7a` as arch default.
26 is new absolute minimum of the Play Store, and otherwise the new SDL2 2.0.9 pull request won't build.

Use API 27 as new default for travis & docs

---

pythonforandroid/python.py

We fix this issue by re-introducing `INSTSONAME`. This variable has been used in all our python recipes, because allow us to remove the version of the compiled python library which is mandatory, at the time of writing, because android does not support versioned libraries (the Java method called to load the libraries only supports a .so suffix).
A little history, because I didn't find any official documentation for this variable, and **it's quite important for us**:
- This variable it's not hacked, it's official and was introduced a long time ago, forms part of the python's shared library building process (python/cpython@1142de3)
- @tito introduced this variable almost at the beginning of the p4a project in (bdefea1)
- @inclement also make use of it when he reworked the python2 recipe …

Fix linkage problems with python's versioned library (reintroduce `INSTSONAME`)

---

pythonforandroid/recipes/Pillow/__init__.py
pythonforandroid/recipes/lxml/__init__.py
pythonforandroid/recipes/reportlab/__init__.py

Fix outdated hardcoded python recipe references in lxml, reportlab & Pillow recipe which prevent building with the new python3 recipe

Fix outdated hardcoded python recipe references in lxml, reportlab & Pillow recipe

---

pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/python2/patches/fix-gethostbyaddr.patch

@tito faced the `gethostbyname_r` issue and send me a fix for that.
This also should fix the second issue described in https://github.com/kivy/python-for-android/pull/1217#issuecomment-453608150, which is the same that @tito found:
See Also: https://bugs.python.org/issue26857
¡¡¡Thanks @tito!!!

 fix missing gethostbyname_r on Android 5.1

---

pythonforandroid/recipes/pycryptodome/__init__.py

Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools and cffi)

[WIP][CORE UPDATE - PART XII] Pycryptodome for both versions of python

---

pythonforandroid/python.py

This fixes the slow copy issue we have when copying files to our distribution folder and affects to python2 and python3.
I tested this in python 3 and @tito made and tested this commit in his own builds for python 2. Travis will say the final words but I suspect that  we can  reduce travis's build timings...will see...
@inclement please...take a look on this when you have time...this affects the core!
Again :smile:, ¡¡¡Thanks @tito!!!

[CORE FIX/ENHANCEMENT] Speedup copy that can be very very long (up to 2 minutes)

---

pythonforandroid/build.py
pythonforandroid/recipe.py

**What this does:** This merge request makes Cython work for the non-recipe regular build. This means CythonRecipe is now unnecessary if the project doesn't need Android-specific extra changes. That's good because a recipe with no actual content is redundant, and because CythonRecipe is problematic:
**Why CythonRecipe is problematic:** I noticed CythonRecipe results in the packages own `setup.py` not run for Cythonization, and instead, p4a engages some manual Cython compilation which is broken per design for a couple of reasons:
1. it assumes all `.pyx` files anywhere in the project dir must compile. This breaks projects that have any `.pyx` files that are *not meant* to be built for the main build and break when Cythonized out of the blue
2. it uses the wrong `site-packages` because it …

Make Cython work without recipe

---

pythonforandroid/recipe.py

Fix APP_PLATFORM not properly passed in NDKRecipe. This is needed so certain NDKAPI/--minimum-api values won't lead to build errors with NDK based recipes, e.g. when using NDKAPI=21 with the current `jpeg` recipe

Fix APP_PLATFORM not properly passed in NDKRecipe

---

doc/source/quickstart.rst
pythonforandroid/recipes/Pillow/__init__.py
pythonforandroid/recipes/freetype/__init__.py
pythonforandroid/recipes/harfbuzz/__init__.py
pythonforandroid/recipes/jpeg/__init__.py
pythonforandroid/recipes/jpeg/remove-version.patch
pythonforandroid/recipes/pil/__init__.py
pythonforandroid/recipes/pil/fix-directories.patch
pythonforandroid/recipes/png/__init__.py

Several actions taken here:
- Update jpeg and moved to mainline
- Update png
- Force to build freetype/harfbuzz **only** as static libraries (to make sure that Pillow/pil gets linked with the static libraries, plus  we cannot use those libraries in his shared form because we will have conflicts with the ones distributed by android os...so no need to build those libraries unless properly versioned as we do with openssl libs)
- Make it work Pillow with python3/python2/python2legacy
- Make it work pil with python2 and python2legacy
- Add freetype/harfbuzz support for Pillow/pil
- Formats the touched recipes and fixes imports
**Note:** This should work, tested in python3. I must review the code and create the proper commits plus I may change something that we may not need. I push it in this …

Rework for Pillow/pil recipes & update jpeg and png

---

pythonforandroid/bootstraps/common/build/jni/application/src/start.c
pythonforandroid/bootstraps/pygame/__init__.py
pythonforandroid/bootstraps/pygame/build/build.py
pythonforandroid/bootstraps/pygame/build/jni/Application.mk
pythonforandroid/bootstraps/pygame/build/src/org/renpy/android/SDLSurfaceView.java
pythonforandroid/bootstraps/pygame/build/templates/ant.properties
pythonforandroid/recipes/pygame/__init__.py
pythonforandroid/recipes/pygame_bootstrap_components/__init__.py
pythonforandroid/recipes/pygame_bootstrap_components/jpeg-ndk15-plus.patch
pythonforandroid/recipes/sdl/__init__.py
testapps/setup_pygame.py

The pygame bootstrap is not working with the latest changes in master branch:
-  because the old python2 recipe has been moved to python2legacy and the pygame bootstrap was made for python2legacy recipe (the android paths for the new python2 are different...so...it's unlikely that it works without touching anything)
- The java build method used for pygame bootstrap is ant (which has been deprecated in modern android ndks and the default java version is not anymore in linux distribution packages (1.5)...now we need version 1.7)
- The distributed jpeg library in sdl does not build fine with modern ndks (assembler issues)
So...saying that, this pr fixes all the mentioned issues and makes that the pygame bootstrap uses the refactored distribution methods (already in python recipe, no need to …

Minimal fixes to make pygame bootstrap work with python2legacy

---

pythonforandroid/recipes/netifaces/__init__.py
pythonforandroid/recipes/netifaces/fix-build.patch

Grants compatibility for both versions of python and cleans up from unneeded source code as well as update the netifaces version.
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools)

[CORE UPDATE - PART VIII] Netifaces for both versions of python (updates the netifaces version)

---

pythonforandroid/recipes/pycrypto/__init__.py

Here I fix pycrypto to make it work with the core-update pull request, which also contains a new version of the openssl libs. I Also update pycrypto to latest version and grants compatibility for both versions of python.
Note: this has to be merged only when the core-update has been merged because it depends on the new python2 recipe and the openssl libs (1.1)

[CORE UPDATE - PART V] Fix pycrypto

---

pythonforandroid/recipes/pymunk/__init__.py

Grants compatibility for both versions of python and enhance flags
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools)

[CORE UPDATE - PART IX] Pymunk for both versions of python and enhance flags

---

pythonforandroid/recipes/protobuf_cpp/__init__.py
pythonforandroid/recipes/protobuf_cpp/fix-python3-compatibility.patch

Fix hardcoded python flags and adapts the recipe to the new python build system.
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools and cffi)

[WIP][CORE UPDATE - PART X] Protobuf_cpp fixes and updated version

---

pythonforandroid/recipes/reportlab/__init__.py

Caused because we try to compile the package with hostpython and we need to use target python or we will not have the right python headers.
Resolves: #1575

Fix reportlab's recipe `crypt.h` error

---

pythonforandroid/recipes/zeroconf/__init__.py

This is one of the commits that @tito needed to make it work the `zeroconf` recipe while testing the recently merged core update (He sended to me a reference to the branch He used via discord)...so...all the credit to him.
¡¡¡Again, thanks @tito!!! :smile:

Fix zeroconf compilation and grants python3 compatibility

---

Dockerfile.py2
Dockerfile.py3

Fixes the travis error recently appeared in prs: #1600 and #1601
The error in travis logs is:
```
Accept? (y/N): Skipping following packages as the license is not accepted:
Android SDK Build-Tools 26.0.2
The following packages can not be installed since their licenses or those of the packages they depend on were not accepted:
build-tools;26.0.2
```
See also: https://travis-ci.community/t/accept-license-for-android-build-tools-27-0-3-bug/549

Fix sdk license error for travis tests (CI)

---

pythonforandroid/recipes/libzbar/__init__.py
pythonforandroid/recipes/pyzbar/__init__.py
pythonforandroid/recipes/zbar/__init__.py
pythonforandroid/recipes/zbarlight/__init__.py

- Add ability to use libzbar for python2 and python3
- Add two more recipes (pyzbar and zbarlight) because those two are compatible with python3, the old zbar recipe seems unmaintained and working only for python2.
**Note: this should be properly tested with some application using this recipes, I only tested the build for python 2 and python 3...so...any feedback about this will be great...**

[WIP] Rework zbar (add python3 compatibility + add recipes: pyzbar and zbarlight)

---

pythonforandroid/recipes/pysha3/__init__.py

Grants compatibility for both versions of python, remove unneeded flags and fix the hardcoded ones.
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools)

[CORE UPDATE - PART XIII] Pysha3 for both versions of python

---

pythonforandroid/recipes/apsw/__init__.py

Grants compatibility for both versions of python and cleans up from unneeded source code
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and may depend on some recipes which aren't python3  compatible in the current master branch (setuptools)

[CORE UPDATE - PART VII] Apsw for both versions of python

---

pythonforandroid/recipes/scrypt/__init__.py

Here I fix scrypt recipe to make it work with the core-update pull request, which also contains a new version of the openssl libs. Also grants compatibility for both versions of python.
Note: this has to be merged only when the core-update has been merged because it depends on the new python2 recipe and the openssl libs (1.1)

[CORE UPDATE - PART VI] Fix scrypt

---

pythonforandroid/recipes/m2crypto/__init__.py

Grants compatibility for both versions of python, bump the version number and removes unneeded flags.
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on some recipes which aren't python3  compatible in the current master branch (setuptools) or compatible with openssl 1.1 (introduced in the core-update #1537)

[CORE UPDATE - PART XI] M2crypto for both versions of python and updated version

---

pythonforandroid/recipe.py

This adds download retries to deal better with connection hiccups during build. I can't count how many times I got either a minor wifi hiccup, or actually one of the servers just didn't wanna cooperate with a download and the entire build fell apart. This is really annoying to happen, and so while this retry mechanism may not cover all types of downloads in p4a, at least it will add retrying for a good chunk of them!

Add download retries to deal better with connection hiccups during build

---

MANIFEST.in
doc/source/apis.rst
doc/source/index.rst
doc/source/quickstart.rst
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/jni/application/src/start.c
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/HIDDevice.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/HIDDeviceManager.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/HIDDeviceUSB.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDL.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLActivity.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLAudioManager.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLControllerManager.java
pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch
pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/android/loadingscreen.py
pythonforandroid/recipes/android/src/android/permissions.py
pythonforandroid/recipes/sdl2/__init__.py
setup.py

Bump to SDL2 to 2.0.9.
State: **ready for merge**
Example use for new runtime permissions API added by this pull request:
```
from android.permissions import Permission, request_permission,\
check_permission
request_permission(Permission.WRITE_EXTERNAL_STORAGE)
```
Gains:
- CTRL key **finally** works properly on physical keyboards
- Side-by-side works properly (with #1522 merged), including contents resizing properly to half the screen
- All other bugfixes that happened between 2.0.4(?) and 2.0.9
- API >=23 runtime permission API added to p4a's `android` module

Bump SDL2 to 2.0.9 & Add API >=23 runtime permissions API

---

testapps/testapp_keyboard/main.py

The keyboard app crashes at launch right now because it has outdated assumptions about the site packages folder and it tries to list things from there. This changes the path accordingly, and avoids a crash in the future if the path shouldn't be present/moved again.

Fix incorrect site-packages path breaking keyboard test app at runtime

---

doc/source/commands.rst

Fix `--force-build` incorrectly listed as `--force_build` in the documentation, fixes #1565

Fix --force-build incorrectly listed as --force_build, fixes #1565

---

pythonforandroid/python.py
pythonforandroid/recipes/libffi/__init__.py
pythonforandroid/recipes/libffi/fix-includedir.patch
pythonforandroid/recipes/python2/__init__.py

It has been reported of errors with `ctypes`, even when the `ctypes` module seems to be built fine.
@tito is one of the affected by this and he found that, in some system configuration, python could be:
```compiled with the headers of the system libffi, but runs with the target libffi```
That will end in an app crash...
So...this pr makes that the python build make use of our libffi headers.
This would be a third solution to add to the ones proposed by @tito in #1605
**This solution avoids to patch python3 and will also work for python2**
!!!So many thanks @tito to found where the problem started :smile:!!!

Fix libffi/ctypes - wrong libffi headers when building python

---

pythonforandroid/toolchain.py

When using some of the options like `--private` without an argument, which shouldn't be done but users make mistakes sometimes, this currently causes a weird backtrace error that isn't obvious to the average user. This pull request addresses that problem such that better error handling can happen

Fix --private and others showing weird error when used without argument

---

pythonforandroid/recipes/greenlet/__init__.py

Also bump to latest version 0.4.15.

Migrates greenlet to new python3 recipe, fixes #1245

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/jni/application/src/start.c
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/distribution.py
pythonforandroid/python.py
pythonforandroid/recipes/python2/__init__.py

We already had before this feature for python2 (python2legacy now)  and we loosed it with the recently merged core update. Also we will be able to compile our python install files for python 3 (new feature for python3). But be aware that to achieve this we must modify a little our source code because as of python 3.5 the `.pyo extension` for compiled python files has been removed in favour of  `.pyc extension`, so it requires to modify `start.c` and `PythonActivity.java` files, which only contemplated the .pyo extension.
Notes:
- the default behaviour will be to compile all python files to the corresponding compiled extension, so **this way the apk will run faster**
- also we compile the code with the option `-00` which will strip the docs, so we **will generate lighter apks**
- this …

[WIP] Restores the ability to compile the python files into .pyo/.pyc (for both versions of python)

---

pythonforandroid/recipe.py
pythonforandroid/recipes/pygame_bootstrap_components/__init__.py
pythonforandroid/recipes/pygame_bootstrap_components/jpeg-ndk15-plus.patch

This is needed to properly apply the patches for the pygame bootstrap components recipe, because we must apply the patches from build_container_dir and the current patching method only allow us to do that from the build directory (which not exists in pygame components because we delete it). Also fix a typo error for pygame components.

Allow patching from any folder + fix pygame components issues

---

pythonforandroid/recipes/libffi/__init__.py

Fixes https://github.com/kivy/python-for-android/issues/1569

Removed argument to cp that doesn't exist on macOS

---

pythonforandroid/graph.py
pythonforandroid/recipe.py

This should fix the recipe ordering issue reported in https://github.com/kivy/python-for-android/issues/1590 and elsewhere.
I wanted to add a test case for this but couldn't actually find an input to the graph that resulted in an invalid ordering unless opt_depends were respected. The reason is that openssl and sqlite3 both have no dependencies, so the graph is already guaranteed (I think) to schedule them to be built before python3.
Nevertheless, opt_depends support was definitely broken and this should fix it. It must have been broken for a very long time, since I replaced the graph resolution. I guess complex opt_depends requirements don't come up that often.

Made recipe graph resolution respect opt_depends

---

pythonforandroid/recipes/gevent/__init__.py
pythonforandroid/recipes/librt/__init__.py
pythonforandroid/recipes/lxml/__init__.py

Because some recipes inserts flags without our control (`-lrt`) and this is a problem because librt does not exist in android, but has been integrated into libc, so, this recipe create a temporary symbolic link from libc to librt so the compilation can find the necessary `symbols/functions` to finish the compilation
Note: Once we end the build we will remove the created symbolic link
¡¡¡Thanks @AndreMiras, for this idea of "dumb" librt recipe!!!

Create a `dumb` librt recipe and refactor the affected recipes to make use of this

---

pythonforandroid/recipe.py

The `tar tf` command is actually just used to find the root directory.
Verbosing makes the Travis log grow too big, e.g. for `openssl` recipe.
Also simplify the file type detection, `endswith()` can take tuple.

Do not verbose the "tar tf" command

---

pythonforandroid/recipes/boost/__init__.py
pythonforandroid/recipes/boost/fix-android-issues.patch
pythonforandroid/recipes/boost/user-config.jam
pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libtorrent/setup-lib-name.patch
pythonforandroid/recipes/libtorrent/use-soname-python.patch
pythonforandroid/recipes/libtorrent/user-config-openssl.patch

Grants compatibility for both versions of python, maintaining the same build method (android's ndk standalone toolchain and b2 tool) but now we will use clang as the compiler, plus starts the migration of the stl lib from gnustl_shared to c++_shared (the only one stl lib starting from ndk18)
Note: this has to be merged only when the core-update has been merged because it has been tested with the new python core and depends on the new openssl lib version 1.1 introduced in  #1537

[WIP][CORE UPDATE - PART XIV] Libtorrent+boost for both versions of python and updated versions

---

pythonforandroid/archs.py
pythonforandroid/recipes/librt/__init__.py

This fixes that the librt recipe requires the NDK folder to be writable. The NDK folder can be installed system-wide and may not be writable, so without this fix the librt build crashes in such an environment. This fixes #1621 
Fixes the build for me! Feel free to test & merge! (or to tell me what to change)

Fix librt recipe requires that NDK folder is writable

---

ci/constants.py
pythonforandroid/recipes/ifaddrs/__init__.py

Makes sure the compiler is being used rather than ccache alone.
Also pin the commit version and use zip download rather than git clone.

Fixes ifaddrs recipe, closes #1398

---

pythonforandroid/recipes/python3/__init__.py
pythonforandroid/recipes/python3/patches/fix-ctypes-util-find-library.patch

This is finally my long-delayed followup to #1517 to fix `ctypes.util.find_library()` for Python 3. It should fix the last somewhat showstopper bug to using Python 3 & ctypes out of the box on p4a master :heart: 
done & tested (with real world python3 app that uses ctypes)

Fix ctypes.util.find_library() not finding any libraries on Android

---

pythonforandroid/archs.py

Revert use of shlex.quote introduced in `pythonforandroid/archs.py` to avoid problems with python 2
tested & (my own real app) build ran through, ready for merge (or change requests) as far I'm concerned

Revert use of shlex.quote to avoid problems with python 2

---

pythonforandroid/bootstrap.py

Due to hardcoding, the arch-dependent `strip` command is not invoked when building for `arch` other than `--arch=armeabi-v7a` (e.g. `strip` not detected when `--arch=x86`).
This PR fixes
- the problem above, and
- the case of applying `strip` erroneously when the file name is `''` (an empty string).

Fix strip in bootstrap

---

pythonforandroid/recipe.py

Seems pretty benign so no reason not to do it.
Fixes https://github.com/kivy/python-for-android/issues/703.

Set $LANG in PythonRecipe

---

.travis.yml
Dockerfile.py2
Dockerfile.py3

Also removed `apt -y clean` layer optimization introduced in df60061.
That way we could skip running `apt -y update` too many times which also
seems to have some issues recently on Travis.

Retry on download hiccups, refs #1306

---

pythonforandroid/bootstraps/common/build/build.py

Fixes https://github.com/kivy/python-for-android/issues/1009
This is important because if the compileall fails, no .pyc is generated and the file will be missing in the APK.

Made build.py stop running if compileall failed

---

pythonforandroid/bootstraps/common/build/build.py

Fixes https://github.com/kivy/python-for-android/issues/1271.
Using singleTask seems appropriate to make sure that our activity is not recreated, so new intents are passed to the existing activity if possible. Doc at https://developer.android.com/guide/topics/manifest/activity-element.

Made the activity launch mode default to singleTask

---

pythonforandroid/archs.py

I forgot to include this in pr `Fix hardcoded entries (build platform) for core modules: archs and python` (#1597)
References: `Fix build platform hardcoded flags for archs.py` (f570def)

Fix linux hardcoded entry in archs.py

---

pythonforandroid/python.py
pythonforandroid/recipes/numpy/__init__.py

Uses `-j` flag on target/host python as well as numpy to run compilation
in parallel. In Python an optimum number of jobs is guessed if the flag
is used alone. In NumPy it must be explicitly set.

Speed up Python and NumPy compilation process

---

Dockerfile.py2
Dockerfile.py3

For some reason running the `chown` command explicitly is hanging on
Docker. Using the `--chown` parameter in the `COPY` command is faster.
However that new method has a couple of drawbacks:
1) it was introduced in a recent Docker version 17+
2) it doesn't accept variables as argument, only hardcoded values
Also note that we don't need to chmod `ANDROID_SDK_HOME` anymore.

Speed up Docker chown via COPY parameter

---

setup.py

In #1664 README got renamed without updating the `setup.py`

s/README.rst/README.md/ refs #1664

---

setup.py

Fix setup.py install breaking due to unicode characters in README.md on Python 3

Fix setup.py install breaking due to unicode characters in README.md on Python 3

---

ci/constants.py
pythonforandroid/recipes/netifaces/__init__.py

Currently in WIP as it's blocked by build been green via https://github.com/kivy/python-for-android/pull/1674

Bumps netiffaces version & removes from broken list, refs #1539

---

pythonforandroid/recipes/zope_interface/__init__.py
pythonforandroid/recipes/zope_interface/fix-init.patch

The `zope.interface` module lacks of the `__init__.py` file in one of his folders, that leads into:
`ImportError: No module named zope.interface`

Fix zope_interface and add python3 compatibility

---

pythonforandroid/bootstrap.py
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/__init__.py
pythonforandroid/bootstraps/service_only/__init__.py
pythonforandroid/bootstraps/webview/__init__.py
pythonforandroid/build.py
pythonforandroid/graph.py
pythonforandroid/recipe.py
pythonforandroid/toolchain.py
pythonforandroid/util.py
tests/test_graph.py
tests/test_recipe.py

- fix graph depending on capitalization of dependency/recipe names when pip doesn't
- fix graph giving no useful errors for conflicts (now it gives them sometimes)
- fix graph entering infinite loop when no bootstrap is found
- fix recipe not being obtainable irregardless of capitalization
- fix recipe IOError-on-doesn't-exist not distinguishable from
recipe-exists-but-code-messes-up-and-causes-unintentional-IOError.
a non-existent recipe will now cause a ValueError
- fix the bootstraps' own dependencies being wrong and unused
- change preferred default from `python2` + `sdl2` to `python3` + `sdl2`
- possibly other minor fixes I forgot about
(some of these fixes are required for #1625 / project's `setup.py` to be reasonably used)

Fix various issues with graphs and recipes

---

pythonforandroid/recipes/pycryptodome/__init__.py

The latest version was leading to compilation errors.
Tested OK with:
```
python setup_testapp_python3.py apk --sdk-dir $ANDROID_SDK_HOME
--ndk-dir $ANDROID_NDK_HOME --bootstrap sdl2 --requirements
python3,kivy,pycryptodome==3.6.3
```

Downgrade to pycryptodome==3.6.3

---

doc/source/apis.rst
doc/source/buildoptions.rst
doc/source/quickstart.rst
pythonforandroid/bootstrap.py
pythonforandroid/graph.py
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/toolchain.py
tests/test_graph.py

This is another subpart split out of my misguidedly oversized #1625 (`setup.py`) pull request.
Changes:
- Adds `--blacklist` option that prevents recipes/packages from being added even though they are in the `depends` of recipes or otherwise added
- Makes the following modules included per default: `android` (via `bootstrap.py` dependency of all bootstraps), `openssl`/`libffi`/`sqlite3` (via `python3` recipe dependency)
- Documents `--blacklist` option and that `android` is now included by default
- Cleans up the packaging kivy/sdl2 apps part in the Quickstart section a little

Implement --blacklist option and include more modules/recipes by default

---

doc/source/buildoptions.rst
pythonforandroid/toolchain.py

Rename misguided shadowing --blacklist to --blacklist-requirements.
Merging this only makes sense if you want to keep the blacklist functionality of course, see discussion in #1683

Rename misguided shadowing --blacklist to --blacklist-requirements

---

doc/source/quickstart.rst

openjdk7 is deprecated on Ubuntu, tested on Ubuntu18.04

change dependency from jdk7 to jdk8

---

testapps/setup_keyboard.py
testapps/setup_testapp_flask.py
testapps/setup_testapp_python3.py
testapps/setup_testapp_python3_sqlite_openssl.py
testapps/setup_testapp_python_encryption.py
testapps/setup_testapp_service.py
testapps/setup_vispy.py

This complements @JonasT work in pull requests #1683 and #1689 and goes a little further
**Note:** This only affects those tests that are not python2's specific

Make testapps use python3 per default and adapt to `blacklist-requirements`

---

pythonforandroid/bootstraps/common/build/build.py

This fixes the issue where additional jar files specified in the buildozer spec at `android.add_jars` aren't copied to the correct build directory resulting in a failed build attempt.

FIX: copy additional jar files into the correct libs directory

---

pythonforandroid/bootstraps/common/build/jni/application/src/start.c

Fixes #1702.  This is regression related to #1690.  For non-SDL2 bootstrap, we should not use `SDL_setenv()` here; instead, use the plain `setenv()` as previously.  Sorry that I missed testing this bootstrap case.
Before fix:
```
/home/a/.local/share/python-for-android/build/bootstrap_builds/webview-python2/jni/application/src/start.c:471: error: undefined reference to 'SDL_setenv'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
After fix: No compile errors regarding this issue.

Fix setenv() of non-SDL2 bootstrap

---

pythonforandroid/recipes/android/src/setup.py

Building an apk with `--bootstrap=webview` breaks at `pythonforandroid/recipes/android/src/setup.py` as follows:
```
$ p4a apk --private ./myapp --package=org.example.myapp --name myapp --version 0.1 --bootstrap=webview --requirements=python2 --arch=armeabi-v7a --debug
```
(snip)
```
RAN: /home/a/.local/share/python-for-android/build/other_builds/hostpython2/desktop/hostpython2/native-build/python setup.py build_ext -v
STDOUT:
Traceback (most recent call last):
File "setup.py", line 9, in <module>
sdl_libs = lib_dict[os.environ['BOOTSTRAP']]
KeyError: 'webview'
```
This PR is to get around the `KeyError` that happens in **any** non-SDL bootstrap modes.

Fix compile error of recipe "android" for non-sdl bootstrap build

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

`loadLibraries()` fails in loading native libs when `arch` is `arm64-v8a` or `x86_64`.
**Explanation**
On 64-bit Android, the path obtained by `getFilesDir().getParentFile().getAbsolutePath() + "/lib"` (e.g. `/data/data/<package>/lib`) is not available ([ref.](https://stackoverflow.com/questions/41709129/lib-directory-missing-after-installing-64-bit-android-application); I did verify this on my 64-bit Android devices).  For the same reason, `libsDirPath` in `getLibraries()` below is resolved to a non-existent path:
https://github.com/kivy/python-for-android/blob/e7c11179d4a50ed1f1ca3948c8a64c6990152d1c/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonUtil.java#L34-L38
As a result, in `addLibraryIfExists()`, a `NullPointerException` is thrown at `files.length`. …

Fix loadLibraries() failing for 64bit arch

---

pythonforandroid/recipes/flask/__init__.py

Fixes https://github.com/kivy/python-for-android/issues/1728

Removed unnecessary genericndkbuild dependency from the flask recipe

---

pythonforandroid/bootstraps/common/build/build.py

Android version code is generated to account for the architecture it is built for as well as the minimum sdk.
The new version format is arch-minsdk-app version
This will allow apps of the same version name built for different architectures be uploaded to the play store and will provide separation for overlap.
example:
app version: 1.0.5
min sdk: 21
old style version code would be 10005 for all architectures
new version codes would be:
x86: 62110005
arm7: 72110005
arm8: 82110005

Generate android version code accounting for arch and min sdk

---

pythonforandroid/recipes/psycopg2/__init__.py

Also note this recipe seems to depend on `nl_langinfo` which is only
available from ANDROID_API 26.

Fixes psycopg2 lib install dir, closes #1711

---

.travis.yml
pythonforandroid/logger.py
pythonforandroid/recipe.py

Otherwise Travis CI complains about log size
Ref kivy/buildozer#823

Add ci_mode to disable download progress

---

doc/source/recipes.rst

Fix documentation on wrong `PythonRecipe` import, that stopped working after the #1284

Fix import in 'Using a PythonRecipe' doc

---

pythonforandroid/recipes/groestlcoin_hash/__init__.py

apparently since the move to python3, the recipes can/should disable call_hostpython_via_targetpython.

fix groestlcoin_hash recipe

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_only/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

Support for: 
https://developer.android.com/guide/topics/manifest/uses-library-element

Added option to support custom shared libraries with <uses-library> tag

---

doc/source/apis.rst
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/recipes/android/src/android/permissions.py
pythonforandroid/recipes/pyjnius/__init__.py

Matches the official Android API via, making it possible to request
multiple runtime permissions at once.
Keeps the previous `android.permissions.request_permission()` interface
for compatibility.
Bumps pyjnius to post 1.2.0 release that solves required method
resolution issues. On 1.2.0, the error was:
```
jnius.jnius.JavaException: No methods matching your arguments, available: []
```

Requests runtime permissions list, fixes #1704

---

pythonforandroid/recipes/android/src/android/_android.pyx

not sure why i need that if others don't, but i can't build anything depending on the android recipe without it.

decode JAVA_NAMESPACE in _android.pyx

---

pythonforandroid/recipes/android/__init__.py

#1747 broke Python3 compatibility by decoding a string. Here is a fix.

Remove string decoding in _android.pyx for Python3 compatibility

---

pythonforandroid/recipes/libxml2/__init__.py

libxml2 has been updated from 2.7.8 to 2.9.8 at commit
6ed40d551e4bbf87569bd30d929526173ff0e6aa, but version 2.8.0 added lzma
compression support, and with it a dependency to liblzma (available at
https://tukaani.org/xz/).
This patch fixes it by disabling lzma support.
A future improvment may add xz recipe and dependency.

[libxml2] fixed crash on missing lzma.h

---

pythonforandroid/recipes/protobuf_cpp/__init__.py

two issues were causing troubles with protobuf during runtime:
- a missing `__init__.py` in site-packages/google was preventing to import the lib (at least with Python 2)
- the links options (`-l …`) where not taken into account. By moving
them to LDFLAGS it works correctly.

[protobuf_cpp] fixed runtime issues

---

ci/constants.py
pythonforandroid/recipes/libglob/__init__.py

- makes sure the compiler is being used rather than ccache alone
- do not manually copy over header files

Fixes libglob recipe, closes #1399

---

pythonforandroid/recipes/kivy/__init__.py

a95d67f revision of Kivy doesn't handle properly the orientation on
Android (see https://github.com/kivy/python-for-android/issues/1763).
Revision c4d6894 works with `--orientation user`

[kivy] updated recipe to c4d6894 revision

---

Dockerfile.py3
pythonforandroid/archs.py
pythonforandroid/python.py
pythonforandroid/recipes/libffi/__init__.py
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/recipes/python3/patches/remove-fix-cortex-a8.patch

Force the use of lld (LLVM's linker), and include a python37 bugfix.
https://clang.llvm.org/docs/Toolchain.html
https://lld.llvm.org/
https://bz-attachments.freebsd.org/attachment.cgi?id=200526
I use p4a in windows bash (windows subsystem for linux). Upgrading from the stable version 0.7.0 to the develop version 0.7.1 causes linker errors when building libffi:
```
/other_builds/libffi/x86__ndk_target_21/libffi/.libs/libffi.so: error: undefined reference to 'ffi_prep_cif_machdep'
/other_builds/libffi/x86__ndk_target_21/libffi/.libs/libffi.so: error: undefined reference to 'ffi_prep_closure_loc'
/other_builds/libffi/x86__ndk_target_21/libffi/.libs/libffi.so: error: undefined reference to 'ffi_prep_raw_closure_loc'
/other_builds/libffi/x86__ndk_target_21/libffi/.libs/libffi.so: error: …
```

Fix libffi recipe, and build + runtime linker errors when compiling on WSL

---

pythonforandroid/recipes/pysdl2/__init__.py

Fix that the PySDL2 version is outdated and adjust from non-PyPI install source to a proper PyPI install source

Fix outdated PySDL2 version and non-PyPI install source

---

pythonforandroid/recipes/xeddsa/__init__.py

The copy of the build shared library was not working anymore after the
update of python2 build chain. This patch fixes it by using
self.ctx.get_site_packages_dir().

[xeddsa] fixed shared library copying

---

pythonforandroid/recipes/android/src/android/_ctypes_library_finder.py
pythonforandroid/recipes/python3/patches/fix-ctypes-util-find-library.patch
tests/test_androidmodule_ctypes_finder.py

This will change `ctypes.util.find_library()` to properly query & search native lib dir, which should fix #1770
Ran fine for me but I tested with an ARMv7 app. I asked the original reporter for an ARM64 test

Properly search native lib dir in ctypes, fixes #1770

---

pythonforandroid/recipe.py
tests/test_recipe.py

Python 2 raises warnings on `imp.load_source()` when the module name contains dots. Ignoring this warning makes p4a output/logs more readable.
Note that for some reason the regression test will only catch the regression if ran isolated, e.g. via:
```sh
tox -e py27 -- tests/test_recipe.py::TestRecipe::test_import_recipe
```

Ignores Python 2 import_recipe() warnings

---

pythonforandroid/recipes/sdl2_mixer/__init__.py
pythonforandroid/recipes/sdl2_mixer/toggle_modplug_mikmod_smpeg_ogg.patch

This PR updates sdl2_mixer version to 2.0.4
Tested on a real-world app w/ python3

Updated sdl2_mixer version to 2.0.4

---

pythonforandroid/recipes/sqlalchemy/__init__.py
pythonforandroid/recipes/sqlalchemy/zipsafe.patch

Fix sqlalchemy build errors and bump sqlalchemy from 1.0.9 to 1.3.3.

Fix sqlalchemy recipe

---

pythonforandroid/recipes/libzmq/__init__.py
pythonforandroid/recipes/pyzmq/__init__.py

fixed `crtbegin_so.o` `crtend_so.o` link errors described [here](https://github.com/kivy/python-for-android/issues/1802)
solution: adding sysroot compiler option
Also:
-- updated ZMQ library version from github releases
-- a little fiexes on env vars
-- added method for include directories

Fixed libzqm recipe linking issues

---

pythonforandroid/recipes/setuptools/__init__.py

Version 40.0.0 seems to give gateway timeout while downloading:
```
wget
https://pypi.python.org/packages/source/s/setuptools/setuptools-40.0.0.zip
--2019-04-18 12:26:42--
https://pypi.python.org/packages/source/s/setuptools/setuptools-40.0.0.zip
Resolving pypi.python.org (pypi.python.org)... 151.101.132.223,
2a04:4e42:1f::223
Connecting to pypi.python.org (pypi.python.org)|151.101.132.223|:443...
connected.
HTTP request sent, awaiting response... 301 Redirect to Primary Domain
Location:
https://pypi.org/packages/source/s/setuptools/setuptools-40.0.0.zip
[following]
--2019-04-18 12:26:43--
https://pypi.org/packages/source/s/setuptools/setuptools-40.0.0.zip
Resolving pypi.org (pypi.org)... 151.101.64.223, 151.101.128.223,
151.101.192.223, ...
Connecting to pypi.org …
```

Bumps to setuptools==40.9.0

---

.travis.yml
Dockerfile.py3
doc/source/distutils.rst
doc/source/quickstart.rst
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/build.py
pythonforandroid/distribution.py
pythonforandroid/pythonpackage.py
pythonforandroid/toolchain.py
setup.py
tests/test_pythonpackage.py
tests/test_pythonpackage_basic.py
tox.ini

Run project's setup.py if present, unless --ignore-setup-py was set.
**What exactly does this do:**
Changes to `p4a`'s behavior:
1. If a `setup.py` is present in the `--private` code directory and `--use-setup-py` is set,
all dependencies that map to recipes will be implicitly added to `--requirements`
2. After all modules in `--requirements` have been built, the `setup.py` is run (again only if
`--use-setup-py` was specified)
This has the following consequences:
1. You can now use a `setup.py` and `--use-setup-py`, and either omit `--requirements`
(If you use Python 3) or otherwise just specify `--requirements=python2
2. For projects without a `setup.py` file, *nothing changes*
3. For projects that for some reason have a `setup.py` but don't want it to run for p4a, there will be a big …

[WIP] Run project's setup.py if present, unless --ignore-setup-py was set

---

doc/source/apis.rst

Fixes https://github.com/kivy/python-for-android/issues/1780

Fixed doc links to plyer and pyjnius

---

pythonforandroid/build.py
pythonforandroid/toolchain.py

I broke things with the `setup.py` pull request :joy: commands other than `p4a apk` appear to be broken, from my test this fix makes it work again, sorry :grimacing:

[WIP] Fix crashes when using other commands than 'apk'

---

pythonforandroid/pythonpackage.py
tests/test_pythonpackage_basic.py

This is just an adjustment for the workaround for
https://github.com/pypa/pip/issues/6097 to fix a corner case.
(The affected corner case was added to the unit test!)
So this code should really be thrown out once pip fixes that issue (so if we're wondering "should we even be dealing with this corner case?" - no, we shouldn't, pip should but sadly right now it doesn't)
---
Also I had this small fix lying around before #1625 was merged but forgot to include it :woman_facepalming:  :woman_facepalming:  :woman_facepalming: lol

Fix corner case of pip hack workaround we should get rid of anyway

---

pythonforandroid/pythonpackage.py
tox.ini

Due to a recent update of tox our ci tests are failing.
This pr makes two things:
- Fixes the import errors with the latest tox by setting the `PYTHONPATH` environment variable
- Fixes `python_package_basic` tests error: `pep517.wrappers.BackendUnavailable`
**Note:** resolves ci's tox errors appeared in #1819

Fix `CI` errors with latest tox

---

.travis.yml
ci/constants.py
pythonforandroid/recipes/opencv/__init__.py

I saw this in the following situations:
- **Random error with `CI` tests that shouldn't fail** (I suspect that this is caused at times of high overload of the travis system)...like this one: https://travis-ci.org/kivy/python-for-android/builds/527925625
- **Recipe that takes a long time to being processed** like the opencv recipe (also see #1661): https://travis-ci.org/kivy/python-for-android/jobs/487920951[ci]
So, in order to fix the above mentioned situations, this pr will run a background process which will print a message in travis log each 9 minutes. This background process will be killed after we make our tests.
Also we enable the `opencv` recipe for `rebuild_updated_recipes` in order to demonstrate that the background process introduced in here works as expected.
**As a side …

Fix travis log doesn't produce any output for more than 10 minutes

---

pythonforandroid/bootstraps/common/build/build.py

The build.py file expects the window arg to be set, however, when building with a service_only bootstrap, this variable is not set. This results in an error when building the private.mp3 resource.

Fixed build file for service_only bootstrap

---

pythonforandroid/recipes/freetype/__init__.py
pythonforandroid/recipes/harfbuzz/__init__.py

To fix cyclic dependency between `freetype` and `harfbuzz` and to produce shared libraries
And because we use those libraries in multiple recipes and building those libraries as shared libraries can reduce a little the apk size in some circumstances (when we build multiple recipes that depends on those libraries)
This changes are friendly with #1822 which needs shared libraries for `freetype` and `harfbuzz`
**Important note:** if `freetype` and `harfbuzz` are in `requirements`, then the cyclic dependency of those libraries will be solved otherwise the library will be build without linking with the other library (as expected)
**As a side note:** tested with a Pillow test app and arch armv7a (#1826)

Rework of freetype/harfbuzz recipes

---

testapps/on_device_unit_tests/README.rst

Added basic documentation on how to build and run the on device unit tests, to go with #1836

Added readme for on device unit tests

---

.coveragerc
.travis.yml
README.md
tox.ini

To achieve the desired result we also modify the travis file, Implementing travis stages which are:
- **Lint** (our tox tests runs in here and also we collect the coverage data)
- **Test** (our build tests, which are exactly the same than the ones we have been using for a while, but now those are labelled)
Make use of the stages allow us to sequentially run some tests (without loosing the parallel builds, so the `Test` stage will be runned in parallel mode...the same behaviour than we have right now). Be aware that if the `Lint` stage fails, then the `Test` stage will never be run. This feature has been implemented in here in order to only send the coverage reports in case that we succeed with `Lint` stage.
This is friendly with the idea to implement some kind of automation to auto …

Add coverage with coveralls and make use of travis stages

---

README.md
doc/source/contribute.rst

Added some documentation about our new git flow structure, and documented the release checklist proposed at #1836.
I propose that once everyone is happy with this, I'll merge the PR, then immediately create the develop branch and the first release branch. We can tidy up any procedural issues in that first release, including making sure the release checklist works okay.
The only real unanswered question is what CalVer format to use. Is there any reason not to go with YYYY.MM.DD? Is some other option more normal (or more [pep-440 compatible](https://www.python.org/dev/peps/pep-0440/))?

Documented the development and release models

---

tests/test_archs.py

Because this module isn't covered by our tests and this allow us to improve a little our coverage

Add unittest for module `pythonforandroid.archs`

---

.travis.yml

At this point we really should get an arm64-v8a test going, and the second python2 build doesn't seem that important. Any objection to replacing it?

Replaced one of the python2 travis builds with python3 arm64-v8a

---

doc/source/contribute.rst

Some minor improvements to the doc that I made while going through the release.

Improved release model documentation

---

pythonforandroid/recipe.py

This fixes a case when a recipe for a tar.gz archive attempts to mv to a subdirectory of itself.

bugfix: unpack for nonzip archives also needs to compare basename(dir)

---

tests/test_distribution.py

To enhance our code coverage...a little more
**Note:** In order to optimize the tests, I `mocked` any file creation

Add unittest for module `pythonforandroid.distribution`

---

pythonforandroid/pythonpackage.py
tests/test_pythonpackage_basic.py

This change ensures the pythonpackage functions return an error when someone attempts to get build requirements of a wheel (beyond the regular runtime dependencies) since this is currently not implemented properly.
It might be possible to determine and obtain this info somehow, but since this is not ever actually used by our `setup.py` functionality I have made sure it raises a `NotImplementedError` now if this is ever attempted, instead of returning incorrect data as previously.
This should also fix the test failure of `test_pythonpackage_basic.py` on current latest `develop`.

pythonpackage can't return build requirements for wheels, make it return an error if attempted

---

pythonforandroid/recipes/freetype/__init__.py

To fix freetype build for `openSUSE` and maybe other oses.
**Note:** It seems that there is a bug in `bzip2-devel` for debian and derivatives which are distributed without a `pkg-config` file, so when we compile freetype with a debian os (or derivative) we build it without bzip2 support, so we enforce to disable bzip2 support, because we know that freetype works fine without bzip2 support
Resolves: #1854

Add `--without-bzip2` to freetype's configure args

---

pythonforandroid/pythonpackage.py

Testing a fix for locating system python on travis. ~~This will most likely not work yet but I need to see the travis output to figure out what is wrong (it's a travis-specific problem) hence I'm already making the pull request~~ This fixes the tests breaking when the system python is not in the `$PATH` env var for some reason (usually that doesn't happen, but with travis & `python3.7` for some reason it does)

Fix locating system python when it's not in $PATH (weird but happens, apparently)

---

README.md
doc/source/quickstart.rst
doc/source/troubleshooting.rst

I revamped the starting out section in the README, to address the following issues:
- I tried making it super clear that the target api, minimum api & ndk version of the quickstart should be used to avoid trouble. we have so many beginners who come into the chat who use another version and don't realize this is the reason why nothing works
- the old readme mentioned recipes, and from my own years ago beginner experience this is quite confusing. recipes are an advanced tool and to a beginner it may not be clear what it is, if e.g. a recipe may be something to build their own app and they need to create one, etc
- the readme also used the word "distribution": similarly nobody knows what that is starting out, so I avoided using it and instead called it building an app, since that is what …

Try to be more clear in README about api levels & quickstart

---

pythonforandroid/build.py
pythonforandroid/pythonpackage.py
pythonforandroid/toolchain.py
tests/test_pythonpackage_basic.py

I made the setup.py processing unintentionally litter a file :grimacing: :grimacing: (in the user project folder of all places) so that's not very good and here's the fix :smile: along with other fixes:
- fix file litter of constraint.txt
- fix --private relative paths during build.py's setup.py install
- fix "" and "." not being recognized as folder by pythonpackage.py
~~Still WIP because I'm still testing it~~ tested with various actual `setup.py`-based builds!

Fix various setup.py processing bugs

---

pythonforandroid/archs.py

The hostpython path that we have doesn't point to the right location (probably was the path for the old python2/python2legacy recipe). As per the current python versions that we maintain, the right path is the one of this pr (inside `native-build` folder)

Fix wrong env variable for `hostpython build path` in `archs.py`

---

pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/python2/patches/fix-ctypes-util-find-library.patch

Adding patch for fixing ctypes-util-find-library issue for python2 support

fix ctypes-util-find-library issue for python2

---

tests/test_bootstrap.py

In this `unittest` we will also cover all the bootstraps we have at this time, so this would increase the coverage a little more than the other tests I recently introduced.
Also should be mentioned that, in order that to not increase the time of our tox tests, I mocked a lot of functions, so this way the test is performed with less than a second and it covers above a 90% of the lines of  the tested files (which I think that should be the final goal for our unittests...above an **90%**)
**As a side note:** I introduced the bootstraps tests in here because our bootstraps (sdl2, webview...)  inherits from `Bootstrap`

Add unittest for module `pythonforandroid.bootstrap`

---

tests/test_build.py

Regression test for the fix introduced in #1898.

Simple run_pymodules_install test, refs #1898

---

pythonforandroid/bootstrap.py
tests/test_bootstrap.py

This should fix `Bootstrap.get_bootstrap_from_recipes()` not being deterministic, which fixes #1875

Fix Bootstrap.get_bootstrap_from_recipes() so it's smarter and deterministic, fixes #1875

---

pythonforandroid/bootstrap.py
tests/test_bootstrap.py

When a pure python package it's supplied inside the dependency list (for the method `expand_dependencies`), we will get a crash because we don't have a recipe for it, unless we contemplate that situation
**Note:** We missed that because we haven't a pure python package in our CI` builds for the [testapps](https://github.com/kivy/python-for-android/blob/develop/.travis.yml#L73-L81)
**As a side note:** The `expand_dependencies` method was recently introduced in PR #1887

Fix crash when guessing Bootstrap (expand_dependencies)

---

Dockerfile.py2
Dockerfile.py3
doc/source/quickstart.rst

Also:
- remove unneeded calls to android's sdkmanager
- remove download of android's platform 19 (because we don't need it)

Docker - Update android's sdk tools to `28.0.2`

---

.gitignore

We can generate some files/folders, under some circumstances, which we don't want that git tracks them, so here we add some entries to `.gitignore`, to make sure that git ignores them:
- files/folders generated by our unit tests
- files/folders generated by our coverage
- folders generated by our testapps (in case that we build some testapp directly from inside the source code folder)
- file `.directory` auto generated by `Dolphin`, the KDE's file manager, when browsing a folder

Feature gitignore additions

---

.gitignore

Because we don't use it (we are using pytest), so better keep it simple
**Note:** this was introduced by mistake in b5d9b611 (#1911), and noticed by @AndreMiras (**thanks** :smile:), unfortunately I saw it once already merged in develop branch, so this PR is to address [this comment](https://github.com/kivy/python-for-android/pull/1911#discussion_r302161021)

Remove `nosetests.xml` from gitignore

---

doc/source/index.rst
doc/source/testing_pull_requests.rst

Due to the **lack of documentation on how to test a pull request**, sometimes we are enforced to fill pull requests with support comments about how to do the testing or we directly don't answer (to not fill the pr with unrelated information), yeah...I'm guilty of that in #1722...sorry :peace_symbol: . So to remediate this issue, I created this pull request to solve this once and for all, but guys, I need your help in here, because each one of us can have his own method, so it would be great to share our testing methods and write them in the docs, for future reference and to redirect users in case that we need to do so with a minimal interference possible for the affected pull request.
I put three methods in the initial documentation, but I need that all of you review this very carefully …

Add documentation: testing a pull request

---

pythonforandroid/recipes/libzmq/__init__.py

- Pyzmq was complaining about libunwind.h not found, so i deactivated it permanently
- CXXFLAGS sysroot was not working for arm64-v8a, it now does.

Fix pyzmq (libunwind and arm64-v8a)

---

pythonforandroid/build.py
tests/test_toolchain.py

First simple set of tests for toolchain.py
Also refactors `Context.prepare_build_environment()` slightly. Splits
concerns to improve readability and ease unit testing.

Basic toolchain.py unit tests

---

pythonforandroid/recommendations.py
tests/test_recommendations.py

In order to avoid issues with old android's NDKs, we force to raise an error in case that an NDK version lower than the specified is detected. We also add the ability to extract the android's NDK letter version, which for now, will only be used to inform the user of the version which is using.
~~**Important note:** **Don't merge this before the ndk-r19 core part I** (we can easily adapt this for ndk-r17 but I leave it to `ndk-19` so we make sure that travis fails as expected), once the Part I gets merged, we can rebase this into develop, push it and the tests should pass **or we could adapt it to ndk-r17 and merge it before**~~
**Note:** The idea to create this pr comes from [this comment](https://github.com/kivy/python-for-android/pull/1722#issuecomment-502844382) from the pull request …

Make it raise an error if an old ndk is used

---

pythonforandroid/toolchain.py
tests/test_toolchain.py

Increases `test_create()` coverage demonstrating crash referenced in:
<https://github.com/kivy/python-for-android/pull/1867#issuecomment-514352035>
Adds `test_recipes()` checking if it prints out without crashing.

Increases toolchain.py test coverage

---

doc/source/contribute.rst

This pull request adds an internal documentation (not build as part of user docs, I just put it in there so we can find it again - it's mainly meant to just sit around in a place where we can find it) describing how p4a interacts with pip & python packages. [This is mainly meant for pip developers and others outside of our team to be able to get an idea what we're doing](https://github.com/kivy/python-for-android/issues/1932), although of course it could also be interesting to newcomers to our own team!
**Please have fun reading and tell me if anything doesn't make sense!**

Add a document describing how p4a interacts with pip & python packages

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/common/build/templates/Service.tmpl.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/templates/Service.tmpl.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/recipes/android/src/android/_android.pyx
pythonforandroid/recipes/android/src/android/_android_jni.c
tests/test_distribution.py

- Adds start_service_not_as_foreground() to avoid always displaying
an associated notification without this being configurable at runtime.
It only is configurable right now if setting the foreground property
via --service, which cannot be done when using the simpler
service/main.py entrypoint
- Fixes service_only service code template not rendering .foreground
correctly since it added an outdated, useless function name override
- Fixes notification channel name which is visible to end user
hardcoding "python" in its name which is not ideal for end user
naming (since the average user might not even know what python is)
- Fixes override of doStartForeground() leading to quite some
error-prone code duplication

Fix foreground notification being mandatory and more (attempt 2)

---

pythonforandroid/recipes/kivy/__init__.py

Kivy master (and future Kivy releases) depends on setuptools now, whereas it didn't before. I think we should just add it to the requirements now, to avoid issues when people try to install from master. It doesn't seem worth messing around with making setuptools a requirement only if Kivy > 1.11 is being targeted.

Added setuptools to Kivy recipe requirements

---

doc/source/apis.rst
pythonforandroid/recipes/android/src/android/storage.py

We just discussed this on discord and the situation with the storage available on Android is a little bit confusing, so I read through the docs a little and wrote an additional storage module to add after #1528 is in. Still untested / to be polished

Add functions for obtaining the default storage paths

---

pythonforandroid/recipe.py
tests/test_recipe.py
tox.ini

Currently unit tests the following:
- `Recipe.download_if_necessary()`
- `Recipe.download()`
Next up is `Recipe.download_file()`. This is more difficult and will be
addressed in subsequent pull request.

Unit tests Recipe download feature

---

Dockerfile.py2
Dockerfile.py3
pythonforandroid/build.py
pythonforandroid/recipe.py
tests/test_toolchain.py

This changes calls to Cython to `python -m Cython` to avoid picking one not matching the current python version (which can happen if just calling `Cython`). This should fix #1885

Call Cython via `python -m Cython` rather than system-wide binary

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/recipes/android/src/android/permissions.py

Currently there is no good way to handle runtime permissions in Android in Kivy (unless I've missed it).
You can already check and request runtime permissions; however, you can't receive the callback onRequestPermissionResult which has to be on the Activity.
A number of changes are made to PythonActivity to allow this callback to be accessed. First an interface PermissionsCallback is defined, allowing PyJnius to be used to build a PythonJavaClass to match. This has a single method onRequestPermissionsResult with arguments which match that of the method on Activity. Instances of matching classes can be registered with PythonActivity using the new method addPermissionsCallback.
Finally the method onRequestPermissionsResult is overridden on PythonActivity. This checks if a PermissionCallback …

feat: Allows registering the onRequestPermissionsResult callback.

---

pythonforandroid/toolchain.py
tests/test_recipe.py

Follow up of #1946.
Increases coverage by testing part of `Recipe.download_file()` handling
https schema. Next up would be to handle more schemas in the tests.
Also addressed @opacam comments from previous pull requests.

Unit tests Recipe.download_file() partly

---

.travis.yml
Dockerfile.py2
Dockerfile.py3
ci/makefiles/android.mk
ci/makefiles/osx.mk
pythonforandroid/python.py
pythonforandroid/recipe.py
pythonforandroid/recipes/python2/__init__.py
pythonforandroid/recipes/python2/patches/fix-interpreter-version.patch

It turns out that the generated binary for `MacOS` and `Cygwin` is not `python`...it's `python.exe`...this leads to not set correctly the `ctx.hostpython` variable for `Mac OS`. This rename of the python binary for  `MacOS` is to, probably,  avoid issues with the  `Mac OS` filesystem which could be Case Insensitive and it would conflict with the build folder named `Python`).
I hope that this solve the `Mac OS` build issue :crossed_fingers:
**Note:** this should be tested by some mac user, unfortunately I could not test it because I don't have a mac...so I recommend to merge after someone test this, but all seems indicate that this is the problem of p4a with Mac OS...thanks to [this comment](https://github.com/kivy/python-for-android/issues/1817#issuecomment-517338012) we got the solution …

 Fix build for case-insensitive FS and add CI test for OSX

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_only/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

This PR introduces a set of options which deal with integration of java/kotlin libraries
- android entrypoint: this option already existed in buildozer but was not implemented in p4a.
this allows to specify a custom class inherited class from org.kivy.android.PythonActivity as entrypoint
- android apptheme: specifies a custom app-theme for the main activity, will be generated into the manifest
- compile-options
- gradle-repository: with this option it is possible to specify additional repositories for the gradle build
- packaging-options: results in packagingOptions in the gradle script, can be necessary to resolve conflicts in java/kotlin packages

customizability

---

pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/recipes/freetype/__init__.py
pythonforandroid/recipes/harfbuzz/__init__.py
pythonforandroid/recipes/jpeg/__init__.py
pythonforandroid/recipes/libcurl/__init__.py
pythonforandroid/recipes/libexpat/__init__.py
pythonforandroid/recipes/libffi/__init__.py
pythonforandroid/recipes/libglob/__init__.py
pythonforandroid/recipes/libglob/glob.patch
pythonforandroid/recipes/libiconv/__init__.py
pythonforandroid/recipes/libogg/__init__.py
pythonforandroid/recipes/libsecp256k1/__init__.py
pythonforandroid/recipes/libshine/__init__.py
pythonforandroid/recipes/libsodium/__init__.py
pythonforandroid/recipes/libx264/__init__.py
pythonforandroid/recipes/libxml2/__init__.py
pythonforandroid/recipes/libxslt/__init__.py
pythonforandroid/recipes/libzbar/__init__.py
pythonforandroid/recipes/openssl/__init__.py
pythonforandroid/recipes/png/__init__.py
tests/test_recipe.py

This PR will introduce a new cls attribute: `built_libraries`.
This `built_libraries` attribute must be a dictionary. The keys are the full library name, e.g.: `libffi.so`. And the values must be the relative path of the library, e.g: `.libs`. So the this cls attribute for libffi recipe it would look like:
```built_libraries = {'libffi.so': '.libs'}```
This new cls attribute will allow us to detect library recipes and to refactor common operations that we do for those kind of recipes:
- copy library into right location
- implement `should_build` for library recipes
Those two things will make that our rebuilds to be more consistent and I hope that it will be easier to maintain. Also I was thinking that it would be great to refactor the build methods that we use in those recipes, but this …

[LIBS - PART I] Initial refactor of library recipes

---

pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/pymunk/__init__.py

Because `--sysroot` flag is not needed anymore and make it fails the build since we migrated to new android's build system (implemented in NDK r19)
BTW, I succesfully build for `armeabi-v7a` and `arm64-v8a` (python3 both tests) and our `CI` test for `rebuild_updated_recipes` seems happy.
See also:
- @AndreMiras's [comment at android'd NDK r19+ migration PR](https://github.com/kivy/python-for-android/pull/1722#issuecomment-524564468) which discovered the `cffi`'s error, **thanks** :smile:!!
- https://developer.android.com/ndk/guides/other_build_systems

Remove `--sysroot` from LDFLAGS for cffi and pymunk

---

pythonforandroid/recipes/libgeos/__init__.py
pythonforandroid/recipes/shapely/__init__.py
pythonforandroid/recipes/shapely/setup.patch

This forms part of the `STL` library refactor (#1947), so depends on it.
In here we do:
- Make libgeos a library recipe (depends on `STL` library):
- Updated version to `3.7.1`
- Make use of CMake for the build
- Make it work shapely with the changes mentioned above and:
- Updated version to `1.7a1`
**Not merge before** #1947

[WIP][LIBS - PART IV] Rework of shapely and libgeos

---

pythonforandroid/recipes/libzmq/__init__.py

This forms part of the `STL` library refactor (#1947), so depends on it.
In here we do:
- Make libzmq a library recipe (depends on `STL` library):
- Updated version to `4.3.2`
**Not merge before** #1947

[WIP][LIBS - PART V] Rework of libzmq

---

pythonforandroid/recipes/boost/__init__.py
pythonforandroid/recipes/boost/fix-android-issues.patch
pythonforandroid/recipes/boost/user-config.jam
pythonforandroid/recipes/libtorrent/__init__.py
pythonforandroid/recipes/libtorrent/setup-lib-name.patch

which:
- fix build for android's NDK r19+
- allow us to build `boost+libtorrent` for any arch
- Update boost to version `1.69.0`
- update libtorrent to version `1.2.1`
The build method needs to be changed because one of the scripts used in `boost+libtorrent` build (make-standalone-toolchain.sh), has been removed from android's NDK. [This is because](https://developer.android.com/ndk/guides/standalone_toolchain):
`As of r19, the NDK's default toolchains are standalone toolchains, which renders this process unnecessary.`
Note: since 3887d2b, `python-for-android` uses android's NDK r19 as the minimum supported and also changed the build method used by p4a as [described in here](https://developer.android.com/ndk/guides/other_build_systems)
This forms part of the `STL` library refactor …

[WIP][LIBS - PART VII] Rework of libtorrent and boost

---

pythonforandroid/bootstraps/common/build/build.py

When using `--use-setup-py` and a `setup.py` instead of `--requirements`, only the `main.py` will currently get copied into the final `.apk` as well as the site packages. That makes using an unnamed service (without `--service`) impossible since `service/main.py` is no longer copied into the `.apk`, and an installed entrypoint via `setup.py` would be in another location.
This commit fixes this by also copying `service/main.py` into the `.apk` when present in addition to `main.py` (while still not copying any other files)

Also copy the service/main.py when building with setup.py

---

ci/constants.py
pythonforandroid/recipes/protobuf_cpp/__init__.py

This forms part of the `STL` library refactor (#1947), so depends on it.
In here we do:
- inherit from `CppCompiledComponentsPythonRecipe` Because depends on android's STL library
- make use of the base class methods for library recipes
- Split build_arch into proper methods
- Shorten some long lines (to be PEP8 friendly)
- make generated library shared
**Not merge before** #1947

[WIP][LIBS - PART VI] Rework of protobuf_cpp

---

pythonforandroid/recipes/jpeg/__init__.py
tests/recipes/recipe_ctx.py
tests/recipes/recipe_lib_test.py
tests/recipes/test_freetype.py
tests/recipes/test_gevent.py
tests/recipes/test_harfbuzz.py
tests/recipes/test_icu.py
tests/recipes/test_jpeg.py
tests/recipes/test_leveldb.py
tests/recipes/test_libcurl.py
tests/recipes/test_libexpat.py
tests/recipes/test_libffi.py
tests/recipes/test_libgeos.py
tests/recipes/test_libiconv.py
tests/recipes/test_libmysqlclient.py
tests/recipes/test_libogg.py
tests/recipes/test_libpq.py
tests/recipes/test_libsecp256k1.py
tests/recipes/test_libshine.py
tests/recipes/test_libvorbis.py
tests/recipes/test_libx264.py
tests/recipes/test_libxml2.py
tests/recipes/test_libxslt.py
tests/recipes/test_openal.py
tests/recipes/test_openssl.py
tests/recipes/test_png.py
tests/recipes/test_pyicu.py
tests/recipes/test_reportlab.py
tests/recipes/test_snappy.py

The main idea is to test as many recipes as we can with the less code possible and without creating any file/directory so our tests can be performed as fast as possible (all this tests will only add between 2 and 3 seconds to our CI tests and will cover almost 100% of the code for each tested recipe)
To do so, we create a couple of modules:
- `tests.recipe_ctx`: allow us to create a proper `Context` to test our recipes
- `tests.recipe_lib_test`: which holds some base classes to be used to test a recipe depending on the build method used. For starters we introduce two kind of base classes:
+ `BaseTestForMakeRecipe`: To test an standard library build (this will iinclude the recipes which requires the classical build commands`configure/make`)
+ `BaseTestForCmakeRecipe`: To test an library …

Proof of concept - A bunch of tests for library recipes

---

tests/recipes/recipe_lib_test.py
tests/recipes/test_gevent.py
tests/recipes/test_icu.py
tests/recipes/test_pyicu.py
tests/recipes/test_reportlab.py
tests/test_archs.py
tests/test_bootstrap.py
tests/test_build.py
tests/test_distribution.py
tests/test_graph.py
tests/test_logger.py
tests/test_pythonpackage_basic.py
tests/test_recipe.py
tests/test_toolchain.py
tests/test_util.py
tox.ini

This is a follow up of #1982
In here we do:
- Move from `__new__` to `__init__` for `BaseTestForMakeRecipe` ([discussed at here](https://github.com/kivy/python-for-android/pull/1982#discussion_r324419892))
- Convert cls attributes to instance attributes ([discussed at here](https://github.com/kivy/python-for-android/pull/1982#discussion_r324419973))
-  Remove `mock` dependency for py3 tests (Because, as per Python 3.3+, `mock` it's a built-in-module). (Unfortunately we still will have a couple of `import mock` entries that we cannot remove until we completely remove python2 from our tests)

Recipes tests enhancements

---

pythonforandroid/bootstrap.py
pythonforandroid/build.py
pythonforandroid/distribution.py
pythonforandroid/python.py
pythonforandroid/toolchain.py
tests/recipes/recipe_ctx.py
tests/test_archs.py
tests/test_bootstrap.py
tests/test_distribution.py

The approach taken here is to specifically *not* change the dist name, which should remain the same as what the user specified, but to use different folders for different arch builds of the same dist.
This is distinct to (say) the NDK API, where we don't allow multiple versions built for the same dist name, because we can expect that multiple archs is a normal thing to want while multiple NDK APIs for the same project is usually a mistake (and if not, can be resolved by specifying different dist names).

Made p4a use per-arch dist build dirs

---

doc/source/troubleshooting.rst

Adds the NoClassDefFoundError XmlSchema case and groups related cases
together. Gives instructions for both Ubuntu and macOS to fix.

Updates Java version troubleshooting

---

pythonforandroid/recipes/libiconv/__init__.py
pythonforandroid/recipes/libzbar/__init__.py

Having `--host=x86` was making the configure script fail at enabling
shared library build on `x86`. This was resulting in failing to copy
`libiconv.so` and `libzbar.so` on `x86` arch.

Fixes libiconv & libzbar configure host

---

testapps/on_device_unit_tests/buildozer.spec

Trivial change, better for development.

Made on-device unit tests app use the develop branch by default

---

pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/numpy/patches/fix-py2-numpy-import.patch

Also:
- make use of python3 `super()` for numpy recipe
Closes: #1988

Fix error on py2  when `import numpy`

---

pythonforandroid/recipes/twisted/__init__.py
pythonforandroid/recipes/twisted/incremental.patch

Last version is building fine with p4a. Also incremental.patch doesn't
seem needed anymore (using Python 3), I could build without it.

twisted: updated to 19.7.0 + removed inceremental.path

---

.env
.travis.yml
Dockerfile.py3
Makefile

Revamping Travis and Docker setup introducing a `Makefile`.
The idea is to move the CI complexity from .travis.yml to `Makefile`.
That makes a single entry point via `make` command and reproducible
builds via Docker.
It makes it easy to run some commands outside docker, such as:
```sh
make testapps/python3/armeabi-v7a
```
Or the same command inside docker:
```sh
make docker/run/make/testapps/python3/armeabi-v7a
```
This pull request also starts introducing some docker layer cache
optimization as needed by #2009 to speed up docker pull/push and
rebuilds from cache.
It also introduces other Docker images good practices like ordering
dependencies alphabetically or always enforcing `apt update` prior
install, refs:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ …

Travis CI revamp part 1, refs #2008

---

Makefile

The error was:
```
Traceback (most recent call last):
File "ci/rebuild_updated_recipes.py", line 112, in <module>
main()
File "ci/rebuild_updated_recipes.py", line 108, in main
build(target_python, recipes)
File "ci/rebuild_updated_recipes.py", line 59, in build
android_sdk_home = os.environ['ANDROID_SDK_HOME']
File "/home/user/app/venv/lib/python3.6/os.py", line 669, in __getitem__
raise KeyError(key) from None
KeyError: 'ANDROID_SDK_HOME'
```
https://travis-ci.org/kivy/python-for-android/jobs/609719811

Exposes ANDROID_SDK_HOME to rebuild_updated_recipes

---

pythonforandroid/recipes/pyproj/__init__.py

bumps pyproj version to 1.9.6 and fixes the source url. Previously the url pointed to the latest pyproj version, which 
1. did not match the recipe version and 
2. seems not to be compatible with `hostpython3`

update pyproj recipe

---

pythonforandroid/recipes/libcurl/__init__.py

Currently (dunno from when, it was working when i added the recipe), the libcurl doesn't use ssl despite the `--with-ssl` option given, because it is not being able to link with libcrypto.
By adding the flags / libs to the environ like others recipes, everything works again.

Fix libcurl with openssl

---

.travis.yml
pythonforandroid/recipes/ffmpeg/__init__.py
pythonforandroid/recipes/ffmpeg/patches/configure.patch
pythonforandroid/recipes/ffpyplayer_codecs/__init__.py

Targets issue #1996 .
Known issues:
- if `libshine` is enabled `libavcodec` is throwing an exception during runtime: `ffpyplayer - ImportError: dlopen failed: cannot locate symbol "shine_set_config_mpeg_defaults" referenced by "/data/app/myapp==/lib/arm/libavcodec.so"..` ( disabled `libshine` as a workaround)
Tested over a `https/hls` stream on both `arm64-v8a` and `armeabi-v7a` .

Fixes ffmpeg build on ndk 19

---

.github/workflows/push.yml
pythonforandroid/recipes/libtorrent/__init__.py
tests/recipes/recipe_lib_test.py
tests/recipes/test_icu.py
tests/test_archs.py
tests/test_bootstrap.py
tests/test_pythonpackage_basic.py
tests/test_recipe.py
tests/test_toolchain.py

**I just want to share some of our travis tests but for `gh-actions`:**
In here we perform the same tox tests that we do in travis but for **linux** and **MacOs** (for **python** versions **3.6** and **3.7**...so we use a matrix) plus an **flake8 test** (which will make stop all the other tests if not succeed). 
Regarding testsapp, we only perform one of the tests (Python3 for arm64-v8a in ubuntu with docker), so we make less tests than travis regarding testapps. The good thing of this is that we run the tox tests in MacOs, which make me notice that we had wrong some of our tests so we solve this in here.
**Why introduce `gh-actions`?**
Well, because it's one more asset that we can use, and this is only one small part of what can be achieved with `gh-actions`. IMHO, I think that we can …

Introduce github-actions (push & pull_requests)

---

pythonforandroid/recipes/ffmpeg/__init__.py
pythonforandroid/recipes/ffpyplayer_codecs/__init__.py
pythonforandroid/recipes/libshine/__init__.py

Since the recent fix for the ffmpeg recipe #1997, we detected that the libshine recipe wasn't working properly at runtime (libavcodec complains about missing symbols), so here we have the fix for that.
In here we:
- build libshine as a shared library
- move to python3's f-strings
- fix LDLIBS/LDFLAGS (which is the main reason of the runtime error described at #1997)
- Re-enable libshine for ffpyplayer_codes and ffmpeg
I tested the build for archs: `armeabi-v7a` and `arm64-v8a`...both builds succeed. Also checked the symbols via command `readelf -a libshine.so` and it seems that the missing func is in there, see 264:
```
....
254: 00003ae5   100 FUNC    GLOBAL DEFAULT   11 shine_check_config
255: 00003ee7    20 FUNC    GLOBAL DEFAULT   11 shine_close
256: 00003d69   184 FUNC    GLOBAL …
```

Fix libshine and re-enable it for ffmpeg & ffpyplayer_codecs

---

testapps/testapp/main.py
testapps/testapp_encryption/main.py
testapps/testapp_flask/main.py
testapps/testapp_keyboard/main.py
testapps/testapp_pillow/main.py
testapps/testapp_sqlite_openssl/main.py

Method `vibrate(milliseconds)` was deprecated in API level 26,
now we should use ` vibrate(android.os.VibrationEffect)`.
I labeled this `WIP` because I thing that we should consider the possibility to use `plyer` instead of using the more low level way of `pyjnius`, because we are repeating the code a lot with all the testapps (except for the flask testapp...which uses the same solution but written slightly differently). But the vibration fix for `plyer` it was merged recently, and we still not have a release with it, so it will force us to put a github requirement in our testapp setup.py files and pin it to a commit or master branch...so...
@inclement and @AndreMiras, what do you think about this, `plyer` or `pyjnius`?
**Note:**
- This solution is based on the kivy/plyer#523 and was …

Fix vibration for testapps

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

The XML is added within the <manifest> tag.
I've always said we should support this, but I couldn't see it in the AndroidManifest.xml as it stands - maybe I'm missing it?
If this sounds good, I'll add it to the other templates as well.

Added a build.py argument to add arbitrary xml to the AndroidManifest.xml

---

.travis.yml
pythonforandroid/recommendations.py
pythonforandroid/toolchain.py
tests/test_recommendations.py

Added this missing command, which existed in the argument parser but wasn't actually implemented.
Not sure what format we really want, but just having the command available is probably an improvement for now.
I thought about removing the argument entirely, but it does seem useful to be able to print the p4a recommendations easily.

Added missing recommendations command and cleaned up code

---

pythonforandroid/recipes/python3/__init__.py

fixed description of patch's name to apply correctly

fixed patch's name to apply correctly

---

pythonforandroid/toolchain.py
tests/test_bootstrap.py

Fixes `p4a bootstrap` command:
```sh
$ p4a bootstraps
Traceback (most recent call last):
File "/home/touilleman/projects/buildozer-test/venv/bin/p4a", line 10, in <module>
sys.exit(main())
File "/home/touilleman/projects/buildozer-test/venv/lib/python3.7/site-packages/pythonforandroid/entrypoints.py", line 18, in main
ToolchainCL()
File "/home/touilleman/projects/buildozer-test/venv/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 671, in __init__
getattr(self, args.subparser_name.replace('-', '_'))(args)
File "/home/touilleman/projects/buildozer-test/venv/lib/python3.7/site-packages/pythonforandroid/toolchain.py", line 788, in bootstraps
for bs in Bootstrap.list_bootstraps():
AttributeError: type object 'Bootstrap' has no attribute 'list_bootstraps'
```

Fix missing renames of Bootstrap.list_bootstraps -> Bootstrap.all_bootstraps

---

.github/workflows/push.yml

To fix gh-actions failures on re-running checks, like the one we have at [here](https://github.com/kivy/python-for-android/runs/464566374?check_suite_focus=true#step:2:246) for #2069

[gh-actions] Move to actions/checkout@v2

---

pythonforandroid/recipes/cppy/__init__.py
pythonforandroid/recipes/kiwisolver/__init__.py

This is the first step that we have to do to fix the `matplotlib` recipe, since it is a direct dependency.
**See also:** #2073 and [this comment](https://github.com/kivy/python-for-android/pull/2073#issuecomment-593102184)

Fix recipe `kiwisolver` (add `cppy` recipe)

---

ci/constants.py
pythonforandroid/recipes/matplotlib/__init__.py
pythonforandroid/recipes/matplotlib/libfreetype.pc.template
pythonforandroid/recipes/matplotlib/libpng.pc.template
pythonforandroid/recipes/matplotlib/mpl_android_fixes.patch
pythonforandroid/recipes/png/__init__.py

This PR depends on a working `kiwisolver` and `cppy` recipes (#2075).
**Closes:** #1900, kivy/buildozer#1003
**Notes:** I will merge the branch of this PR alongside the branch of #2075 into #2073 so we can see if the thing is working with the `on_device_unit_test_app`.
**See also:**
- [this comment](https://github.com/kivy/python-for-android/pull/2073#issuecomment-593102184)
- #1750

Fix `matplotlib` and update to `v3.1.3`

---

pythonforandroid/recipes/python3/__init__.py
pythonforandroid/recipes/python3/patches/py3.8.1_fix_cortex_a8.patch

Because:
- the name does not match the file
- `py3.8.1_fix-cortex-a8.patch` contains unneeded changes which provokes the patching to fail
Also we add a comment to `py3.8.1_fix_cortex_a8.patch` file, explaining why we need that patch (imho, very useful after a while...)
**Note:** The github user @Sanialtian, found this bug and notified me via email...so thanks for your debugging session and the testing!!  :raised_hands:

Fix Python 3.8.1 patch naming and content

---

.travis.yml
Makefile
pythonforandroid/recipes/cython/__init__.py
pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/numpy/patches/add_libm_explicitly_to_build.patch
pythonforandroid/recipes/numpy/patches/do_not_use_system_libs.patch

We add the `cython` recipe because the last version of `numpy` (at time of writing v1.18.1), requires `cython` installed as a Python module during the build stage of the `numpy` recipe.
Also this will make the `numpy` recipe only available for `Python3` since it requires python>=3.5.

Update `numpy` to v1.18.1 (add `cython` recipe)

---

pythonforandroid/archs.py

This commit is extracted from the tests we made at #2073 (commit message slightly modified, not the content) and it seems that solves the build problems detected in there...unfortunatelly I cannot test any `apk` with this fix, but it solves the build problem...so I recommend to merge it :wink:
**See also:**
- https://github.com/kivy/python-for-android/pull/2073#issuecomment-592998163

:bug: Add `-fPIC` to  `CFLAGS` for Arch `x86_64`

---

pythonforandroid/recipes/gevent/__init__.py
tests/recipes/test_gevent.py

Adding `libm.so` to the `arm64-v8a` build fixes undefined reference
errors. The (truncated) config.log errors were:
```
...
libpython3.7m.so: undefined reference to `hypot@LIBC'
libpython3.7m.so: undefined reference to `frexp@LIBC'
libpython3.7m.so: undefined reference to `cos@LIBC'
libpython3.7m.so: undefined reference to `pow@LIBC'
libpython3.7m.so: undefined reference to `atan2@LIBC'
libpython3.7m.so: undefined reference to `modf@LIBC'
libpython3.7m.so: undefined reference to `exp@LIBC'
libpython3.7m.so: undefined reference to `sin@LIBC'
libpython3.7m.so: undefined reference to `log@LIBC'
libpython3.7m.so: undefined reference to `fmod@LIBC'
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
...
```
Refs: …

Fixes gevent recipe on arm64-v8a arch

---

pythonforandroid/recipes/libbz2/__init__.py
pythonforandroid/recipes/libbz2/lib_android.patch
tests/recipes/test_libbz2.py

This is the first part of a set of recipes that will improve our libraries ecosystem, allowing us, in a near future, to build a extra python module: `_bz2.cpython-38.so`, required by some python packages like `pandas`.
**Notes:**
- tested at #2088
- this PR is not enough to build the mentioned python module, this will be done at `Compression libraries - episode III`
- @AndreMiras, I applied [the corrections you made at #2088](https://github.com/kivy/python-for-android/pull/2088#discussion_r394260228), **thanks!!** :smile:

:sparkles: Compression libraries - episode I: libbz2

---

Dockerfile.py3
pythonforandroid/recipes/liblzma/__init__.py
tests/recipes/test_liblzma.py

This is the second part of a set of recipes that will improve our libraries ecosystem, allowing us, in a near future, to build a extra python module: `_lzma.cpython-38.so`, required by some python packages like `pandas`.
**Notes:**
- tested at #2088
- this PR is not enough to build the mentioned python module, this will be done at `Compression libraries - episode III`

:sparkles: Compression libraries - episode II: liblzma

---

pythonforandroid/python.py
pythonforandroid/recipes/python3/__init__.py

This is the third part and last of a set of recipes that will add add support for libbz2 & liblzma to python3 recipe, allowing us to build some extra python modules:
- `_bz2.cpython-38.so`
- `_lzma.cpython-38.so`
Also I put up-to-date the python3 recipe documentation :pencil:
These libraries are required by some python packages, like `pandas`, which I plan to create a PR later :wink:
**Notes:**
- tested at #2088
- **this PR should not be merged before previous PRs, named `Compression libraries...`**: #2095 and #2096

:sparkles: Compression libraries - episode III: add support for libbz2 & liblzma to python3

---

pythonforandroid/recipes/pytz/__init__.py

Because is one of the dependencies of `pandas` recipe #2100,
and despite that the old version seems to work fine,
I think it's better to go for to the latest available version.

:arrow_up: Update `pytz` to version `2019.3`

---

pythonforandroid/recipes/pandas/__init__.py
pythonforandroid/recipes/pandas/fix_numpy_includes.patch
tests/recipes/test_pandas.py

**Notes:**
- tested at #2088
- the version of pandas tested above is not the same the we finally introduced in here, because the last days, the pandas team released a bug fix release, so I updated the version :wink:
- Since the version tested at #2088 is not the same that I put in here, I tested it locally (at build and at runtime) with an updated `pytz` recipe, which I will post later in a separate PR.

:sparkles: Add `pandas` recipe

---

doc/source/quickstart.rst

- orders dependencies bullets alphabetically
- updates Arch Linux dependencies

Updates quickstart.rst "Installing Dependencies"

---

pythonforandroid/recipes/freetype/__init__.py

Tested at runtime with an app of mine for `arm64.v8a` and `Python 3.8.1` (the default for p4a develop branch at the time of writing) using the updated Pillow recipe #2067 alongside an updated `harfbuzz` recipe (which I will publish later in a separate PR)

[recipes] Update freetype & add zlib support

---

pythonforandroid/recipes/harfbuzz/__init__.py

Tested at runtime with an app of mine for `arm64-v8a` and `Python 3.8.1` (the default for p4a develop branch at the time of writing) using the updated Pillow recipe #2067 alongside an updated freetype recipe #2068

[recipes] Update harfbuzz to v2.6.4

---

pythonforandroid/recipes/android/src/android/runnable.py

https://travis-ci.org/github/kivy/python-for-android/jobs/668867999
```
runnable.py:17:1: E302 expected 2 blank lines, found 1
runnable.py:33:1: W293 blank line contains whitespace
runnable.py:45:1: W293 blank line contains whitespace
runnable.py:46:1: W293 blank line contains whitespace
runnable.py:49:1: E303 too many blank lines (4)
runnable.py:53:1: W293 blank line contains whitespace
runnable.py:55:1: W293 blank line contains whitespace
runnable.py:56:32: E261 at least two spaces before inline comment
runnable.py:56:33: E262 inline comment should start with '# '
runnable.py:57:1: W293 blank line contains whitespace
runnable.py:58:45: E231 missing whitespace after ':'
runnable.py:59:1: W293 blank line contains whitespace
runnable.py:61:1: W293 blank line contains whitespace …
```

Fixes linting errors in runnable.py

---

pythonforandroid/archs.py
pythonforandroid/bdistapk.py
pythonforandroid/bootstrap.py
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/build.py
pythonforandroid/distribution.py
pythonforandroid/graph.py
pythonforandroid/logger.py
pythonforandroid/recipe.py
pythonforandroid/recipes/android/__init__.py
pythonforandroid/toolchain.py
pythonforandroid/tools/biglink
pythonforandroid/tools/liblink
pythonforandroid/util.py
tests/test_bootstrap.py

- remove `object` inheritance
- remove `__future__` imports
- remove `six` checks and conditional imports
- flat out a few for loops
- fix `dir` is a reserved keyword
- few more nitpick fixes

Minor fixes and cleanup

---

pythonforandroid/recommendations.py

Probably newer versions are also fine, but making this change in particular because the buildozer download url for 19b no longer exists. I think the 19c one should work fine though.

Update recommended NDK version to 19c

---

pythonforandroid/build.py

If a library is already compiled, skip compilation, but don't skip actually installing the thing.

Install already compiled libraries

---

pythonforandroid/recipes/zeroconf/__init__.py

python-zeroconf bumped to 0.24.5(latest version via pip)
package depends only on 'ifaddr' and 'typing'. Special recipes not required

bump zeroconf version to 0.24.5, fix depends

---

Makefile

Coveralls started failing suddenly in GitHub Actions Worflows.
This feels like a bug on their side (at least their documentation)
because the `CI` environment variable is not supposed to be set refs:
https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
Disabling the `coveralls` conditional run from the `Makefile` fixes it.
It wasn't needed as Travis already calls it explicitly without going
through the `test` target.
Error was:
```
/bin/sh: 1: .tox/py36/bin/coveralls: not found
Makefile:30: recipe for target 'test' failed
make: *** [test] Error 127
```

Fix coveralls error on GitHub Actions

---

pythonforandroid/recipes/cffi/__init__.py

- https://bitbucket.org/cffi/cffi/issues/403/build-fails-on-38-dev-pyinterpreterstate
- https://github.com/kivy/python-for-android/pull/2130#issuecomment-608988477
The error was:
```
c/call_python.c:20:30: error: incomplete definition of type 'struct _is'
```

Bumps cffi==1.13.2 fixes under Python 3.8

---

pythonforandroid/recipes/cryptography/__init__.py

Update the `cryptography` recipe to a newer version, and remove unnecessary dependencies.
- `idna` no longer needed [since version 2.5](https://github.com/pyca/cryptography/blob/e687b8f7f40e30ef88e9de889c55cd7fdec99762/CHANGELOG.rst#25---2019-01-22)
- `asn1crypto` no longer needed [since version 2.8](https://github.com/pyca/cryptography/blob/e687b8f7f40e30ef88e9de889c55cd7fdec99762/CHANGELOG.rst#28---2019-10-16)
- `enum34` is just a backport of python 3.4+ functionality
- `ipaddress` is just a backport of python 3.3+ functionality
(I am assuming py2 and old versions of py3 are no longer supported)

recipe: update 'cryptography' and rm unnecessary dependencies

---

doc/source/testing_pull_requests.rst

- s/codeblock/code-block/
- fixes code block being nested because of previous literal block `::`
See screenshot attached, to the left before the change, to the right after the change:

Fixes code block directives

---

.gitignore
.travis.yml

Uses PyPI `__token__` and Travis auto deployment to publish to PyPI
upon tagging.
https://pypi.org/help/#apitoken
Travis uses the not so well documented `PYPI_PASSWORD` environment
variable to store the password.
https://github.com/travis-ci/dpl/blob/v1.10.15/lib/dpl/provider/pypi.rb#L12
The variable was set with a valid token prior this change.
https://travis-ci.org/github/kivy/python-for-android/settings
This is more secure than user and password as tokens are generated with
uploaded only permissions and can be scoped to a given project.

Auto deploys to PyPI using Travis on tags

---

pythonforandroid/recipes/twisted/__init__.py

Because of a detected vulnerability with prior versions of twisted:
**See also**: https://github.com/advisories/GHSA-h96w-mmrf-2h6v

:lock: Bump twisted version to `20.3.0`

---

.deepsource.toml
MANIFEST.in
pythonforandroid/bootstrap.py
pythonforandroid/build.py
pythonforandroid/recipes/matplotlib/__init__.py
setup.py

- Fix dangerous default argument
- Remove unnecessary comprehension
- Remove unnecessary f-string
---
Find the other issues found here - [https://deepsource.io/gh/pnijhara/python-for-android/issues/?category=all](https://deepsource.io/gh/pnijhara/python-for-android/issues/?category=all)
This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this …

Fix some code quality and bug-risk issues

---

.github/workflows/push.yml
Dockerfile
Makefile
README.md

Simplifies the Dockerfile as Python 2 was dropped.
Renames to default "Dockerfile" so it's picked up by docker hub automatically.
This is a follow-up for: #2105
Adds the GitHub action build badge.
Free up space before building the APKs to avoid the GitHub Action runner being full.
The error was:
```
mkdir -p /home/user/.android/android-ndk-r19b \
&& unzip -q android-ndk-r19b-linux-x86_64.zip -d /home/user/.android \
&& ln -sfn /home/user/.android/android-ndk-r19b /home/user/.android/android-ndk \
&& rm -f android-ndk-r19b-linux-x86_64.zip
Error processing tar file(exit status 1): write /home/user/.android/android-ndk-r19b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/bfd-plugins/LLVMgold.so: no space left on device
Makefile:61: recipe for target 'docker/build' failed …
```

Simplifies Dockerfile and fix GitHub runner space

---

pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https
https://www.google.com/search?q=net%3A%3AERR_CLEARTEXT_NOT_PERMITTED&oq=net%3A%3AERR_CLEARTEXT_NOT_PERMITTED&aqs=chrome..69i57j69i58.788j0j7&sourceid=chrome-mobile&ie=UTF-8
**This is a key update for webview, without it, webview can't work for android 8 and beyond.**

Update AndroidManifest.tmpl.xml to support HTTP

---

pythonforandroid/recipes/twisted/__init__.py
pythonforandroid/recipes/twisted/remove_tests.patch

Update of the recipe for Twisted so that it removes the unit tests in the `prebuild_arch` hook. This should decrease the size from 11 down to 4 MB for the uncompressed APK directory.

Twisted recipe

---

.travis.yml
Dockerfile
Makefile
pythonforandroid/build.py
pythonforandroid/pythonpackage.py
pythonforandroid/util.py
setup.py
tests/test_pythonpackage_basic.py
tests/test_util.py
tox.ini

Here:
- we remove one p4a dependency `virtualenv`
- move from `pytoml` to `toml`, because `pytoml` is [deprecated](https://pypi.org/project/pytoml/)
- remove unneeded code related with virtualenv
**Notes:**
- close #2145

 Use python3's venv instead of virtualenv

---

pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

This is a port of the SDL bootstrap's UnpackTask fix to the webview bootstrap, so that the loading screen can be displayed during unpack instead of a plain black window.

Show loading screen while unpacking for webview bootstrap

---

setup.py
tox.ini

- F401 'os' imported but unused
- E303 too many blank lines (3)
- E302 expected 2 blank lines, found 1
- E305 expected 2 blank lines after class or function definition, found 1
- E251 unexpected spaces around keyword / parameter equals

:rotating light: Fix linting for setup.py

---

pythonforandroid/build.py

It looks like the `_env` keyword argument is acception dictionary only.
The error was:
```
TypeError: Invalid special arguments:
'env': env must be a dict. Got environ(...)
```
https://travis-ci.org/github/AndreMiras/python-for-android/jobs/680502683

Fixes sh `_env` should be a dictionary

---

.travis.yml
Makefile
pythonforandroid/recipes/hostpython3/__init__.py
pythonforandroid/recipes/hostpython3/patches/pyconfig_detection.patch
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/recipes/python3/patches/pyconfig_detection.patch

Running the freshly compiled host python binary from another Python
process (e.g. sh module or os.system()) may get wrongly detected as
if it was ran directly from the venv.
This happens when `pyvenv.cfg` is present (e.g. venv/pyvenv.cfg).
It makes `sysconfig.is_python_build()` returns `False` instead of `True`
since it's using the compiled interpreter (e.g. ./build-dir/python).
https://docs.python.org/3/library/sysconfig.html#sysconfig.is_python_build
https://github.com/python/cpython/blob/v3.8.2/Lib/sysconfig.py#L127
This is because the `sys._home` attribute is used during the detection.
The issue was first seen in macOS venv which generates the `pyvenv.cfg`.
To compare both behaviours, try the following within and without a venv:
```python
import os
os.system("./build-dir/python -E -c …
```

Fixes hostpython build with macOS venv

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

I had trouble making the file patterns work using `include` (no errors, but files didn't get included). However, this approach works for specifying source directories, which was our use case. Figured I'd post what we have now and see if anyone knows how to fix the patterns case, or knows if that case is used often?

Get --add-source working for dirs in Gradle builds

---

doc/source/quickstart.rst
doc/source/troubleshooting.rst

Also removes deprecated error troubleshooting targeting Python 2.

Adds macOS install instructions

---

pythonforandroid/recipes/pygame/__init__.py

Edit: this authored by @robertpfeiffer I've just copy/pasted his description in the commit message, rebased and made few edits to give an example of what the PR could look like.
As discussed on the Discord, this is a recipe to build apps based on
SDL2-based pygame.
It currently references https://github.com/pygame/pygame/tree/android,
a branch that will continue to live until we have an official stable
release of pygame based on SDL2 with android support.
Simple examples have been tested by other pygame users (it doesn't just
build on my own machine) but some pygame functionality is still untested,
and some dependencies like freetype, postmidi and libjpeg are currently
not part of the build. It's usable, but not complete.

Adds pygame recipe

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch
pythonforandroid/recipes/sdl2/__init__.py

Actually simply reverted few files:
```sh
git checkout master -- \
pythonforandroid/recipes/sdl2/__init__.py \
pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch \
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
```
- fixes #2167
- fixes #2169

Downgrades to SDL2 2.0.9

---

pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/recipes/hostpython3/__init__.py
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/toolchain.py

Tries to keep the `current_directory` context manager as scoped as
possible. Also use the `contextlib.suppress` context manager when
appropriated as it's more concise.

Narrows some context manager scopes

---

testapps/on_device_unit_tests/test_app/main.py

See adb logcat trace after the fix:
```
Android kivy bootstrap done. __name__ is __main__
AND: Ran string
Run user program, change dir and execute entrypoint
Imported unittest
App requirements are:  {'sqlite3', 'python3', 'openssl', 'requests', 'pyjnius', 'libffi'}
Defined test case
Adding Testcase:  tests.test_requirements.Sqlite3TestCase
Adding Testcase:  tests.test_requirements.OpensslTestCase
Adding Testcase:  tests.test_requirements.RequestsTestCase
Adding Testcase:  tests.test_requirements.PyjniusTestCase
Adding Testcase:  tests.test_requirements.LibffiTestCase
Tests to perform are:  {'sqlite3': 'tests.test_requirements.Sqlite3TestCase', 'openssl': 'tests.test_requirements.OpensslTestCase', 'requests': 'tests.test_requirements.RequestsTestCase', 'pyjnius': …
```

Fixes service only unittest loading

---

doc/source/contribute.rst

- Links both Travis and GitHub CI build systems
- Updates the PyPI release process (handled by the CI)

Updates release documentation

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/bootstraps/common/build/src/main/java/org/renpy/android/AssetExtract.java
pythonforandroid/bootstraps/common/build/src/main/java/org/renpy/android/Hardware.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/launcher/ProjectAdapter.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/launcher/ProjectChooser.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

- Avoid duplicate imports
- Avoid importing anything from the package java.lang
- Avoid unused imports
- Avoid unused local variables
- Avoid unused private fields
- No need to import a type that lives in the same package
- Unnecessary use of fully qualified name due to existing import
In the future we may want to add a dedicated Java linting job in the CI.

Java code linting using PMD 6.23.0

---

pythonforandroid/archs.py
pythonforandroid/graph.py
pythonforandroid/logger.py
pythonforandroid/pythonpackage.py
pythonforandroid/recipes/android/src/android/_ctypes_library_finder.py
pythonforandroid/recipes/reportlab/__init__.py
pythonforandroid/toolchain.py

The recent `flake8==3.8.0` update reported new errors:
```
pythonforandroid/graph.py:133:27: E741 ambiguous variable name 'l'
pythonforandroid/toolchain.py:219:25: E741 ambiguous variable name 'l'
pythonforandroid/toolchain.py:1146:19: F522 '...'.format(...) has unused named argument(s): Fore
pythonforandroid/pythonpackage.py:690:23: F523 '...'.format(...) has unused arguments at position(s): 0
pythonforandroid/logger.py:202:36: E741 ambiguous variable name 'l'
pythonforandroid/logger.py:204:36: E741 ambiguous variable name 'l'
pythonforandroid/archs.py:150:25: E741 ambiguous variable name 'l'
pythonforandroid/recipes/android/src/android/_ctypes_library_finder.py:56:27: E741 ambiguous variable name 'l'
pythonforandroid/recipes/reportlab/__init__.py:25:21: E741 ambiguous variable name 'l' …
```

:bug: Fixes flake8 errors post update

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonActivityUtil.java
pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonService.java
pythonforandroid/bootstraps/common/build/src/main/java/org/renpy/android/AssetExtract.java
pythonforandroid/bootstraps/common/build/src/main/java/org/renpy/android/Hardware.java
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

This helper class shares code to be reused between the `PythonActivity`
classes of the different bootstraps.
Also adds few minor adjustments to existing classes.

PythonActivityUtil helper for unpacking data

---

pythonforandroid/recipes/python3/__init__.py
tests/recipes/test_python3.py

This covers an **84%** of the python recipe.
Most of the uncovered code is related with `set_lib_flags` (marked with a `todo` inline comment).
I think that is better to deal with it later, since it may require to touch python3's recipe (again)...also it crossed to my mind that maybe we should reduce a little the complexity of that part...I'm still not sure...

:white_check_mark: Add initial tests for python3 recipe

---

pythonforandroid/recipes/python3/__init__.py
tests/recipes/test_python3.py

Because, I forgot to implement it when I first wrote the test at 535b39d6
**Note:** I replaced `os.path.isfile` by `pathlib.Path(<any-path>).is_file()` because:
- It seems that when trying to mock `isfile` function, doesn't work as expected (is completely ignored, unless we import the whole `os.path` module)
- Given the above situation, we must modify the import, so better use the `pathlib` implementation, wich it has several advantages (it handles any kind of path automatically, no matter the platform)

:ambulance: Fix `test_should_build`

---

pythonforandroid/recipes/psycopg2/__init__.py

Added setuptools as a dependency for psycopg2. This fixed the 'ImportError: No module named setuptools' error I encountered while building the package with buildozer.

Fix for 'ImportError: No module named setuptools', encountered when building with buildozer

---

pythonforandroid/recipes/hostpython3/__init__.py
tests/recipes/test_hostpython3.py

This will cover **100%** of the code for the hostpython3 recipe.
Also we migrate `os.path.exists` and `os.path.isfile` to `pathlib.Path`'s implementation because when we mock these functions, it seems that property `return_value` is being ignored.

:white_check_mark: Add tests for hostpython3 recipe

---

doc/source/troubleshooting.rst

Documents how to fix the following error:
```
SSLError("Can't connect to HTTPS URL because the SSL module is not available.")
```

:books: Troubleshoot SSL error

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/__init__.py
pythonforandroid/bootstraps/service_library/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_only/__init__.py
pythonforandroid/bootstraps/service_only/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/__init__.py
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/build.py
pythonforandroid/recipe.py
pythonforandroid/toolchain.py
tests/test_build.py

If we want to **keep** debug symbols from `.so` files we will use: `--with-debug-symbols`
Also:
- enable debug builds for all bootstraps (AndroidManifest.tmpl.xml)
- add log message to make it clear what kind of build we will get
This closes #2207

:package: Split logic for build modes & debug symbols

---

Makefile
pythonforandroid/recipes/opencv/__init__.py
pythonforandroid/recipes/opencv_extras/__init__.py

This recipe allows us to build extra modules from the `opencv_contrib` repository. It depends on `opencv` recipe and all the build of the modules will be performed inside opencv build directory.
This closes #2206
**Note:** I've not tested this recipe at runtime but it builds fine for `arm64-v8a` in my local tests, plus generates the extra opencv libraries (which are a lot so probably will increase the size of the apk considerably).
**See also:** https://github.com/opencv/opencv_contrib

:sparkles: Add `opencv_extras` recipe

---

doc/source/quickstart.rst
doc/source/troubleshooting.rst

Followed the docs as I was building a project from a fresh macOS install.

:pencil: Updates install and troubleshooting docs

---

pythonforandroid/bootstraps/common/build/gradle/wrapper/gradle-wrapper.properties

Gradle 6 supports OpenJDK up to version 13.
Also refs: https://github.com/kivy/buildozer/pull/1135

:arrow_up: Bumps to Gradle 6.4.1

---

Makefile
doc/source/troubleshooting.rst
testapps/on_device_unit_tests/setup.py

The `requests` module has `urllib3`, `chardet` and `idna` as dependencies.
This used to be handled dynamically thanks to the `requests` recipe.
This is a drawback and side effect of #2202.
The on device error was:
```
Imported unittest
loading tests...
running unittest...
unittest result is:
....EE........
======================================================================
ERROR: test_import_module (tests.test_requirements.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/user/app/testapps/on_device_unit_tests/build/bdist.android-armeabi-v7a/test_app/tests/mixin.py", line 17, in test_import_module
File "/home/user/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/pyt …
```

:bug: Adds missing requests sub dependencies

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java

issue: #2228 
description: `added missing import  for "DialogInterface", "AlertDialog" and "KeyEvent". `
cc: @AndreMiras

Fixed KeyError not found

---

pythonforandroid/recipe.py
pythonforandroid/toolchain.py
pythonforandroid/util.py

Fixes running `tox` outputs warnings:
- replaces the `imp` module by the `importlib` one
- simplifies downloader dropping `FancyURLopener`
The warnings were:
```
pythonforandroid/util.py:17
/home/andre/workspace/python-for-android/pythonforandroid/util.py:17:
DeprecationWarning: WgetDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
urlretrieve = WgetDownloader().retrieve
pythonforandroid/toolchain.py:84
/home/andre/workspace/python-for-android/pythonforandroid/toolchain.py:84:
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
```

:rotating_light: Depreciation warning fixes

---

Dockerfile
Makefile
ci/makefiles/android.mk
ci/makefiles/osx.mk
doc/source/troubleshooting.rst

- bumps CI build to OpenJDK 13
- bumps Android SDK Build-Tools to 29.0.3
- unpins Cython as it currently works with latest versions
- cleans troubleshooting documentation

:arrow_up: Bumps to OpenJDK 13

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

The error was:
```
Listing '/home/user/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/webview_includes'...
[INFO]:    Detected highest available build tools version to be 28.0.2
[DEBUG]:   -> running gradlew assembleDebug
[DEBUG]:        Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:
[DEBUG]:        > Task :compileDebugJavaWithJavac FAILED
[DEBUG]:        /home/user/.local/share/python-for-android/dists/unnamed_dist_1__armeabi-v7a/src/main/java/org/kivy/android/PythonActivity.java:245: error: cannot find symbol
[DEBUG]:            public boolean onKeyDown(int keyCode, KeyEvent event) {
[DEBUG]:                                                  ^
[DEBUG]:          symbol:   class KeyEvent
[DEBUG]: …
```

:bug: Fixes service_only and webview symbol errors, closes #2228

---

.travis.yml

This is a follow up for previous migration that was missing the Travis update,
refs #2231

:green_heart: Fixes Travis build post OpenJDK bump

---

pythonforandroid/recipes/libpq/__init__.py

Since buildozer bumped ubuntu versions for their docker image to ubuntu 20.04, the version in the recipe of libpq does not follow the one privided by that distro.
Bumping the version of libpq to follow the one provided by ubuntu 20.04, which is postgresql 10.12, is the easiest way to be able to compile this library on that docker image.
The addition of the environment variable `USE_DEV_URANDOM` prevents the `./configure` stage to look for the file `/dev/urandom` while cross compiling.

Bump libpq version

---

pythonforandroid/recipes/libpq/__init__.py
pythonforandroid/recipes/psycopg2/__init__.py

I inadvertently introduced a runtime error in #2245.
For some reason psycopg2 2.8.4 has a linking issue to PQencryptPasswordConn. This seems to have been fixed with 2.8.5 on my machine. So a simple revision bump should be fine.

Fix runtime psycopg2 error

---

pythonforandroid/build.py
pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/android/_android.pyx
pythonforandroid/recipes/android/src/android/activity.py
pythonforandroid/recipes/android/src/android/broadcast.py
pythonforandroid/recipes/android/src/android/loadingscreen.py
pythonforandroid/recipes/android/src/android/permissions.py
pythonforandroid/recipes/android/src/android/runnable.py
pythonforandroid/recipes/android/src/android/storage.py
pythonforandroid/toolchain.py
tests/test_toolchain.py

to make possible to use custom PythonActivity java class

added --activity-class-name and --activity-package parameters 

---

pythonforandroid/recipes/kivy3/__init__.py

Adding the _kivy3_ module in the requirements in  .spec file results to the installation of the module via pip during the debug process. However, the **default.glsl** file is not copied to the python-installs directory along with the rest of the files and, subsequently to the distributions folder. This recipe remedies the issue.
I created this pull-request following @inclement 's advice on discord. Thanks.

Add Recipe for Kivy3 module 

---

pythonforandroid/recipes/python3/__init__.py

I assume most users don't need this (unlike me), but I don't really see any downsides to having it enabled by default.

build python3 with loadable-sqlite-extensions

---

pythonforandroid/recipes/hostpython3/__init__.py
pythonforandroid/recipes/python3/__init__.py

Fixes the osx build.
The patch in #2159 was only applied for < 3.8.3, but the problem still exists with 3.8.5.

(host)python3: rm version check for pyconfig patch

---

pythonforandroid/recipe.py
tests/test_recipe.py

I was trying to fix the travis osx build, but the download failure seems to have been replaced by a different problem :(
Might still be a useful modification though.

download_file: show error + exponential sleep

---

doc/source/buildoptions.rst
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle
pythonforandroid/bootstraps/common/build/templates/lottie.xml
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java

- add `--presplash-lottie` option to `build` command allowing to pass a
json file
- add lottie to build.gradle if necessary
- use an xml layout file to define the view (added/removed appropriately
by build.py)
- rework PythonActivity to select appropriate view at startup
https://youtu.be/tYvRQA9m6Do

Allow using lottie files for splashscreen (SDL2 bootstrap)

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

Support for native services

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

This PR implements the `manifestPlaceholders` usage as described here: https://developer.android.com/studio/build/manifest-build-variables

Add manifestPlaceholders

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java

Refactor out the function to set the background color of a view, and
calling it on the created view before returning it.

Allow using background color with lottie splashscreen

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_only/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

This PR enables users to pass a new argument to p4a to enable
custom backup rules through the means of an XML file as documented
in the official [Android docs](https://developer.android.com/guide/topics/data/autobackup#IncludingFiles).
I also noticed that the "allowBackup" flag would do nothing when userd
with either `webview` or `service_only` bootstraps, where the 
`AndroidManifest.tmpl.xml` would set it to a hardcoded "true" instead of 
the user-defined value.

Add possibility to add a backup rules xml file

---

pythonforandroid/recipe.py

As per #2311, the. running `python -m Cython.Build.Cythonize` is **not** the same thing as running `cython`

Call cython via the setuptools entrypoint, fixes #2311

---

pythonforandroid/recipes/reportlab/__init__.py

Fix issue #2310 
Because Reportlab bitbucket link doesn't work anymore, I have update the link from Reporlab source.

Update __init__.py for Report Lab recipe

---

pythonforandroid/recipe.py

This adds support for all the hash fragment types pypi may use: https://pip.pypa.io/en/stable/reference/pip_install/#hashes-from-pypi .
Allowing cryptographically secure hashes can help system administrators defend against compromise.
Documentation is only added for sha512sum and blake2bsum to maintain backwards compatibility in the interface and stay somewhat concise.  These two algorithms are rated highly.

added missing digest support to recipes

---

pythonforandroid/recipes/ffmpeg/__init__.py
pythonforandroid/recipes/ffmpeg/patches/configure.patch
pythonforandroid/recipes/ffpyplayer/__init__.py

Update versions of ffmpeg and ffpyplayer recipes.
Do not enable building of GPL components if not necessary.
Add support for x86 build in ffmpeg recipe

ffmpeg and ffpyplayer improvements

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

Merge master into develop, to pull in the couple of PRs that have been made straight to master.
I know it's easy to miss, but PRs should go to develop. Not sure if we can protect master more, maybe non-core-devs can be blocked from making PRs to master.

Fix master only merges

---

doc/source/troubleshooting.rst

There is a small typo in doc/source/troubleshooting.rst.
Should read `packaged` rather than `pacakged`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, pacakged -> packaged

---

.github/workflows/push.yml
.travis.yml

Travis error was:
```
pyenv: pip3.7: command not found
```
Also bumps `actions/setup-python` to latest tag.
Hopefully fixes recent `set-env` and `add-path` commands depreciation.
The error is:
```
Error: Unable to process command
'##[set-env name=pythonLocation;]/opt/hostedtoolcache/Python/3.7.9/x64' successfully.
Error: The `set-env` command is disabled.
Please upgrade to using Environment Files or opt into unsecure command execution by
setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

:bug: Fixes pip command on Travis and bumps actions/setup-python

---

pythonforandroid/recipes/audiostream/__init__.py

This is an attempt to fix https://github.com/kivy/audiostream/issues/25 .  Previously using audiostream caused a crash when loading.
It looks like audiostream hasn't been maintained much.  Is it still the best route for accessing audio in a platform independent way on kivy?
EDIT: it looks like a commit from master got into my PR because it's missing from develop; I'm thinking you probably want that on the develop branch too.

Audiostream Fix

---

doc/source/services.rst

Since this seems to be where the background service documentation is, I wanted to add how to set them up in buildozer.

Add service information for buildozer.spec

---

pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/recipes/android/__init__.py
pythonforandroid/recipes/android/src/setup.py

Fixes #2325.
* This fixes the dlopen error (and allows use of the `android` module).
* `request_permissions` seems to work ~~(w/ pyjnius 1.2.1 [but not yet with 1.3.0](kivy/pyjnius#538))~~.
* For now I copy-pasted the permissions stuff from the sdl2 bootstrap. I'd prefer refactoring that into a common base class, but I'd require some maintainer input on how they prefer to do that :)

fix webview jni

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/recipe.py
pythonforandroid/recipes/boost/__init__.py
pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/opencv/__init__.py
pythonforandroid/recipes/python3/__init__.py
tests/recipes/test_python3.py

Hi,
I'm helping a user to diagnose a downstream issue https://github.com/PyO3/pyo3/issues/1077 when compiling a Rust application using p4a. In the linked issue is a lot of background and the OP also contains a link to a minimal example.
Their build with p4a targeting Python 3.8 was failing with link errors. Their workaround was to manually link to `libpython3.8m.so`.
However, I understood the `m` suffix was removed with Python 3.8 after pymalloc builds became ABI-compatible with the mainline: https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes
So I think that `libpython3.8m.so` is a non-standard name for libpython, and propose here the `m` suffix is dropped by p4a.
I am very new to the p4a codebase, so please give me a heads-up for any other sections of the code that …

`libpython3.8m.so` should not have `m` suffix

---

pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

Description of changes:
* 3.1.4 seems to be pretty outdated and also has some issues with Firebase, 3.5.2 works quite well.
* Got rid of deprecated `compile` method. Replaced them with `implementation`.
<del>* Added extra `classpath` and `apply plugin` as they're required to use firebase(Instead of hardcoding these in the build.gradle file, there could be options to add extra `classpath` and `apply plugin` as per one's requirement).</del> (Because Google services plugin requires a google-services.json file so this plugin must only be added if requires)

Updated gradle plugin version

---

pythonforandroid/recipe.py

When using e.g. a `git+https` url and a `version` that refers to a tag (not a branch), p4a fails when the repo has already been cloned b/c it tries to run `git pull` (which requires a branch and fails with a detached HEAD). This fixes that.

don't run git pull when not on a branch

---

pythonforandroid/recipes/pymunk/__init__.py

Seems to be required to link -lm on at least 5.1, but not on 8.0.
Should fix #2388

Fix Pymunk crash on older versions of Android

---

pythonforandroid/logger.py

Print  contents of `_env` when recipe fails and `P4A_FULL_DEBUG` is set.  Printed `export` commands allow for recreation of recipe's build enviroment and faster iteration when developing complex recipes. This acts as a poor man's substitute for the analogous [devshell](https://embeddeduse.com/2018/10/13/building-yocto-packages-manually-with-devshell/) feature in OpenEmbedded.

recipes: print recipe ENV on failure

---

pythonforandroid/recipes/pyzmq/__init__.py

It seems to be no longer automagically available at this build stage (maybe some order of operations got changed)

PyZQM recipe needs setuptools, list it explicitly in deps

---

pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch

This PR added ability to set input type for keyboard on android. It needs to be merged with https://github.com/kivy/kivy/pull/7231
this is just a new PR with a successful rebase so the CI builds. 
closes #2361

Added ability to set input type on android

---

pythonforandroid/recipe.py

set urllib user-agent

---

pythonforandroid/recipes/Pillow/__init__.py

Fix this bug `ImportError: dlopen failed: cannot locate symbol "modf"`
https://github.com/kivy/buildozer/issues/1020

Fix ImportError bug: cannot locate symbol "modf"

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

This prevents a "permission denied" error w/ sdk 30.

webview: put webview_includes in assets dir

---

Dockerfile
pythonforandroid/recipes/opencv/__init__.py
pythonforandroid/recipes/opencv_extras/__init__.py

Allows build with docker container. Without this changes, I could not build opencv with p4a.

Avoids build error for opencv and bumps version to 4.5.1

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

see https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
This adds a `--icon-fg` and a `--icon-bg` build option to the sdl2 bootstrap,
that can be used to specify two PNG files to be used as the foreground and background
of an adaptive icon. These will get used if API 26+ is available at runtime.
The existing `--icon` option to specify an icon as a single PNG file is kept, as
- this provides backwards compatibility,
- and even if the new options are used, it might be a good idea to set all three
options: when running on API <26, the PNG specified via `--icon` gets used.

android: add support for adaptive icon/launcher

---

pythonforandroid/recipe.py

liblzma was no longer loaded correctly. redirection not considered.

fixed redirection for download liblzma

---

pythonforandroid/recipes/Pillow/__init__.py

https://github.com/kivy/buildozer/issues/1020
I have put requirements=pillow directly without any modification
.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/init.py
Results
In Android 8 running well without any problem
In Android 5 crashing
ImportError: dlopen failed: cannot locate symbol "log" referenced by "_imaging.so"...
and after the change ,In both device running well.
env['CFLAGS'] += cflags + " -lm"

Adds libm to Pillow recipe

---

pythonforandroid/recipes/pygame/__init__.py

Changed the version of pygame in the recipe from 2.0.0-dev (released in Feb 2020) to the latest release 2.0.1 (released in Dec 2021).
Version 2.0.0-dev had the tag name as `android` ; due to which changing the version number via setup.py/cli fails.
This issue is also resolved by this PR.

Updated version of pygame from 2.0.0-dev7 to 2.0.1

---

MANIFEST.in
setup.py

In this https://github.com/kivy/python-for-android/pull/2436 diff files where added to the package_data in setup.py. However, that is not enough. This PR adds the *.diff pattern to a couple of more places needed.

Add *.diff to manifest and package_data

---

pythonforandroid/recipes/pydantic/__init__.py

My Kivy application is using pydantic to handle dataclasses and enforcing strong typing.
I am trying to create a recipe for it. I would really appreciate some help on this.
Is anything wrong?
```python
from pythonforandroid.recipe import PythonRecipe
class PydanticRecipe(PythonRecipe):
version = '1.8.2'
url = 'https://github.com/samuelcolvin/pydantic.git'
depends = ['setuptools']
python_depends = ['Cython==0.29.23', 'devtools==0.6.1', 'email-validator==1.1.2','dataclasses==0.6', 'typing-extensions==3.10.0.0', 'python-dotenv==0.17.1']
call_hostpython_via_targetpython = False
recipe = PydanticRecipe()
```

Recipe for pydantic

---

doc/source/ext/sphinx_rtd_theme/package.json

The `python-for-android` repo is currently red-flagged for a security vulnerability. This PR updates grunt according to the dependabot guidelines.

Upgrade grunt version re: CVE-2020-7729

---

.coveragerc
.github/workflows/push.yml

Coveralls reports are now currently broken due to travis-ci.org shut down.
This PR sends coveralls reports via Github actions.

Move coveralls to github actions

---

.github/workflows/push.yml

This PR fixes a wrong `actions/checkout@v2` usage, that was preventing `Test updated recipes` test to work as expected.
`fetch-depth: 0` should work for our scope, even if it forces us to fetch history for all tags and branches.
See https://github.com/actions/checkout/pull/155 and https://github.com/actions/checkout/issues/214 for additional info.

GitHub Actions: Fixes wrong actions/checkout@v2 usage

---

pythonforandroid/recipes/pygame/__init__.py

Changed the version of pygame in the recipe from 2.0.1 (released in Dec 2020) to the latest release 2.1.0 (released in Nov 2021).

Updated version of pygame from 2.0.1 to 2.1.0

---

.github/workflows/push.yml

This PR updates the python versions matrix used on the CI
`Python 3.6` reached EOL on 23 Dec 2021.

Update python versions matrix on CI

---

pythonforandroid/recipe.py

refactoring code with For Else which is more pythonic, concise and efficient; how do you think this change which has practical value？

refactoring code with For Else

---

pythonforandroid/recipes/pybind11/__init__.py
pythonforandroid/recipes/tflite-runtime/CMakeLists.patch
pythonforandroid/recipes/tflite-runtime/__init__.py
pythonforandroid/recipes/tflite-runtime/build_with_cmake.patch

Also includes pybind11 recipe.
An example using this recipe and some documentation is here: https://github.com/Android-for-Python/c4k_tflite_example , this link also referenced in `tflite-runtime/__init__.py`
This recipe does not build on x86_64 so in this case the build runs but creates nothing, enabling ci testing (I hope). This is documented in  `tflite-runtime/__init__.py` . Though this is not ideal,  it is solely an emulator case and x86 is presumably a substitute.
The platform build dependency occurs because tflite implementation varies by platform. So a "tflite python api" for x86_64 may compile for some platform, but not another. The Android platform "tflite python api" depends on the RUY matrix multiplication library which does not currently compile for x86_64.

tflite-runtime recipe

---

pythonforandroid/recipes/flask/__init__.py

The depencies of flask on itsdangerous and itsdangerous is unable to find the name json hence the application fails to start with the following exception.
ImportError: cannot import name 'json' from itsdangerous
This issue needs to fixed by upgrading the version of the flask the recipie.
I have tested with the modified reciepe with the latest version of flask and found that application works after the fix.

Upgrading the flask version to avoid exception at the start of webview application

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java

add version check to unpackPyBundle

---

.github/workflows/push.yml
ci/osx_ci.sh

- Fixes issue #2569 
- macOS builds are expected to fail ( `hostpython3`, `python3` and `numpy` builds are failing on macOS >= 11) https://github.com/kivy/python-for-android/pull/2566 should fix `python3` and `hostpython3`, but `numpy` needs to be updated accordingly.
- Builds on Apple Silicon are expected to fail until #2550 is ready and merged)
- On macOS (Github hosted) runners `ANDROID_*` env vars override is needed as are already defined https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#environment-variables-2 (Could be interesting to use the runner-environment contained version when we will migrate to a recent version of the NDK).

macOS CI: ADD APK, AAB & Updated Recipes build

---

pythonforandroid/archs.py
pythonforandroid/recipes/libffi/__init__.py

- Bumps `libffi` from `v3.3` to `v3.4.2` ( `v3.3` was failing to build via Android-LLVM on macOS as `-flto` flag is present in `CFLAGS` by default (See: libffi/pull/590)
- Added missing `-fPIC` to `Archx86` (i686-linux-android)
~~⚠️ Do not merge it yet as it needs some tests during runtime.~~
✅  Tests passed during runtime on `on_device_unit_tests` (On a `arm64-v8a` device)

Bumps libffi to v3.4.2 + adds -fPIC on i686-linux-android

---

.github/workflows/push.yml

Like `ubuntu_rebuild_updated_recipes`, `macos_rebuild_updated_recipes` step `Checkout python-for-android` needs `fetch-depth: 0` in order to successfully process changes that have been made to recipes.

Add missing fetch-depth: 0 on macos_rebuild_updated_recipes

---

.github/workflows/push.yml

- Fixes a typo introduced in https://github.com/kivy/python-for-android/pull/2574

Fixes a typo in macos_rebuild_updated_recipes

---

.github/workflows/push.yml

These changes allows us to test the artefacts produced from `ubuntu-latest`, `macos-latest` and `apple-silicon-m1`.
Builds made on different platforms may lead to a different result. (As an example, `numpy` seems to pass during build-time on `macos-latest`, but later it fails during on-device tests).

Upload artifacts produced from every build platform, not only ubuntu-latest

---

pythonforandroid/build.py
tests/test_build.py
tests/test_recipe.py

This is a regression from f7f8cea636714dc4843b8818c553510f99084b6a.
Previously, `self.sdk_dir` and `self.ndk_dir` were passed to
`select_and_check_toolchain_version`.

Set PATH using real SDK and NDK directories

---

pythonforandroid/recipes/py3dns/__init__.py
pythonforandroid/recipes/py3dns/patches/android.patch

I found an error in the `py3dns` module for android. And since this library is not on github and it has not been updated for more than 3 years, I decided to copy the library to my repository and fix the bug by adding a patch. This is a fairly popular library, used as a dependency for `validate_email`.
```py
from kivy.app import App
from kivy.uix.button import Button
import DNS
import smtplib
class TestApp(App):
def build(self):
return Button(text='Get DNS',
on_release=lambda *args: print(self.get_dns_host('gmail.com')),
)
@staticmethod
def get_dns_host(hostname: str, timeout=5):
valid_host = None
try:
DNS.DiscoverNameServers()
mx_hosts = DNS.mxlookup(hostname, timeout)
for mx in mx_hosts:
smtp = smtplib.SMTP()
try:
smtp.connect(mx[1])
except smtplib.SMTPConnectError:
continue  # try the …
```

Added py3dns recipe

---

.github/workflows/push.yml
Makefile
ci/rebuild_updated_recipes.py

✂️ (Partially) from #2586 
- `rebuild_updated_recipes.py` now accepts (multiple) `--arch ...` parameters so can build the updated recipes againist the selected archs.
- CI jobs for `*_rebuild_updated_recipes` (that run on `ubuntu-latest`, `macos-latest`, `apple-silicon-m1`) now are configured to run for each of the supported archs (`x86`, `x86_64`, `arm64-v8a`, `armeabi-v7a`).
- `continue-on-error: true` allow us to see if the build only fails for a specific arch.

*_rebuild_updated_recipes CI jobs now test the updated recipe along all the supported Android archs (arm64-v8a, armeabi-v7a, x86_64, x86)

---

pythonforandroid/build.py

The Android SDK tools are deprecated in favor of the command line tools.
Trying to use avdmanager from the deprecated tools fails on OpenJDK 11
with since it can't find the `javax/xml/bind/annotation/XmlSchema`
class. Try `cmdline-tools/latest/bin/avdmanager` first.

Prefer avdmanager from cmdline-tools

---

.github/workflows/push.yml
ci/makefiles/osx.mk
pythonforandroid/prerequisites.py
pythonforandroid/toolchain.py
tests/test_prerequisites.py
tox.ini

✂️ Partially sliced from #2586
- Is still experimental
- Moved `autoconf`, `automake`, `libtool`, `openssl` and `pkg-config`
- Added some generic tests and specific ones.
- Changed the logic around `mandatory` and `installer_is_supported`
- Added `SKIP_PREREQUISITES_CHECK` so we can skip prerequisites checks during recipe tests.
- brew-installable prerequisites can follow a DRY approach, but we should make sure that also doesn't over-complicate the `linux` implementation, so I'll leave the improvements for later.

Handle all the macOS prerequisites (except NDK/SDK) via prerequisites.py

---

testapps/on_device_unit_tests/test_app/app_flask.py
testapps/on_device_unit_tests/test_app/main.py

Disable flask threading so that jnius works using the webview bootstrap. See #2533 for more details.

Fix webview testapp jnius usage

---

testapps/on_device_unit_tests/test_app/app_flask.py
testapps/on_device_unit_tests/test_app/templates/index.html

This will help ensure that services work from the webview bootstrap.

Add service to webview test app

---

.github/workflows/push.yml
Makefile
pythonforandroid/bootstraps/webview/__init__.py

This is essentially exactly the same as what the sdl2 bootstrap is
doing.

Support multiarch in webview bootstrap

---

.github/workflows/push.yml

- Same of https://github.com/kivy/kivy/pull/7885
- https://github.com/actions/runner/releases/tag/v2.292.0 now supports Apple Silicon natively. 🥳
- The run_wrapper that was enforcing arm64 on top of a x86_64 process is now un-needed.
- There's a pending PR in actions/python-versions which is expected to introduce support for universal2 versions of Python, so hopefully, we will be able to rely on actions/setup-python also for our self hosted runner in a while..

Our self-hosted Apple Silicon runner now has been migrated to actions/runner v2.292.0 which now supports arm64 natively

---

pythonforandroid/recipes/librt/__init__.py

fix for 
```python
AttributeError: 'ArchARMv7_a' object has no attribute 'ndk_platform'
```

changed arch.ndk_platform to arch.ndk_lib_dir in `librt` recipe

---

pythonforandroid/recipes/librt/__init__.py

fix for lxml build error
```sh
ld: error: unable to find library -lrt
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/ccache' failed with exit status 1
```
the above error is using this path
```sh
/home/<user>/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21/usr/lib
```
instead of 
```sh
/home/<user>/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21
```

removed `usr` and `lib` from ndk library path in `librt` recipe

---

pythonforandroid/recipes/lapack/__init__.py
pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/numpy/patches/fix-missing-threads.h.patch
pythonforandroid/recipes/pybind11/__init__.py
pythonforandroid/recipes/scipy/__init__.py

Google has removed gcc/gfortran support in their latest NDK (r23b), supported by p4a.  Building gfortran out-of-tree is possible, but the sysroot, shipped with NDK r23b does not contain enough libraries to properly link objects, generated by gfortran compiler.
This is a workaround to use older NDK, supporting gcc/gfortran (r19c) to build lapack/scipy, while the rest of the recipes build with r23b by default.
A new environment variable is introduced, `LEGACY_NDK` -> to specify the location of the legacy NDK (r19c), containing gcc/gfortran compilers.

use LEGACY_NDK option to build lapack/scipy with a separate NDK

---

.github/workflows/push.yml
Makefile
ci/makefiles/android.mk
testapps/on_device_unit_tests/test_app/tests/test_requirements.py

Adding CI tests for downloading and extracting `LEGACY_NDK` , gfortran to build lapack/scipy.  Follow-up PR to https://github.com/kivy/python-for-android/pull/2615

add scipy/lapack CI tests

---

doc/source/buildoptions.rst
doc/source/quickstart.rst
doc/source/services.rst

- Adding service_library and 'aar' generation to the documentation.
- Removing absolute paths from service file declaration.
- Adding mention of  `foreground` and `sticky` options in services.

add service_lib and aar to the docs

---

pythonforandroid/build.py
pythonforandroid/recipes/lapack/__init__.py
pythonforandroid/recipes/numpy/__init__.py
pythonforandroid/recipes/python3/__init__.py

- Recently our CI started to fail when checking the availability of certain tools (E.g. `lld`, `ccache` ...)
See: https://github.com/kivy/python-for-android/runs/7394641730
- `sh` released a new version (1.14.3, 12 hours ago) with a breaking change on our side.
- This is due to https://github.com/amoffat/sh/pull/584
- They are right, and in order to achieve what we expect `shutil.which("name")` should be used instead, as returns `None` when a cmd is not found.
From [Python](https://docs.python.org/3/library/shutil.html#shutil.which) docs:
> Return the path to an executable which would be run if the given cmd was called. If no cmd would be called, return None.

Use `shutil.which` instead of `sh.which`

---

.github/workflows/push.yml
Makefile
pythonforandroid/toolchain.py

The final component in the package name is just the extension, so
prefixing it with a - means the output file ends in `-.<ext>`.

Remove stray - in output file name

---

pythonforandroid/toolchain.py
tests/test_toolchain.py

This is necessary when using patches in a local recipe since
`Recipe.apply_patch` assumes the recipe directory is absolute and uses
`patch -d` to change directories. It could just be fixed there, but this
ensures that recipe directories are always absolute.
Closes: #2623

Resolve absolute path to local recipes

---

pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java

Fix #1907 
Back button currently fall to the start [preloader](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/bootstraps/webview/build/webview_includes/_load.html) and stuck on it.
We better keep that in mind and not let it happen.
Also fixed bug when app get closed without confirmation when you launch  it and immediately press back.
https://user-images.githubusercontent.com/20641837/179565742-39e1b920-dc1b-421c-8773-b5a214c0343a.mp4

Fix webview Back button behaviour

---

pythonforandroid/bootstraps/common/build/build.py

usable for example with intent-filters that need extra resources (like `android.hardware.usb.action.USB_DEVICE_ATTACHED`)

Add option for adding files to res/xml without touching manifest

---

pythonforandroid/recipes/hostpython3/__init__.py

fix .buildozer/android/platform/python-for-android/pythonforandroid/recipes/hostpython3/__init__.py", line 69, in get_recipe_env
env["PKG_CONFIG_PATH"] = os.pathsep.join(
TypeError: str.join() takes exactly one argument (2 given)

Fixes TypeError: str.join() takes exactly one argument (2 given) in hostpython3/__init__.py", line 69

---

pythonforandroid/graph.py
tests/test_graph.py

- Assert is a keyword and a space is needed + the parentheses are not needed.
- A recent change in `pycodestyle` (See: https://github.com/PyCQA/pycodestyle/pull/1063) introduced this check.
- CI runs started to fail this evening. (See: https://github.com/kivy/python-for-android/runs/7599511212)

Fixes some E275 - assert is a keyword.

---

pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/toolchain.py

Fix the icon-bg and icon-fg arguments and also create the folder
mipmap-anydpi-v26 if it doesn't exists before trying to create a file
inside.

Add icon-bg and icon-fg to fix_args

---

pythonforandroid/recipe.py
pythonforandroid/toolchain.py
setup.py

- Python 2 is not supported anymore, so `six` is not needed.
- The same applies for `enum34` as python versions < 3.4 are not supported anymore.

Remove six and enum34 dependency

---

Dockerfile

Related to: https://github.com/kivy/python-for-android/issues/2653
We can't support `linux/arm64` as Google doesn't provide a compatible NDK, but we can force **docker** to build a `linux/amd64` image also when running on `arm64` hosts.
This is particularly useful for contributors which may want to run tests locally.

Force `--platform=linux/amd64` in Dockerfile

---

pythonforandroid/recipes/liblzma/__init__.py
tests/recipes/test_liblzma.py

Fixes issue #2343 
On macOS with a case-insensitive filesystem (which is the default), `install` and `INSTALL` are the same thing, and `INSTALL` is a file that already exists.
- The folder used to store the build results (`lib` and `headers`) was previously named `install` and now got renamed to `p4a_install` so it doesn't interfere with the file named `INSTALL`
- Removed an `ensure_dir('install')` call, which was creating an unused folder in the wrong place.
- Added a test that may help us to notice if the folder name gets reverted to `install`

`liblzma`: Use `p4a_install` instead of `install`, as a file named `INSTALL` is already present.

---

.github/workflows/push.yml
ci/makefiles/android.mk
doc/source/quickstart.rst
pythonforandroid/recommendations.py

- Android NDK `25b` fully supports Apple Silicon 🎉 
- Android NDK `25b` is the new LTS version, and ATM, is the only one marked as supported by Google.
Here's a summary of the major changes (NDK 23 -- > NDK 25)  from Google release notes:
- The GNU Assembler (GAS), has been removed. If you were building with -fno-integrated-as you'll need to remove that flag. See [Clang Migration Notes](https://android.googlesource.com/platform/ndk/+/refs/heads/master/docs/ClangMigration.md) for advice on making assembly compatible with LLVM.
- GDB has been removed. Use LLDB instead. Note that ndk-gdb uses LLDB by default, and Android Studio has only ever supported LLDB.
- Jelly Bean (APIs 16, 17, and 18) is no longer supported. The minimum OS supported by the NDK is KitKat (API level 19).
- Non-Neon …

Bump minimal and recommended Android NDK version to 25b

---

tests/test_pythonpackage_basic.py

- Added clarification about this test.
- `toml` is not available on system-wide Python installation on the latest Github Actions runner images.
- The CI started to fail recently, see: https://github.com/kivy/python-for-android/runs/8256955240

`toml` may not be available on systemwide python

---

ci/constants.py
pythonforandroid/recipes/libvpx/__init__.py

Fixes issue #2665 
- `libvpx` build was silently failing.
- `--enable-external-build` is preventing the build to success.
- Disabled `neon-asm` on `armeabi-v7a`
- Removed `ffpyplayer` from `BROKEN_RECIPES`

Fixes libvpx build

---

doc/source/apis.rst
pythonforandroid/recipes/android/src/android/activity.py
testapps/on_device_unit_tests/test_app/app_flask.py
testapps/on_device_unit_tests/test_app/app_kivy.py
testapps/on_device_unit_tests/test_app/tools.py

The `Application.ActivityLifecycleCallbacks` interface is used to register a class that can receive callbacks on Activity lifecycle changes. Add a `PythonJavaClass` implementing the interface and helper functions to register python callbacks with it. This can be used to perform actions in the python app when the activity changes lifecycle states.

android/activity: Add Application.ActivityLifecycleCallbacks helpers

---

pythonforandroid/archs.py

Many of the tools run by p4a store intermediate files in the user's home
directory. Passing the HOME environment variable to the build
environment has 2 positive effects:
1. To completely encapsulate the build, HOME can be set to an alternate
directory than the user's actual home directory. Many tools such as
p4a have options to override these paths, but that must be done on a
case by case basis and it would require that p4a pass through these
options or environment variables.
2. In containerized environments the user may not be registered in the
accounts database. If the user's home directory can't be found from
the HOME environment variable or the accounts database, many tools
will fail. An example of this is python2.7 when run by `ndk-build`.
I don't know if this is the best place to …

Include HOME in build environment

---

pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

When the adjust mode is unspecified, Android will not resize the webview when showing the on screen keyboard to keep the input element on screen. Explicitly instruct it to use `adjustResize` mode. Possibly this is because the webview bootstrap uses an `AbsoluteLayout` as the top level widget. See
https://developer.android.com/guide/topics/manifest/activity-element#wsoft for details.

Resize webview when keyboard is shown

---

setup.py
tests/test_pythonpackage_basic.py

The "<0.7.0" bound was added in https://github.com/kivy/python-for-android/commit/9f6d6fcce748be96ed606815aca9294644ac90cc to fix https://github.com/kivy/python-for-android/issues/1994 :
> The `TestGetSystemPythonExecutable.test_virtualenv` and `TestGetSystemPythonExecutable.test_venv` tests started failing all of a sudden. Error was:
>
> ```
> ModuleNotFoundError: No module named \'pytoml\'\n'
> ```
>
> This ca be reproduced in local via:
>
> ```shell
> pytest tests/test_pythonpackage_basic.py::TestGetSystemPythonExecutable::test_virtualenv
> ```
I think this no longer applies,
`$ pytest tests/test_pythonpackage_basic.py::TestGetSystemPythonExecutable` runs successfully for me, using latest `pep517==0.13.0`.
---
Also, let's see if the CI tests pass.

requirements: relax version bound on "pep517"

---

pythonforandroid/recipe.py

When a recipe uses a "git+..." `url`, and has a `version` specified, only do a shallow git clone. This saves disk space and bandwidth.
Tested with a custom qt5 recipe.
Without this patch, the git clone on disk was 8.5 GB, now it is 5.0 GB.
```
class Qt5Recipe(BootstrapNDKRecipe):
url = 'git+https://code.qt.io/qt/qt5.git'
version = '9b43a43ee96198674060c6b9591e515e2d27c28f'  # version 5.15.2
```

recipe.download_file: implement shallow git cloning

---

pythonforandroid/recommendations.py
tests/test_recommendations.py
tests/test_toolchain.py

Google Play is enforcing to target a recent API, as it follows:
Android OS version | New app | Updated app ** | Existing app
-- | -- | -- | --
Android 13 (API level 33) | August 1, 2023 | November 1, 2023 | November 1, 2024
Android 12 (API level 31) | August 1, 2022 | November 1, 2022 | November 1, 2023
Android 11 (API level 30) | August 1, 2021 | November 1, 2021 | November 1, 2022
Name | Description
-- | --
New app | An app that is not yet published on Google Play (for example, a brand new app).
Updated app | A new version of an app that is already published on Google Play.
Existing app | A published app that is not receiving updates.
Further info: https://support.google.com/googleplay/android-developer/answer/11926878?hl=en
This PR bumps `MIN_TARGET_API` and `RECOMMENDED_TARGET_API` …

Update `MIN_TARGET_API` to `30` and `RECOMMENDED_TARGET_API` to `33`

---

pythonforandroid/recipes/aiohttp/__init__.py

References: 
https://stackoverflow.com/a/64755338/20124004,
https://stackoverflow.com/a/64755052/20124004, 
https://github.com/kivy/python-for-android/pull/2518

Make CI compile aiohttp again.

---

pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml

On Android 11 / sdk 30 WRITE_EXTERNAL_STORAGE no longer has any meaning. 
Ref: https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11
This PR removed a Gradle warning message.

WRITE_EXTERNAL_STORAGE maxSdk

---

doc/source/buildoptions.rst
doc/source/launcher.rst
pythonforandroid/bdistapk.py
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/common/build/jni/application/src/start.c
pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/service_only/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/bootstraps/webview/build/src/main/java/org/kivy/android/PythonActivity.java
pythonforandroid/build.py
pythonforandroid/recipes/python3/__init__.py

When building an app via `python-for-android` (without using `buildozer` on top of it), the app may fail to build.
`python-for-android` refuses to build due to a python file that is located in a blacklisted folder (via `blacklist.txt`) as that file is failing the byte-compile step.
That should not happen, as a blacklisted folder (E.g. `venv` or `.git`) may contain a python file that can't be byte-compiled.
Also, byte-compiling a blacklisted folder may lead to an increase of the build time.
This PR targets the above-mentioned issue, and the following minor ones:
- **As of Python 3.5, the `.pyo` filename extension is no longer used and has been removed in favour of extension `.pyc`**
All the references to `pyo` has been removed. `--no-compile-pyo` build option has been removed in favor of …

Fixes an issue regarding blacklist and bytecode compile + some cleanup

---

doc/source/buildoptions.rst
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/toolchain.py

Why does adding Android resources have so many PRs but no implementation? Clearly users think it is a necessary feature. This is another try.
There are two outstanding PRs, https://github.com/kivy/python-for-android/pull/2580 and https://github.com/kivy/python-for-android/pull/2299. And a partial solution has previously been incorporated https://github.com/kivy/python-for-android/pull/2330, but is not documented in buildozer.spec and apparently doesn't work https://github.com/kivy/buildozer/issues/1508.
This PR is based on the observation that there is a simple hack for adding resources using `add_assets` and prefixing the second field with `../res/` like this 
```
android.add_assets = icons/all-inclusive.png:../res/drawable/all_inclusive.png
```
This implementation simply copies the …

Add resources

---

pythonforandroid/recipes/audiostream/__init__.py
pythonforandroid/recipes/ffpyplayer/__init__.py
pythonforandroid/recipes/kivy/__init__.py
pythonforandroid/recipes/pygame/__init__.py
pythonforandroid/recipes/sdl2_mixer/__init__.py
tests/recipes/test_sdl2_mixer.py

Fixes issue: https://github.com/kivy/python-for-android/issues/2698
Include paths for `sdl2_mixer` changed recently, so recipes (like `ffpyplayer`) that were using a hardcoded path are failing to build.
- Added a `get_include_dirs` method (like the one we have in `libffi`), for `sdl2_mixer`.
- Replaced any hardcoded path with the new `get_include_dirs` method.
- Added a (very) minimal test to check the new method.

Include paths for sdl2_mixer have changed. Added a method to return the right one.

---

pythonforandroid/toolchain.py

Headache time 🤕⏱️!
As clearly described by @DexerBR in #2704 :
> The app size grows unexpectedly from 18.5MB to 26.4MB in the second build. From the second to next builds, the sudden size changes seem to stabilize.
For a still unknown(likely a Gradle bug) reason, the produced `APK` is bigger on non-first builds.
After some analysis (unpacked the APK, checked and compared the content), I can say that only the size of the APK itself is different, not the content, as when it gets unzipped, the size of the unzipped content is the same between the first build and subsequent ones.
The files md5 hashes are the same, except for the `assets/private.tar` file (and its content), as I'm not building with `SOURCE_DATE_EPOCH` set, which means that …

Gradle: Run the clean task before anything else to make sure nothing is cached.

---

pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch
pythonforandroid/recipes/sdl2/__init__.py
pythonforandroid/recipes/sdl2/remove-extra-include.patch

This is a WIP PR meant for testing a pre-release SDL feature that should fix the following issues:
- https://github.com/kivy/python-for-android/issues/2010
- https://github.com/kivy/kivy/issues/7337
Edit:
SDL `2.26.0` has been released, and even if it needs a small patch during build-time, works great!
The SDL team said that `2.26.1` (which doesn't need `remove-extra-include.patch` anymore) is expected to be released in a month.
But, considering that we're not targeting anymore a pre-release version, this PR could be considered ready to merge.

Bump to a version of `SDL` with patches for the TextInput / TextEditing (SDL `2.26.0`)

---

pythonforandroid/recipe.py
tox.ini

See:
- https://github.com/PyCQA/flake8/issues/1760
From https://flake8.pycqa.org/en/latest/user/configuration.html :
> Following the recommended settings for [Python’s configparser](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour), Flake8 does not support inline comments for any of the keys. So while this is fine:
```
[flake8]
per-file-ignores =
__init__.py: F401
```
> this is not:
```
[flake8]
per-file-ignores =
__init__.py: F401 # imported but unused
```

Flake8 does not support inline comments for any of the keys.

---

pythonforandroid/recipes/secp256k1/cross_compile.patch

Fix recipe that doesn't build without setting an environment variable.
"--host=" is now implemented in the same manner as other recipes.

secp256k1 Update "--host="

---

pythonforandroid/bootstraps/sdl2/build/src/patches/SDLActivity.java.patch

Unfortunately (and I'm creating a detailed report for us and the SDL team), suggestions from Android keyboards are still not completely usable. 😔
A logic, that mimics every possible scenario should be implemented on our side or on SDL's side if we decide to keep using input from SDL on mobile devices (which still makes sense ATM).
In one of the recents SDL updates, `InputType.TYPE_TEXT_FLAG_MULTI_LINE` has been or-ed with the InputType.
That is preventing `InputType.TYPE_NULL` (which is the default on `kivy/kivy==master`) to work, as `InputType.TYPE_TEXT_FLAG_MULTI_LINE` forces `InputType.TYPE_TEXT` even if `SDLActivity.keyboardInputType` is `InputType.TYPE_NULL`.
If needed `InputType.TYPE_TEXT_FLAG_MULTI_LINE` should be moved on our InputType selection logic in `kivy/kivy`.
See: …

`InputType.TYPE_TEXT_FLAG_MULTI_LINE` forces `InputType.TYPE_TEXT` even if `SDLActivity.keyboardInputType` is `NULL`

---

pythonforandroid/recipes/sdl2/__init__.py
pythonforandroid/recipes/sdl2/sdl-orientation-pr-6984.diff

- inverse landscapeLeft and landscapeRight (now behaves as described in SDL docs)
- fix to match exactly Portrait (as it is contained in PortraitUpsideDown)
See: https://github.com/libsdl-org/SDL/pull/6964 and https://github.com/kivy/python-for-android/issues/2724#issuecomment-1368142168

Apply a patch from SDL upstream that fixes orientation settings

---

pythonforandroid/recipes/scrypt/__init__.py

`scrypt` recipe is not working...
Updating the version to `0.8.20` and the url to `https://github.com/holgern/py-scrypt/archive/refs/tags/v{version}.zip` fixes it
You can check the latest release of `scrypt` here: https://github.com/holgern/py-scrypt/releases/tag/v0.8.20
Already tested it on my phone, it works only after applying this fix

Update __init__.py from `scrypt` recipe

---

doc/source/buildoptions.rst
pythonforandroid/bdistapk.py
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml
testapps/on_device_unit_tests/setup.py
tests/test_bootstrap_build.py

As discussed on issue #2724 , when targeting API 31 and above, on Android 12 and above, the attribute `android:screenOrientation` is ignored, as the activity will run in multi-window mode.
This PR takes advantage of changes made on SDL side which have been applied as a patch to `python-for-android` SDL build: https://github.com/kivy/python-for-android/pull/2730.
After these changes, orientation can be controlled in two ways:
`--orientation` will control the allowed orientations (`portrait`, `landscape`, `portrait-reverse`, `landscape-reverse`). The allowed orientations list is then set to `KIVY_ORIENTATION`, which is used during window setup time to populate the `SDL_HINT_ORIENTATIONS` value, as we're doing for other platforms.
`--manifest-orientation` has been added to keep the …

Implements `--manifest-orientation` and changes how `--orientation` works so we can now pass the setting to the SDL orientation hint

---

pythonforandroid/recipes/pydantic/__init__.py

There is [incompatibility](https://github.com/huggingface/transformers/issues/8638) between python > 3.6 and package `dataclasses`.
This error was happening after my compilations: `AttributeError: module 'typing' has no attribute '_ClassVar'`
The fix is removing `dataclasses` from `python_depends`.
I also updated the pydantic version to the newest release `1.10.4`, it can be checked [here](https://github.com/pydantic/pydantic/releases) and its url.
I already compiled my app after applying these changes, and the compilation is working successfully again.

🐛 fix: Update `pydantic` recipe

---

setup.py

keep sh version under 2.0 as default behaviour was switched

restrict sh version

---

pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/recipes/hostpython3/__init__.py
pythonforandroid/recipes/python3/__init__.py

- Adds support for Python 3.10 in `hostpython3` and `python3` recipes.
- Makes Python 3.10 the default version.

Add support for Python 3.10 and make it the default while building hostpython3 and python3

---

pythonforandroid/recipes/av/__init__.py
pythonforandroid/recipes/av_codecs/__init__.py

[PyAV](https://github.com/PyAV-Org/PyAV) - is a Pythonic binding for the [FFmpeg](http://ffmpeg.org/) libraries.
I also added a recipe for the codecs in a similar way to ffpyplayer.

Add PyAV recipe

---

pythonforandroid/distribution.py

Sometimes the android dist is being rebuilt every time, and it's hard to understand why that happens. This PR adds some debug logging so that it's easier to investigate when this happens.
In my case, I incorrectly used `Cython` and `Pillow`  in the `requirements` of my `buildozer.spec`, and this caused my dist to be rebuild every time, because `dist.recipes` would have `cython` and `pillow` in it, and p4a thinks it's missing the recipes `Cython` and `Pillow`.

Add debug loggings for identifying a matching dist

---

pythonforandroid/bootstraps/common/build/jni/application/src/start.c

This provides reasonable default implementations for common IO class methods such as isatty().
Closes #2762.

Use io.IOBase for LogFile

---

pythonforandroid/bootstraps/common/build/build.py

Smaller fix when `android_api` was given as a string but integer is needed and expected.

android_api to integer

---

pythonforandroid/tools/liblink

Looks like a regression from 22b7dfee1ddc5f435f8bf016cbf83980a45b4374
To be honest I am not sure how this file is used. Maybe it could be removed altogether seeing as no one complained for three years.

fix tools/liblink: syntax error

---

pythonforandroid/recipes/pyjnius/__init__.py

Update `pyjnius` to latest available version (`1.5.0`) as it contains a fix needed to correctly handle log on **Kivy 2.2.0** and onwards.

Update `pyjnius` version to `1.5.0`

---

pythonforandroid/recipes/kivy/__init__.py

~~⚠️ WIP - DO NOT MERGE
⚠️ Currently uses the pre-release version (2.2.0rc1) for testing~~
Updates the Kivy recipe, and adds the proper (new) dependencies. 
`chardet` is used as a replacement for `charset-normalizer>=3.x`, which requires a recipe (or, as an alternative, and it will likely land on `python-for-android` soon, the proper flags during `pip install`, to select a non-platform specific wheel).

Update Kivy recipe for 2.2.0

---

pythonforandroid/recipes/cffi/__init__.py
pythonforandroid/recipes/cffi/disable-pkg-config.patch

version bump required for python3.10
resolves #2799

Cffi update

---

pythonforandroid/pythonpackage.py
setup.py
tests/test_pythonpackage.py
tests/test_pythonpackage_basic.py

pep517 has been renamed to pyproject-hooks, and as a consequence all of the deprecated functionality has been removed. build now provides the functionality required, and since we are only interested in the metadata, we can leverage a helper function for that. I've also removed all of the subprocess machinery for calling the wrapping function, since it appears to not be as noisy as pep517.

Use build rather than pep517 for building

---

.github/workflows/push.yml
.github/workflows/pypi-release.yml

We currently use an old version of `actions/setup-python` and `actions/checkout`.
Github suggest to update them, as are outdated and are making use of `Node.js 12`, which is deprecated and will removed soon.
The new versions are based on `Node.js 16`.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Bump `actions/setup-python` and `actions/checkout` versions, as old ones are deprecated

---

.github/workflows/push.yml
Makefile

Well, parallelizing builds, even if most of the work is duplicated, is usually good. (If you're not paying for CI runs)
This is something valid also for `python-for-android` artifacts builds, as parallelizing `APK` and `AAB` builds takes ~14 minutes less than a build that performs APK (debug) + AAB (release) build in the same run.
But ... even if we're not paying for CI runs (thank you GitHub), workers are capped at a maximum concurrent number (and in the case of our Apple Silicon M1 self-hosted runner, only one instance per time is available), which means that other jobs need to wait the completion of previous ones. (making it slower than non-parallelized builds)
Some data, on Ubuntu:
- APK + AAB: `1h 19m 47s` (keeps only 1 instance locked for the entire build)
- APK `1h 5m 21s` + AAB …

Optimize CI runs, by avoiding unnecessary rebuilds

---

setup.py

On Window, sys.platform = "win32".
I think "nt" is a reference to os.name.

Correct sys_platform

---

pythonforandroid/recipes/kivy/__init__.py

Bump `kivy` version to `2.2.1` (latest release)

Bump `kivy` version to `2.2.1`

---

Makefile

`Cython>=3.0.0` broke our CI pipeline.
But it's not `Cython` fault, instead, we urge to change our `python-for-android` and `kivy-ios` logic to not rely on a single specific `Cython` version for all the packages, as every package should be able to decide the `Cython` (and other build-time-only packages to use).
Meanwhile, to keep the development up and running, that seems the faster solution.
(See https://github.com/kivy/buildozer/pull/1637)

Use a pinned version of `Cython` for now, as most of the recipes are incompatible with `Cython==3.x.x`

---

pythonforandroid/prerequisites.py

`get_required_prerequisites()` maintains a list of Prerequisites required by each platform.
But that same information is already stored in each Prerequisite class.
Rather than maintaining two lists which might become inconsistent, auto-generate one.
[Note: Unit tests fail, but I don't think it is a result of this change,]

Automatically generate required pre-requisites

---

README.md
pythonforandroid/util.py

Advantages:
- Works cross platform, not just Unix.
- Is a namedtuple, so can use meaningful  fieldnames.
Also snuck in correction to typo in Readme which doesn't warrant its own review.
[Note: Unit-tests failed, but I don't *think* it had anything to do with this.]

Use platform.uname instead of os.uname

---

README.md
pythonforandroid/pythonpackage.py

One typo I introduced while trying to fix the other.

Fix simple typos in comments

---

pythonforandroid/util.py

`build_platform` should be all-lowercase. 
FYI: @Julian-O , the issue has been introduced via #2857 (CI wasn't working as expected, and was hard to see)
Now that CI is working as expected, see: https://github.com/kivy/python-for-android/actions/runs/5630635544/job/15256832012?pr=2863

`build_platform` should be all-lowercase

---

pythonforandroid/patching.py

`patching.py` contains a set of helper functions for recipe developers to specify patch conditions. Most of them are still not used.
This refactor maintains the same API, but does a lot of re-ordering and reformatting to make this library easier for a recipe-writer to adopt.  Docstrings and other comments have been added, parameter types are explained, kwargs are avoided for simplicity. None of these affect any existing client.
In addition, there are three functional changes:
* `distutils.LooseVersion` is deprecated and causing warnings. `package.version.Version` takes its place. These do have slightly different semantics, but no-one seems to be using these functions yet, so there are no clients to fix.
* `os.uname()[0]` replaced with `platform.uname.system()` which works cross-platform. …

Patching cleanup

---

.github/workflows/push.yml
doc/source/buildoptions.rst

Python 3.11 was released October 2022.
Python 3.7 went end-of-life June 2023

Python versions: Update documentation & CI testing

---

pythonforandroid/checkdependencies.py
pythonforandroid/toolchain.py

`toolset.py` uses the class `LooseVersion` from `distutils` to implement comparison of versions.
[Distutils](https://docs.python.org/3/library/distutils.html) is deprecated, and won't be in Python 3.12 which is [< 3 months away](https://peps.python.org/pep-0693/).
As a result, deprecations warnings are appearing in p4a's logs.
This PR moves over to use `packaging.Version`. `packaging` is a already an install_req.
Note: `packaging.Version` is a lot more opinionated about what a version number must look like. The current Python dependencies that are checked are [sh](
https://pypi.org/project/sh/#history_) and [colorama](https://pypi.org/project/colorama/#history), both of which adhere to this versioning standard, so there is no issue there.
But, Android SDK versions sometimes contain …

Factor out dependency checking. Use modern version handling

---

pythonforandroid/bootstrap.py
pythonforandroid/build.py
pythonforandroid/graph.py
tests/test_build.py

The errors were:
```
pythonforandroid/bootstrap.py:136:5: F811 redefinition of unused 'name' from line 73
pythonforandroid/build.py:111:5: F811 redefinition of unused 'libs_dir' from line 82
pythonforandroid/build.py:127:5: F811 redefinition of unused 'aars_dir' from line 83
pythonforandroid/graph.py:48:12: E721 do not compare types, for exact checks use `is`
pythonforandroid/graph.py:163:20: E721 do not compare types, for exact checks use `is`
tests/test_build.py:39:41: E231 missing whitespace after ','
tests/test_build.py:40:58: E231 missing whitespace after ','
tests/test_build.py:41:61: E231 missing whitespace after ','
tests/test_build.py:42:71: E231 missing whitespace after ','
```

:rotating_light: linter fixes

---

pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

When running Gradle, a warning is issued:
> [DEBUG]:   	**> Configure project :**
> [DEBUG]:   	WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
I went to [Stack Overflow](https://stackoverflow.com/questions/68215302/using-flatdirs-should-be-avoided-because-it-doesnt-support-any-meta-data-format) to learn what the appropriate action was, and while the answers varied, they generally recommended removing the `flatDir` entry and adding a `jniLibs.srcDir[s]` entry to under `sourceSets`.
Examining the Gradle template, the `sourceSets` were already configured, so I simply removed the `flatDir` entry.
Confirmed that `flatDir` warnings are no longer logged, and builds are proceeding fine.

Remove deprecated FlatDir in Gradle template

---

pythonforandroid/bootstrap.py
pythonforandroid/recipe.py
pythonforandroid/util.py
tests/test_bootstrap.py
tests/test_util.py

* Add new util function (and tests) called `move`.
* Change references to sh.mv to use move (as it is faster and cross-platform).
* Change conditional "mv -t" to a for-loop.
* This altered imports which affected rmtree instances too, so cleaned that up.

Standardise on move

---

pythonforandroid/recipe.py
pythonforandroid/recipes/protobuf_cpp/__init__.py
pythonforandroid/recipes/reportlab/__init__.py
pythonforandroid/util.py
tests/recipes/test_reportlab.py
tests/test_recipe.py
tests/test_util.py

Existing code shells out to run the `touch` Unix command. This can be done faster (and cross-platform) with `pathlib`'s touch method.
* Created a utility to accept string paths or pathlib paths and applies touch.
* Created test for it.
* Update all instances to use it, and updated their tests.
* Where imports were touched, made them PEP8 compliant.

Use Python's touch() rather than shelling out.

---

pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

Updates the Lottie player version to [the latest 6.1.0](https://github.com/airbnb/lottie-android/releases).
The current version in use (3.4.0) is from 2020, and among the many issues that have already have been fixed since then, it does not allow for color updates in keyframes[0], which is a very common operation when changing Lotties that already exist out there in the public domain.
[0] https://stackoverflow.com/questions/74912770/lottie-animation-error-after-change-color-of-animation

Update Lottie player version

---

pythonforandroid/archs.py
pythonforandroid/bootstraps/common/build/build.py
pythonforandroid/recipe.py
pythonforandroid/recommendations.py
pythonforandroid/toolchain.py
pythonforandroid/util.py
setup.py
testapps/on_device_unit_tests/setup.py
testapps/setup_testapp_python3_sqlite_openssl.py
testapps/setup_vispy.py
testapps/testlauncher_setup/sdl2.py
testapps/testlauncherreboot_setup/sdl2.py
tests/recipes/recipe_lib_test.py
tests/recipes/test_icu.py
tests/recipes/test_libgeos.py
tests/recipes/test_libmysqlclient.py
tests/recipes/test_libpq.py
tests/recipes/test_libvorbis.py
tests/recipes/test_openal.py
tests/recipes/test_openssl.py
tests/recipes/test_pandas.py
tests/recipes/test_pyicu.py
tests/recipes/test_python3.py
tests/test_archs.py
tests/test_bootstrap.py
tests/test_build.py
tests/test_recipe.py
tests/test_recommendations.py
tests/test_util.py

Recently, our CI pipeline began failing due to the default Python version provided by `actions/setup-python` being set to `3.12`. This issue stems from the removal of `distutils` in Python `3.12`.
**Changes:**
To address the Python 3.12 compatibility issue, this pull request introduces the following changes:
- Replaced `distutils.spawn.find_executable` with `shutil.which` for locating executables.
- Replaced the use of `distutils.version.LooseVersion` with `packaging.version.version` for version comparisons.
- Introduced two new methods, `build_tools_version_sort_key` and `max_build_tool_version`, in the `pythonforandroid.utils` module. These additions not only resolve DRY (Don't Repeat Yourself) violations but also enhance testability.
- Updates the testapps to use `setuptools` instead …

Remove `distutils` usage, as is not available anymore on Python `3.12`

---

pythonforandroid/recipes/pyjnius/__init__.py

As our [CI have shown](https://github.com/kivy/python-for-android/actions/runs/6774900670/job/18413008601), `pyjnius==1.5.0` still relies on Java 7, which is old (and now not usable anymore on `macos-latest`, with default Java version)
From `pyjnius>1.6.0`, Java 7 is not required anymore, while building the `pyjnius` Java source code.

Bump `pyjnius` version to `1.6.1`

---

FAQ.md

This is largely stolen and copy-edited from python-for-android trouble-shooting section, and Kivy's FAQ.
Future work:
* Remove duplicate info from trouble-shooting section.
* Remove duplicate info from Kivy framework FAQ.
* Link to this from Kivy framework FAQ.

Introduce  FAQ

---

pythonforandroid/bootstraps/common/build/gradle/wrapper/gradle-wrapper.properties
pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle
pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_library/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/service_only/build/templates/AndroidManifest.tmpl.xml
pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml

- Removes API 33 warning:
```
[DEBUG]:   	WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33 > IDLE
[DEBUG]:   	
[DEBUG]:   	This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
[DEBUG]:   	
[DEBUG]:   	This warning can be suppressed by adding
[DEBUG]:   	    android.suppressUnsupportedCompileSdk=33
[DEBUG]:   	to this project's gradle.properties
[DEBUG]:   	
[DEBUG]:   	The build will continue, but you are strongly encouraged to update your project to
[DEBUG]:   	use a newer Android Gradle Plugin that has been tested with compileSdk = 33
```
- `namespace` in `build.gradle` (mandatory) now replaces `package` in `AndroidManifest.xml`

Update Android gradle plugin to `8.1.1` and gradle to `8.0.2`

---

ci/constants.py
pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
pythonforandroid/recipes/cython/__init__.py
pythonforandroid/recipes/hostpython3/__init__.py
pythonforandroid/recipes/pybind11/__init__.py
pythonforandroid/recipes/python3/__init__.py
pythonforandroid/recipes/python3/patches/cpython-311-ctypes-find-library.patch
pythonforandroid/recipes/scipy/__init__.py
pythonforandroid/recipes/scipy/setup.py.patch

Add support for Python `3.11` and make it the default while building `hostpython3` and `python3`

---

Dockerfile
doc/source/quickstart.rst
pythonforandroid/prerequisites.py

- Updates `Dockerfile` (clean up of old requirements and change of base image)
- Set JDK version `17` as a prerequisite, newer JDK versions such as `21` are incompatible with our version of `gradle`, and `gradle` now requires at least `JDK 17`
- Update docs to reflect the current status (ouch, docs were super-outdated)

Update `python-for-android` prerequisites (`Dockerfile`, `prerequisites.py`, docs)

---

pythonforandroid/bootstraps/common/build/templates/build.tmpl.gradle

While upgrading to the new SDL2 (in fact the CI is failing), which uses lambdas in Java, I noticed we still have set both `sourceCompatibility` and `targetCompatibility` to `1.7` by default, unless `androidx` is enabled.
This PR makes `1.8` the default, even if `androidx` is disabled.
Some additional info about Java API on Android (and support for old APIs):
- https://developer.android.com/studio/write/java8-support
- https://developer.android.com/studio/write/java8-support-table
From #2927 CI run:
```
> Task :compileDebugJavaWithJavac FAILED
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use …
```

`sourceCompatibility` 1.7 and `targetCompatibility` 1.7 are obsolete, use 1.8 by default

---

pythonforandroid/recipes/kivy/__init__.py

Bump `kivy` version to `2.3.0` (latest release)

Bump Kivy version to `2.3.0`

---

pythonforandroid/recipes/openssl/__init__.py

I encountered the following error:
`Downloading openssl from https://www.openssl.org/source/openssl-1.1.1m.tar.gz`
resulted in
`urllib.error.HTTPError: HTTP Error 404: Not Found`
and a failed build.
On visiting [the link from the old code](https://www.openssl.org/source/openssl-1.1.1m.tar.gz), it says
> Page Not Found
> Sorry, but the link you gave does not exist.
The download for old version has been moved to https://www.openssl.org/source/old/1.1.1/openssl-1.1.1m.tar.gz
The link for the latest version is https://www.openssl.org/source/openssl-1.1.1w.tar.gz
This commit includes the updated link to resolve the above error.

Update OpenSSL version to `1.1.1w`

---

pythonforandroid/recipes/materialyoucolor/__init__.py

recipes: new `materialyoucolor` recipe

---

pythonforandroid/recipes/libzmq/__init__.py

libzmq: fix build

---

pythonforandroid/recipes/coincurve/__init__.py
pythonforandroid/recipes/coincurve/coincurve.patch
pythonforandroid/recipes/libsecp256k1/__init__.py

recipes: new recipe `coincurve`
