kivy/python-for-android

- recipes/opencv/patches/p4a_build-2.4.10.1.patch
- recipes/opencv/recipe.sh
This is a fully working recipe for OpenCV (v2.4.10.1). The recipe automatically builds OpenCV Python module (cv2.so) and installs native camera libraries. This recipe attempts to fix #75.
> Recipe for OpenCV

- recipes/bidi/recipe.sh
This recipe is for the bidi module, very useful to display languages which are red from right to left (such as Arabic or Hebrew)
> added recipe for bidi (bi-directional layout implementation)

- recipes/openssl/recipe.sh
Previous version was vulnerable for FREAK, others.
> update to openssl version 1.0.2b

- recipes/ecdsa/recipe.sh
- recipes/paramiko/recipe.sh
- Update paramiko recipe to a newer version 
- Add ecdsa recipe (dependency)
> Update paramiko recipe

- pythonforandroid/bootstraps/pygame/build/build.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/compiler.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/debug.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/environment.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/ext.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/filters.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/lexer.py
- pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg/jinja2/utils.py
@thopiekar 
* modified few files to support python 3 syntax.
I havent tested it though.
> [revamp] Fixed some invalid python syntax errors in the pygame builds. Fixes #444

- pythonforandroid/toolchain.py
some things probably lost in prev. pull req. merging
> cosmetic: toolchain logs improved

- pythonforandroid/toolchain.py
Shows all output when a shell command fails.
> show full output from failed commands

- pythonforandroid/recipe.py
Needed when a recipe overrides commands like `build` rather than `build_ext`. Also fixes some environment usage when calling setup.py.
> allow using a command other than "build_ext", fix some env usage

- pythonforandroid/recipe.py
Allows version to be used to select a branch or tag.
> use version for git urls

- pythonforandroid/bootstraps/sdl2/build/jni/src/start.c
Eggs don't work without this code.
> fix site packages

- setup.py
> fix missing mk files in installed p4a

- pythonforandroid/recipes/openssl/__init__.py
- pythonforandroid/recipes/openssl/disable-sover.patch
> Update OpenSSL recipe & patch

- pythonforandroid/recipes/python2/__init__.py
> Use darwin patches

- pythonforandroid/recipes/boost/__init__.py
- pythonforandroid/recipes/boost/disable-so-version.patch
- pythonforandroid/recipes/boost/use-android-libs.patch
- pythonforandroid/recipes/boost/user-config.jam
- pythonforandroid/recipes/libtorrent/__init__.py
- pythonforandroid/recipes/libtorrent/disable-so-version.patch
- pythonforandroid/recipes/libtorrent/use-soname-python.patch
> add libtorrent recipe

- pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonUtil.java
> load python lib before main

- setup.py
> install .jam config files for recipes;

- pythonforandroid/recipes/m2crypto/__init__.py
Tested with this script on Android 6.0.1: https://e1ven.com/2011/04/06/how-to-use-m2crypto-tutorial/
> Added M2Crypto recipe

- pythonforandroid/recipes/openssl/__init__.py
Lots of (security) issues fixed: https://www.openssl.org/news/changelog.html#x1
> Update openssl to 1.0.2g

- pythonforandroid/bootstraps/sdl2/build/build.py
- pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
Fix for issue https://github.com/kivy/python-for-android/issues/666.
> Window option for SDL2 bootstrap

- pythonforandroid/recipe.py
Now supports .tar.xz and anything tar can do could be easily added.
> Let tar automatically recognize compression format

- pythonforandroid/recipes/pyleveldb/__init__.py
Change to CompiledComponentsPythonRecipe
> Minor refactor PyLevelDB recipe

- pythonforandroid/recipes/spine/__init__.py
Recipe for [spine-cython](https://github.com/tileworks/spine-cython).
> Add spine-cython recipe.

- pythonforandroid/recipes/ipaddress/__init__.py
Only change was added licence.
> update ipaddress to 1.0.16

- pythonforandroid/recipes/sdl2_mixer/__init__.py
- pythonforandroid/recipes/sdl2_mixer/toggle_modplug_mikmod_smpeg_ogg.patch
> update sdl2_mixer 2.0.1

- pythonforandroid/recipes/sdl2/__init__.py
- pythonforandroid/recipes/sdl2/add_nativeSetEnv.patch
> update sdl2 to 2.0.4

- pythonforandroid/recipes/cherrypy/__init__.py
- pythonforandroid/recipes/decorator/__init__.py
- pythonforandroid/recipes/feedparser/__init__.py
- pythonforandroid/recipes/libnacl/__init__.py
- pythonforandroid/recipes/requests/__init__.py
> Python recipes CherryPy LibNaCl Requests FeedParser Decorator

- pythonforandroid/recipes/libffi/__init__.py
> call autoreconf before building libffi

- pythonforandroid/recipes/netifaces/__init__.py
Depends on PR #775 (Python 2.7.11) and PR #793
> Netifaces's recipe (mandatory for Python 2.7.11)

- pythonforandroid/recipes/opencv/__init__.py
- pythonforandroid/recipes/opencv/patches/p4a_build-2.4.10.1.patch
> Add opencv recipe

- doc/source/index.rst
- doc/source/services.rst
Not for merging quite yet, I haven't checked if it's actually all correct, but adding here so as not to forget.
> Added Service doc page

- pythonforandroid/recipes/libffi/__init__.py
Fixes #766 for building without buildozer.
> fix autoconf libffi

- pythonforandroid/recipes/kiwisolver/__init__.py
Fixes "ImportError no module setuptools" when building
> Add setuptools for kiwisolver

- doc/source/quickstart.rst
> Fix toctree

- pythonforandroid/recipes/cryptography/__init__.py
Also add requirements from setup.py
> update cryptography to 1.4

- pythonforandroid/recipes/openssl/__init__.py
Patch can remain exactly the same.
> update openssl recipe to 1.0.2h

- pythonforandroid/recipes/boost/__init__.py
Use default system host toolchain.
> Boost recipe NDK12b compatibility

- pythonforandroid/bootstraps/sdl2/build/templates/strings.tmpl.xml
Added "presplash_color" argument to set the loading screen background color
> Added "presplash"_color argument

- doc/source/recipes.rst
small spelling mistake ...
fron -> from
> documentation recipe.rst spelling change

- doc/source/quickstart.rst
It is the same as the one at the end of the command.
> Remove the excessive ccache in the command

- pythonforandroid/recipes/pymunk/__init__.py
This is a recipe for Pymunk (the latest 5.2.0 version).
> Recipe for Pymunk

- pythonforandroid/recipes/kivy/__init__.py
Fixes https://github.com/kivy/python-for-android/issues/1044
> Updated Kivy recipe to pull 1.10.0

- pythonforandroid/recipes/pbkdf2/__init__.py
- pythonforandroid/recipes/pycryptodome/__init__.py
- pythonforandroid/recipes/secp256k1/__init__.py
- pythonforandroid/recipes/secp256k1/no-download.patch
- pythonforandroid/recipes/secp256k1/pkg-config.patch
* pycryptodome
* secp256k1
* pbkdf2
> Various Ethereum related recipes fixes

- pythonforandroid/recipes/protobuf_cpp/__init__.py
- pythonforandroid/toolchain.py
Fixes the protobuf_cpp recipe's inconsistent indentation, and makes p4a try harder to ignore broken recipes when listing them.
> Recipe import fixes

- pythonforandroid/recipes/regex/__init__.py
[regex](https://pypi.python.org/pypi/regex/) - alternative regular expression module, offers additional functionality.
> Added "regex" module recipe

- pythonforandroid/recipes/websocket-client/__init__.py
> Improve documentation for websocket-client to account for SSL compatibility

- pythonforandroid/toolchain.py
Closes https://github.com/kivy/python-for-android/issues/1116
> Added --version argument

- pythonforandroid/recipe.py
pypi.python.org is the most convenient place to obtain source tar.gz archives.
Thus, to update our stale recipes, we better adapt to their new URL scheme.
Thanks, Enoch.
> Accept pypi fragmented URLs (#md5...)

- pythonforandroid/recipes/openssl/__init__.py
> Fix OpenSSL recipe crashes on x86

- pythonforandroid/recipes/preppy/__init__.py
- pythonforandroid/recipes/preppy/fix-setup.patch
- pythonforandroid/recipes/pyrxp/__init__.py
- pythonforandroid/recipes/reportlab/__init__.py
- pythonforandroid/recipes/reportlab/patches/fix-setup.patch
Just adds recipes for reportlab pdf generation package & pyrxp rxp based python xml parser
> add recipes for pyrxp & reportlab

- doc/source/troubleshooting.rst
Refs https://github.com/kivy/buildozer/issues/639
> Troubleshooting NoClassDefFoundError BASE64Encoder

- pythonforandroid/recipes/feedparser/__init__.py
Follow up (cleaned) PR of https://github.com/kivy/python-for-android/pull/1324
> Adds Python3 Crystax support to Feedparser

- pythonforandroid/toolchain.py
> decode gradle path to avoid python3 crash

- pythonforandroid/recipes/cymunk/__init__.py
> - let cymunk also be built with python3 recipe

- pythonforandroid/recipes/pycryptodome/__init__.py
- pythonforandroid/recipes/secp256k1/__init__.py
Since #1361 was merged, we can drop LDSHARED override.
> Clean-up LDSHARED, fixes #1360

- pythonforandroid/recipes/kivy/__init__.py
See both:
- https://github.com/kivy/kivy/pull/6107
- https://github.com/kivy/kivy/pull/6120
> Defaults to post kivy==1.10.1 commit for SDL 2.0.9 fixes

- pythonforandroid/recipes/enum34/__init__.py
- pythonforandroid/recipes/pyasn1/__init__.py
- pythonforandroid/recipes/pyopenssl/__init__.py
* Update enum34 to 1.1.6
* Update pyasn1 to 0.4.5
* Update pyopenssl to 19.0.0
> Update enum34, pyasn1and pyopenssl versions.

- pythonforandroid/bootstraps/common/build/build.py
Follow up fix for #1733 (untested)
> Fixes object is not subscriptable error, refs #1733

- pythonforandroid/recipe.py
> fix: "cwd is" log message was printed directly, not via debug()

- pythonforandroid/recipes/ffmpeg/__init__.py
Moved download url to github repo, in order to speed-up the download. (Current ffmpeg.org download link is freaking slow)
> Move ffmpeg download url to github repo

- pythonforandroid/recipes/ffpyplayer/__init__.py
As discussed here: https://github.com/matham/ffpyplayer/pull/69, this PR updates ffpyplayer version in order to fix ffpyplayer build process in p4a
> Fixes ffpyplayer build

- pythonforandroid/recipes/python3/__init__.py
> enable IPv6 for packaged python3

- pythonforandroid/recipes/ffmpeg/__init__.py
- pythonforandroid/recipes/libx264/__init__.py
This PR fixes `ffmpeg` and `libx264` recipes for `arm64-v8`
> Fixes ffmpeg and libx264 recipes for arm64-v8

- pythonforandroid/recipes/regex/__init__.py
> Fix and update regex's recipe

- setup.py
- tests/test_pythonpackage_basic.py
Recent pep517 release seems to break tests.
> Fixes test_virtualenv and test_venv failing, closes #1994

- doc/source/apis.rst
Correct sample code for hiding the splash screen in android.
> Documentation: android hide loading screen

- pythonforandroid/recipes/kivy/__init__.py
> automatically load/enable certifi in kivy

- README.md
- pythonforandroid/recipes/openssl/__init__.py
The merge conflicts were pretty trivial, so I just resolved them in favour of the current develop state.
What do you think about merging this? Then presumably we could merge it into the release-2020.03.30 branch as well to resolve the conflicts there.
@AndreMiras
> Merge master into develop

- Dockerfile
Using the latest released LTS.
> :arrow_up: Bumps to Ubuntu 20.04

- pythonforandroid/recipes/hostpython3/patches/pyconfig_detection.patch
> Print patched message to stderr

- pythonforandroid/recipes/android/src/android/loadingscreen.py
- pythonforandroid/recipes/android/src/android/permissions.py
> android: call non-static methods on .mActivity

- pythonforandroid/bootstraps/service_library/build/src/main/java/org/kivy/android/PythonActivity.java
mActivity is missing in PythonActivity.java
> missing mActivity

- pythonforandroid/recipes/kivy/__init__.py
Bumps Kivy stable-1.11.1 to Kivy stable-2.0.0.
> :arrow_up: Updates to Kivy2

- pythonforandroid/recipes/aiohttp/__init__.py
had this in private recipes but would probably be useful for larger audience.
Didn't find any example in tests how to test a CythonRecipe so no unit test :(
> Add recipe for https://docs.aiohttp.org/en/stable/

- pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java
- pythonforandroid/recipes/python3/__init__.py
#2337 w/o the updated Python version.
> support Python 3.9

- doc/source/quickstart.rst
-brew cask install
+brew install --cask
> Update quickstart.rst macOS brew cask command

- setup.py
> setup.py: add *.diff to package_data

- pythonforandroid/recipes/groestlcoin_hash/__init__.py
https://travis-ci.com/github/Groestlcoin/electrum-grs/jobs/489445687
> Add setuptools dependency for Groestlcoin_hash recipe

- pythonforandroid/bootstraps/common/build/build.py
I think this (also) fixes #1013.
> build.py: also clean() tarfile directory entries

- pythonforandroid/recipes/ffmpeg/__init__.py
- pythonforandroid/recipes/ffpyplayer_codecs/__init__.py
- pythonforandroid/recipes/libvpx/__init__.py
- pythonforandroid/recipes/libvpx/patches/0001-android-force-neon-runtime.patch
- tests/recipes/test_libvpx.py
This commit allows transparent videos.
See https://gist.github.com/tito/52cf2b545858358cd3d2a034337fd9fe
> Add libvpx recipe, reference it in ffpyplayer_codecs and ffmpeg

- doc/source/apis.rst
Things about BroadcastReceiver, Runnable and onActivityResult
are really important for anybody that tries to use Android apis.
I've added back in api.rst, but if another place is preferred, just
tell me :)
> Reintroduce documentation of android module

- pythonforandroid/recipes/hostpython3/__init__.py
- pythonforandroid/recipes/python3/__init__.py
NB: I haven't tested this version myself since I've been using 3.9.x.
> update (host)python3 to 3.8.9

- pythonforandroid/recipes/android/src/android/_ctypes_library_finder.py
This fixes #2468. Please refer to that issue for detailed description.
> Fix bad library found by ctypes for 64-bit arch (#2468)

- pythonforandroid/recipes/pandas/__init__.py
> fix pandas recipe

- pythonforandroid/recipes/lxml/__init__.py
> Fixes ndk_include_dir on lxml recipe.

- pythonforandroid/recipes/libcurl/__init__.py
- pythonforandroid/recipes/libogg/__init__.py
- pythonforandroid/recipes/libsecp256k1/__init__.py
- pythonforandroid/recipes/libvorbis/__init__.py
> proper --host for libsecp256k1, libogg, libvorbis, libcurl

- .github/support.yml
This PR enables `support-requests` integration.
> Add support-requests configuration.

- pythonforandroid/recipes/Pillow/__init__.py
- pythonforandroid/recipes/Pillow/patches/fix-setup.patch
That PR started with the intent to only fix issue #2497, but finished bumping the Pillow version for convenience.
Is marked as WIP, cause:
> Bump Pillow version to 8.4.0

- pythonforandroid/recipe.py
This PR cherry-picks #2544 that was erroneously merged into `master`
> Update recipe.py (#2544)

- pythonforandroid/recipes/kivy/__init__.py
> Update to Kivy 2.1.0

- pythonforandroid/recipes/tflite-runtime/__init__.py
Now, if the **requirements** has not been changed, the reassembly will not occur
> Fix issue #2630

- pythonforandroid/recipes/ffmpeg/__init__.py
Added UDP and TCP protocols to "--enable-procol" to supporting RTSP streams over each.
Added RTSP to "--enable-demuxer" to supporting RTSP with ffmpeg.
> RTSP support for ffmpeg

- doc/source/buildoptions.rst
- pythonforandroid/bootstraps/common/build/build.py
- pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
Added support if the user want to run the application as a home app (launcher).
> Home app functionality

- pythonforandroid/recipes/freetype/__init__.py
Changed the url to use https as http fails.
> Changed the url to use https as http fails

- pythonforandroid/recipes/vlc/__init__.py
> vlc: fix build

- pythonforandroid/bootstraps/common/build/build.py
- pyconfig.h was appended twice into WHITELIST_PATTERNS
- Regression from commit a636b88
> Remove redundant append into WHITELIST_PATTERNS
